### ISSUE TITLE
docker pull: "invalid reference format"

### ISSUE THREAD

**Issue by PenelopeFudd** [distribution/distribution#3250] opened 2020-09-13 06:05 UTC
Hi;

Small bug to report:
```
$ docker pull owasp/dependency–track
invalid reference format
```
Some blinkety-blankety web site authoring tool replaced the hyphen ('-') with a long hyphen ('–'), so when I copy-and-pasted the command it always failed with the error 'invalid reference format'.

Could you *please* give an error message that doesn't require users to Google their brains out for half an hour to figure out the problem?

Thanks!

**Comment by sudo-bmitch** [comment] 2021-04-11 23:50
Changing that error message would likely result in broken scripts looking for that message. And anyone googling for the new message wouldn't find all the answers for the old message (like [this SO answer](https://stackoverflow.com/a/52818152/596285)).

**Comment by PenelopeFudd** [comment] 2021-04-12 00:24
Instead of changing it, maybe add an second line of text, possibly on stderr, possibly selectable with a --verbose-error-messages option or environment variable, just something. 

Then scripts looking for the existing message will find it, the error string is still Google-able, and yet the second line can still give useful information to a human so they can solve it without resorting to Google.  Some programs (i.e. [ShellCheck](https://www.shellcheck.net/)) even put a url into the error message that links to a full explanation of what could cause that error message and how to fix it, which is way more focused than a Google search.

In this particular case, reading through all the documentation didn't help, the reference looked correct.  The true cause of the error was only found by accident when the reference was typed over again by hand and suddenly it worked.  Normally, one expects copy-and-paste to be more reliable than typing.

I feel (rightly or wrongly) that an error message should be more informative than the "check engine" light on a car's dashboard.

**Comment by sudo-bmitch** [comment] 2021-04-12 02:00
For what it's worth, after answering quite a few stackoverflow questions, copy and paste, especially from websites, causes a lot of issues. Different dashes, smart quotes, weird space characters, etc.

Links to a website can be problematic when the website changes. There are a lot of Docker EE links that went stale after the Mirantis split, and I'm sure things have broken with distribution moving out of the docker repo. With the distribution no longer a docker project, now moved out to CNCF, it would be another external source to keep in sync for docker.

As user unfriendly as the error message is, it also makes sense technically. The problem is more that error message is directly exposed in user tools, where users may not know what a reference is. The fix could be to update the docker cli to enhance the error messages, rather than the distribution project.

But my preferred option is to have a documentation page to explain various error messages from docker, could be just as useful as the Dockerfile and compose documentation pages. That also wouldn't be a CNCF change.

**Comment by joaodrp** [comment] 2021-04-12 11:46
Please consider opening an issue in https://github.com/moby/moby if looking for a more user friendly message. Closing this issue as it's not a registry bug.

**Closed by joaodrp** 2021-04-12 11:46 UTC
