### ISSUE TITLE
Crash when starting without an auth handler

### ISSUE THREAD

**Issue by ferrix** [distribution/distribution#1168] opened 2015-11-09 18:45 UTC
I am running registry:2 (docker image ddfb3bf27ae2) behind an authorizing proxy. Most of my configuration:

```
version: 0.1
log:
  level: warn
  formatter: text
  fields:
    service: registry
    environment: garden
  hooks:
    - type: mail
      levels:
      - panic
      options:
         smtp:
          addr: something
          username: foo
          password: bar
        from: docker@yes.no
    to:
      - people@else.where
storage:
   s3:
http:
  addr: :5000
```

This results in a whine about realm not being set for htpasswd auth. When I enable silly auth with realm and service, I get a nag about path not being set: 

```
auth:
  silly:
    realm: silly-realm
    service: silly-service
```

Then when I set the path, I get a nag that service is not set for silly:

```
auth:
  silly:
    realm: silly-realm
    service: silly-service
    path: '/this/is/not/happening'
```

And finally this works:

```
auth:
  silly:
    realm: silly-realm
    path: '/this/is/not/happening'
    service: silly-service
```

However then I need to send bogus silly `Authorization` headers. The same configuration worked last week.

**Comment by stevvooe** [comment] 2015-11-09 20:22
@ferrix What error message are you getting which specific configuration?

In general, `silly` auth is useful for nothing but testing. Is there something you're trying to test?

**Comment by ferrix** [comment] 2015-11-10 06:11
For the first incarnation of the config.yml:

    panic: unable to configure authorization (htpasswd): "realm" must be set for htpasswd access controller

This is for the second incarnation:

    panic: unable to configure authorization (silly): "path" must be set for htpasswd access controller

That is a bit funny since silly does not require "path" at all. The third one I don't have but practically "service" must be set for silly access controller.

The originating line was: https://github.com/docker/distribution/blob/master/registry/handlers/app.go#L236

So my theory is that nothing or something equal auth.htpasswd for some reason and those errors need to be handled some way.

I know silly is silly just as the name says. The bottom line is that it does not hurt much either unless there is some specific insecurity about it that is not documented. I do have the authenticating proxy anyway. Without it, registry crashes and I am getting nothing. So it is just a really silly workaround.

**Comment by stevvooe** [comment] 2015-11-10 20:11
@ferrix What is the output of `docker run -it registry:2 --version`?

I just tried the following configuration, with and without the `auth` section, and it worked fine:

```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
  filesystem:
    rootdirectory: /usr/local/var/lib/registry
http:
  addr: :5000
  debug:
      addr: localhost:5001
  headers:
      X-Content-Type-Options: [nosniff]
auth:
  silly:
    realm: silly-realm
    service: silly-service
```

My guess would be that there is a spacing issue or the complete configuration is incorrect in some way.

I'd recommend starting with a completely fresh configuration and turn off all environment variables. From there, work through one of the getting started handbooks.

**Comment by ferrix** [comment] 2015-11-14 09:23
Here's the version:

    /bin/registry github.com/docker/distribution v2.2.0

All of this started happening when the image got upgraded. Initially, I did not have the auth section in my configuration at all but suddenly that resulted in a crash. Also, I am validating my YAML, so spacing issues are simply not there.

**Comment by stevvooe** [comment] 2015-11-18 13:44
@ferrix Could you provide the whole configuration in a gist along with the unmodified log? I simple wasn't able to reproduce this with 2.2.

Here is the configuration I use for development:

```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
  filesystem:
    rootdirectory: /usr/local/var/lib/registry
http:
  addr: :5000
  debug:
      addr: localhost:5001
  headers:
      X-Content-Type-Options: [nosniff]
```

**Comment by thaJeztah** [comment] 2015-12-25 23:49
ping @ferrix has this been resolved for you? If not, could you provide the information that @stevvooe requested?

**Comment by dsanders11** [comment] 2015-12-29 03:08
I've also run into this issue and I think I have a reproduce case with the config @stevvooe provides.

I got the same error after upgrading to v2.2.1 from v2.1.1, and tracked it down to an errant environment variable. I'd previously played with having auth done at the registry itself before putting nginx in front of it. However, I inadvertently left `REGISTRY_AUTH_HTPASSWD_PATH` set in the environment variables file for the registry.

It looks like if that environment variable is set without any `auth` section in the registry config it will cause the panic. Perhaps it circumvents some sanity checks by being an environment variable and causes the panic instead of simply a misconfiguration error (since realm is required in the `htpasswd` section of `auth`).

**Comment by stevvooe** [comment] 2015-12-29 19:13
@dsanders11 Interesting. Thank you for the investigation.

Generally, we treat misconfigurations as panics, since they may result in unintended, insecure deployments. While in this case it was confusing, the registry took the right action by not proceeding with serving a registry that may have required authentication.

I've reproduced this behavior with the following incantation:

```
REGISTRY_AUTH_HTPASSWD_PATH=foo ./bin/registry ./cmd/registry/config-dev-osx.yml
```

We'll look into a possible bugfix for the error message, but this is still from a bad configuration.

**Comment by 3drepoinstaller** [comment] 2016-05-05 14:27
In case it helps

I did have this error message, which turned out to be a typo in the arguments:
docker run [...] -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" [...]

I had some typos in the environment variable names...

**Comment by 3Nigma** [comment] 2017-01-01 12:12
I also experienced this. It turned out that I forgot to define the ```REGISTRY_AUTH_HTPASSWD_PATH``` variable as described in https://docs.docker.com/registry/deploying/ .

I initially thought that only the highlighted red lines need to be added and thus overlooked ```REGISTRY_AUTH_HTPASSWD_PATH```. Perhaps you could highlight it as well.

![docker_htpasswd_issue](https://cloud.githubusercontent.com/assets/210908/21581145/2dda4186-d02c-11e6-9979-74c51a147ec0.png)

**Comment by stevvooe** [comment] 2017-01-06 01:29
@3Nigma The highlighting is just for string syntax in the shell command.

I am not really seeing much of an issue. In all cases, it is preventing incorrect configuration from going live. This is working as intended and the error message is reporting something actionable.

Unless anyone wants to step up and submit a PR, we should probably close this.

**Comment by milosgajdos** [comment] 2024-07-06 10:05
Closing as wildly outdated. Besides, things work as expected.

**Closed by milosgajdos** 2024-07-06 10:05 UTC
