### ISSUE TITLE
Add API for tagging images

### ISSUE THREAD

**Issue by mikekap** [distribution/distribution#1797] opened 2016-06-22 00:34 UTC
It would be nice to be able to (re)tag images via the rest API rather than the docker binary (e.g. for use inside docker images that just manage deployment, to add a "current version" tag).

**Comment by RichardScothern** [comment] 2016-06-27 17:23
@mikekap the docker daemon interacts with the registry through the API.  When you put a manifest under a tag, a tag is created/updated.

**Comment by mikekap** [comment] 2016-07-05 21:54
Does that mean I can fetch the manifest via API, change the tag field & re-push the manifest? Or is there more to it?

If possible, I'd rather not involve the docker daemon in this process. In my case the docker daemon is set up with read-only credentials for the whole fleet. There's only one container that actually needs the ability to re-tag so I don't want to escalate privileges for all the other containers.

**Comment by RichardScothern** [comment] 2016-07-05 23:13
There is no longer a tag field in the manifest (see https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md).  

You can use the rest API to put a manifest under a different tag.

**Comment by wheleph** [comment] 2016-07-13 08:06
Can you tell specifically how to do it? This seems to be confusing for many people:

- http://stackoverflow.com/questions/37134929/how-to-tag-image-in-docker-registry-v2
- http://stackoverflow.com/questions/31083868/how-do-you-manipulate-tags-in-docker-registry-2-0-and-the-v2-api

Also is there a way instruct registry to fallback to v1 API?

**Comment by wheleph** [comment] 2016-07-13 13:59
@RichardScothern I tried to do like you suggest, but still run into problems. Could you help me to sort them out? Here's what I did:

- Use registry 2.4: `docker run -p 5000:5000 registry:2.4`
- Install an image in the registry:
```
docker pull busybox
docker tag busybox 192.168.99.100:5000/mybusybox
docker push 192.168.99.100:5000/mybusybox
```
- Get manifest for the uploaded image:
`curl 'http://192.168.99.100:5000/v2/mybusybox/manifests/latest' -H "accept: application/vnd.docker.distribution.manifest.v2+jon"`. Result:
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 1459,
      "digest": "sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 667590,
         "digest": "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f"
      }
   ]
}
```
- Try to upload the manifest under a new tag: `curl -XPUT 'http://192.168.99.100:5000/v2/mybusybox/manifests/new_tag' -H "accept: application/vnd.docker.distribution.manifest.v2+json" -d '@manifest.json'`. And get error back:
```json
{
  "errors": [
    {
      "code": "MANIFEST_INVALID",
      "message": "manifest invalid",
      "detail": {}
    }
  ]
}
```
In the registry log I see this error message: 
```msg="response completed with error" err.code="manifest invalid" err.detail="missing signature key"```

Can you suggest what I'm going wrong?

**Comment by wheleph** [comment] 2016-07-13 15:24
Problem solved. I should've used `content-type` instead of `accept`:
```
'http://192.168.99.100:5000/v2/mybusybox/manifests/new_tag' -H "content-type: application/vnd.docker.distribution.manifest.v2+json" -d '@manifest.json'.
```

**Comment by pasali** [comment] 2017-05-16 20:35
@RichardScothern when i try to put a manifest under a new tag, i am getting MANIFEST_UNKNOWN error. Am i missing something ?

**Comment by dgoo2308** [comment] 2017-11-29 09:36
@RichardScothern trying to tag a pushed image with a gitlab-registry(v3.6.1-1) ends up in : 
    
    {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}

with a detail the registry log:

     err.code="manifest invalid" err.detail="missing signature key" err.message="manifest invalid”

while on open shift (3.6.0) registry that works like a charm.

any thoughts?

**Comment by genesi5** [comment] 2021-07-22 19:48
@dgoo2308  I suppose i'ts too late, but in case somebody will encounter this:

Had problem like yours, same error, same message in registry's log. The problem is that was sending a request with wrong header:

```json
{"Accept": "application/vnd.docker.distribution.manifest.v2+json"}
```
while i had to use this:
```json
{"Content-Type": "application/vnd.docker.distribution.manifest.v2+json"}
```

**Comment by dgoo2308** [comment] 2021-08-01 13:47
@genesi5 never too late, thanks

**Comment by milosgajdos** [comment] 2023-08-13 15:06
Closing. This is implemented via the `/manifest` route https://github.com/distribution/distribution/blob/69fe1690134c17c3d3a84f991c38a98fd0a064ed/registry/api/v2/descriptors.go#L518 using the `PUT` that can be either a `digest` or a `tag` https://github.com/distribution/distribution/blob/69fe1690134c17c3d3a84f991c38a98fd0a064ed/registry/api/v2/descriptors.go#L571

**Closed by milosgajdos** 2023-08-13 15:06 UTC
