### ISSUE TITLE
Private registry push fails

### ISSUE THREAD

**Issue by kopax** [distribution/distribution#1754] opened 2016-05-28 00:42 UTC
I can pull from my private registry but I can't push for some reasons.

By running the commands :

```
docker pull alpine
docker tag alpine alpine
docker login registry.mydomain.com -> success
docker push registry.mydomain.com/alpine
```

The push starts the first layers, then timeout for a while.

I have a tcp io timeout error at the end.

```
The push refers to a repository [registry.mydomain.com/alpine]
8f01a53880b9: Pushing 133.6 kB/4.797 MB
dial tcp 179.43.231.99:80: i/o timeout
```

Daemon used:

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

I have test with `registry:2` and `registry:2.4.1`

I am using `nginx:1.7` exactly like explained in [here](https://docs.docker.com/registry/nginx/)

I have SSL and auth configured. 

The UI+auth of the registry is working well on port 443.

When trying to push the `alpine` to nginx : 

```
82.254.222.221 - rvb [28/May/2016:08:28:48 +0200] "POST /v2/alpine/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \x5C(linux\x5C))"
82.254.222.221 - rvb [28/May/2016:08:29:34 +0200] "POST /v2/alpine/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \x5C(linux\x5C))"
```

The registry logs :

```
172.16.0.3 - - [28/May/2016:06:30:20 +0000] "POST /v2/alpine/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"

time="2016-05-28T06:34:00Z" level=info msg="response completed" go.version=go1.6.2 http.request.host=registry.service.consul http.request.id=093c87a8-3e76-41d4-b7a7-861c3e4b072c http.request.method=POST http.request.remoteaddr=82.254.222.221 http.request.uri="/v2/alpine/blobs/uploads/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))" http.response.duration=173.480161ms http.response.status=202 http.response.written=0 instance.id=593250d0-b83d-421f-824c-3adc2156d8e0 version=v2.4.1 
172.16.0.3 - - [28/May/2016:06:34:00 +0000] "POST /v2/alpine/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
```

**nginx.conf**

```
user www-data;
worker_processes auto;

worker_rlimit_nofile 8192;
pid /var/run/nginx.pid;

events {
  multi_accept on;
  worker_connections 4096;
  use epoll;
}

http {
  ##
  # custom settings
  ##

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_tokens off;
  client_max_body_size 0;

  server_names_hash_bucket_size 128;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  ##
  # Virtual Host Configs
  ##

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}
```

**sites-enabled/registry.conf**

```
## Set a variable to help us decide if we need to add the
## 'Docker-Distribution-Api-Version' header.
## The registry always sets this header.
## In the case of nginx performing auth, the header will be unset
## since nginx is auth-ing before proxying.

map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
  'registry/2.0' '';
  default registry/2.0;
}

server {
  listen 443 ssl;
  server_name registry.mydomain.com;

  # SSL
ssl on;

# certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
ssl_certificate /etc/ssl/certs/wildcard.mydomain.com.chained.crt;
ssl_certificate_key /etc/ssl/private/wildcard.mydomain.com.key;
ssl_session_timeout 24h;
ssl_session_cache shared:SSL:10m;

# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits or better
ssl_dhparam /etc/ssl/dhparam-2048.pem;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
ssl_prefer_server_ciphers on;


## verify chain of trust of OCSP response using Root CA and Intermediate certs
ssl_trusted_certificate /etc/ssl/certs/GandiStandardSSLCA2.pem;

  # disable any limits to avoid HTTP 413 for large image uploads
  client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
  chunked_transfer_encoding on;

  location / {
      # let Nginx know about our auth file
      auth_basic              "Restricted";
      auth_basic_user_file             /etc/nginx/htpasswd/registry/.htpasswd;

      ## set upstream
      set $upstream registry.service.consul;

      ## include upstream config
      include /etc/nginx/upstream-conf/default.conf;
  }

  location /v2/ {
    ## If $docker_distribution_api_version is empty, the header will not be added.
    ## See the map directive above where this variable is defined.
    add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

    ## set upstream
    set $upstream registry.service.consul;

    ## include upstream config
    include /etc/nginx/upstream-conf/default.conf;

    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
    if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
      return 404;
    }

    client_max_body_size 0;

    # To add basic authentication to v2 use auth_basic setting plus add_header
    auth_basic "Registry realm";
    auth_basic_user_file             /etc/nginx/htpasswd/registry/.htpasswd;

  }


  location /_ping {
    auth_basic off;

    ## set upstream
    set $upstream registry.service.consul;

    ## include upstream config
    include /etc/nginx/upstream-conf/default.conf;

  }  

  location /v1/_ping {
    auth_basic off;
    return 200 'V2 registry';
  }

  access_log  /var/log/nginx/registry_access.log;
  error_log   /var/log/nginx/registry_error.log;

}
```

**upstream-conf/default.conf**

```
proxy_pass http://$upstream;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_read_timeout 900;
proxy_send_timeout 900;
```

Does anyone understand why I cannot push to my private registry ?

**Comment by EugenMayer** [comment] 2016-05-28 14:48
Exactly the same issue here, see https://github.com/EugenMayer/kontextwork-catalog/issues/1 - interestingly, i have a working case with just a different nginx version ( barebone working, container nginx is not working )

**Comment by EugenMayer** [comment] 2016-05-28 15:29
@kopax after playing arround with different HAproxy, nginx and registry setup, flipping them arround to see what could be the cause i found it, its neither of them, its the docker version on the client. Check my issue for further reading

**Comment by kopax** [comment] 2016-05-30 09:41
@EugenMayer updating docker to latest builld didn't change for me. I had to remove completely haproxy

**Comment by EugenMayer** [comment] 2016-05-30 09:52
@kopax i can confirm that HAproxy works without issues with registry:2.3.1 and 2.4.1, while using either a portus as token auth or basic auth. I am using HAproxy with SSL termination, registry is not configured with TLS. All my configs you will find in the other issue

**Comment by kopax** [comment] 2016-05-30 09:53
so in your config, nginx is not handling SSL terminaison? Just Haproxy?

**Comment by EugenMayer** [comment] 2016-05-30 09:55
yes. I dont do HA->nginx(ssl)->registry, i do HA(ssl)->registry

**Comment by kopax** [comment] 2016-05-30 09:56
Ok, and I do nginx(ssl+auth)->HAproxy(http reverse proxy)->registry. 
I suspect my issue to be in the header of HA to registry

**Comment by RichardScothern** [comment] 2016-06-13 21:43
@kopax did that work out for you?

**Comment by milosgajdos** [comment] 2024-07-06 10:09
Closing as wildly outdated.

**Closed by milosgajdos** 2024-07-06 10:09 UTC
