### ISSUE TITLE
registry can't run up when special character in REGISTRY_HTTP_SECRET env

### ISSUE THREAD

**Issue by zyyw** [distribution/distribution#3636] opened 2022-04-26 09:49 UTC
When I set REGISTRY_HTTP_SECRET to `>Z4&t2CyKuNp}qy2`, the registry can't start with error message like below:
```
Apr 26 09:35:59 ubuntu-harbor registry[3418]: configuration error: error parsing /etc/registry/config.yml: yaml: did not find expected comment or line break
Apr 26 09:35:59 ubuntu-harbor registry[3418]: Usage:
Apr 26 09:35:59 ubuntu-harbor registry[3418]:   registry serve <config> [flags]
Apr 26 09:35:59 ubuntu-harbor registry[3418]: Flags:
Apr 26 09:35:59 ubuntu-harbor registry[3418]:   -h, --help=false: help for serve
Apr 26 09:35:59 ubuntu-harbor registry[3418]: Additional help topics:
```

**Comment by deleteriousEffect** [comment] 2022-04-27 17:27
@zyyw this is a yaml parsing issue, you'll need to quote strings with special characters: https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

Looks like you're using an environment variable, try exporting that value with double quotes `export REGISTRY_HTTP_SECRET='">Z4&t2CyKuNp}qy2"'` and see if that works.

**Comment by wy65701436** [comment] 2022-04-28 08:49
yes, you should use the above example to specify values if it contains any sepcial character. Close it as not a bug.

**Closed by wy65701436** 2022-04-28 08:49 UTC
