### ISSUE TITLE
Transient MalformedXML error in the registry pod 

### ISSUE THREAD

**Issue by BrandonWeng** [distribution/distribution#3602] opened 2022-03-04 17:30 UTC
Has anyone seen this issue before? One of our users reported that for several minutes they were observing this issue and the image pushing was failing for them.

It self-resolved after 2-3 minutes. From the logs it seems like this was an issue with the request sent to S3 [S3](https://aws.amazon.com/premiumsupport/knowledge-center/config-malformedxml-error/)

```
2022-02-02T22:05:41.615Z time="2022-02-02T22:05:41.614819641Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
2022-02-02T22:05:41.579Z time="2022-02-02T22:05:41.578907228Z" level=error msg="unknown error completing upload: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
2022-02-02T22:05:41.579Z time="2022-02-02T22:05:41.578941342Z" level=error msg="error canceling upload after error: already committed"...
```

Related: https://github.com/goharbor/harbor/issues/16325#issuecomment-1030885532

**Comment by Jamstah** [comment] 2022-07-05 16:01
The s3 calls are all through a library, so I would expect it to generate well-formed XML. The library has been updated since this issue was opened: https://github.com/distribution/distribution/pull/3599

I doubt this project can do much unless we can get something reproducible.

**Comment by milosgajdos** [comment] 2024-07-06 10:23
Closing for the lack of noise from the OG reporter. Feel free to reopen.

**Closed by milosgajdos** 2024-07-06 10:23 UTC
