### ISSUE TITLE
Issue writing to S3 bucket

### ISSUE THREAD

**Issue by cooktheryan** [distribution/distribution#945] opened 2015-08-28 20:00 UTC
```
# Registry output 
time="2015-08-28T19:52:53.770649612Z" level=debug msg="authorizing request" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=0e211cd9-e8b7-49e1-a2cf-e273bae87e24 http.request.method=GET http.request.remoteaddr="192.168.1.100:57426" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:53.770737772Z" level=info msg="response completed" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=0e211cd9-e8b7-49e1-a2cf-e273bae87e24 http.request.method=GET http.request.remoteaddr="192.168.1.100:57426" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.507441ms http.response.status=200 http.response.written=2 instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
192.168.1.100 - - [28/Aug/2015:19:52:53 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64"
time="2015-08-28T19:52:53.928287497Z" level=debug msg="authorizing request" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=ef2db0ae-4c73-44d9-8c70-3cb806b28abb http.request.method=GET http.request.remoteaddr="192.168.1.100:57427" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:53.928373648Z" level=info msg="response completed" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=ef2db0ae-4c73-44d9-8c70-3cb806b28abb http.request.method=GET http.request.remoteaddr="192.168.1.100:57427" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.49359ms http.response.status=200 http.response.written=2 instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
192.168.1.100 - - [28/Aug/2015:19:52:53 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64"
time="2015-08-28T19:52:54.123358846Z" level=debug msg="authorizing request" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=895ce801-dbbc-40c8-8fd0-0a5cd5114c4d http.request.method=GET http.request.remoteaddr="192.168.1.100:57428" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.123460082Z" level=info msg="response completed" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=895ce801-dbbc-40c8-8fd0-0a5cd5114c4d http.request.method=GET http.request.remoteaddr="192.168.1.100:57428" http.request.uri="/v2/" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.51959ms http.response.status=200 http.response.written=2 instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
192.168.1.100 - - [28/Aug/2015:19:52:54 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64"
time="2015-08-28T19:52:54.307479136Z" level=debug msg="authorizing request" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.307566417Z" level=debug msg=GetBlob environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.382830755Z" level=debug msg="s3.GetContent(\"/docker/registry/v2/repositories/test/_layers/sha256/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/link\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=75.182475ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=1ef4af16-b80a-49c6-a438-7b5c045935f9 trace.line=55 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.430626106Z" level=debug msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/e5/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/data\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=47.658296ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=61bd9842-a514-4bbc-b15a-79d40139beb6 trace.line=111 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.451144915Z" level=debug msg="s3.GetContent(\"/docker/registry/v2/repositories/test/_layers/sha256/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/link\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=20.394003ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=4a79e6cd-2412-43ea-9ec2-7bb733d070f6 trace.line=55 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.491977486Z" level=debug msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/e5/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/data\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=40.708066ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=c6bfe5c5-7a09-4afd-8fe3-0227741f30e5 trace.line=111 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.546601975Z" level=debug msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/e5/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/data\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=54.478431ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=3119fa8d-407a-4ea5-b864-39e2935695f6 trace.line=111 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.546860991Z" level=debug msg="s3.URLFor(\"/docker/registry/v2/blobs/sha256/e5/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/data\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=141.172µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).URLFor" trace.id=39820966-bdbc-411b-a224-63a46c94b6da trace.line=161 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.566610292Z" level=debug msg="s3.GetContent(\"/docker/registry/v2/repositories/test/_layers/sha256/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/link\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=19.65831ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=2204bb72-f6ab-467d-9d29-12f0ca4ac7a5 trace.line=55 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.613294581Z" level=debug msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/e5/e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada/data\")" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=46.578099ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=4721651f-4d00-40ba-b00e-da86c96b8a3f trace.line=111 vars.digest="sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" vars.name=test version=v2.1.1-43-g1927c6c.m 
time="2015-08-28T19:52:54.613462392Z" level=info msg="response completed" environment=development http.request.host="registry-host01.prod.somewhere.com:5000" http.request.id=fb325223-18b9-498f-bf1c-8f1573d1dbd0 http.request.method=HEAD http.request.remoteaddr="192.168.1.100:57429" http.request.uri="/v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada" http.request.useragent="docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64" http.response.contenttype="application/octet-stream" http.response.duration=307.492998ms http.response.status=307 http.response.written=0 instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry version=v2.1.1-43-g1927c6c.m 
192.168.1.100 - - [28/Aug/2015:19:52:54 +0000] "HEAD /v2/test/blobs/sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada HTTP/1.1" 307 0 "" 
"docker/1.7.1.fc22 go/go1.4.2 kernel/4.1.6-200.fc22.x86_64 os/linux arch/amd64"
time="2015-08-28T19:52:57.035854365Z" level=debug msg="s3.List(\"/\")" environment=development instance.id=842e4b08-bfad-4639-8afa-4f0e1ad3f6aa service=registry trace.duration=27.443081ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=e329a10c-12ef-4e72-b6f4-d2b1730c84e9 trace.line=123 version=v2.1.1-43-g1927c6c.m 
```
# Client attempt to push

```
docker push registry-host01.prod.somewhere.com:5000/test
```
# client version

```
Docker version 1.7.1.fc22
```
# registry version

```
2.0+ pulled from master this morning
```
# config.yml

```
version: 0.1
loglevel: debug
storage:
  s3:
    accesskey: removed
    secretkey: removed
    region: Removed
    bucket: Removed
    encrypt: true
    secure: false
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
http:
    addr: 0.0.0.0:5000
    debug:
        addr: 0.0.0.0:5001
    tls:
        certificate: /usr/lib/golang/src/github.com/docker/distribution/certs/Removed
        key: /usr/lib/golang/src/github.com/docker/distribution/certs/Removed

notifications:
    endpoints:
        - name: local-8082
          url: http://localhost:5003/callback
          headers:
             Authorization: [Bearer <an example token>]
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
        - name: local-8083
          url: http://localhost:8083/callback
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
```
# Error

[rcook@goku ~]$ docker push registry-host01.prod.somewhere.com:5000/test
The push refers to a repository [registry-host01.prod.somewhere.com:5000/test](len: 1)
e3c92c6cff35: Image push failed 
Error pushing to registry: Server error: 400 trying head request for test - sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada

**Comment by dmp42** [comment] 2015-08-28 20:11
Sorry, what's the issue?
I don't see an error in the logs.

Thanks.

**Comment by cooktheryan** [comment] 2015-08-28 20:15
Updated sorry about that

**Comment by dmp42** [comment] 2015-08-28 20:29
@cooktheryan ok, do you have the registry logs that show the 400 on the server side?

**Comment by cooktheryan** [comment] 2015-08-28 20:35
The logs in the beginning were all that was given in the output. Those logs were from the server.

**Comment by dmp42** [comment] 2015-08-28 20:59
Ok, can you get your docker *daemon* logs? Usually `journalctl` or `/var/log/upstart/docker.log`

**Comment by cooktheryan** [comment] 2015-08-28 21:20
# Server
-bash-4.2# journalctl -xn
-- Logs begin at Thu 2015-08-27 17:01:11 UTC, end at Fri 2015-08-28 21:18:06 UTC. --
Aug 28 21:18:01 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:01.504256876Z" level=info msg="GET /containers/json"
Aug 28 21:18:01 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:01.606817964Z" level=info msg="GET /containers/json"
Aug 28 21:18:01 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:01.709392726Z" level=info msg="GET /containers/json"
Aug 28 21:18:01 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:01.811917034Z" level=info msg="GET /containers/json"
Aug 28 21:18:01 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:01.914659315Z" level=info msg="GET /containers/json"
Aug 28 21:18:02 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:02.017410984Z" level=info msg="GET /containers/json"
Aug 28 21:18:02 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:02.120182704Z" level=info msg="GET /containers/json"
Aug 28 21:18:02 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:02.222967091Z" level=info msg="GET /containers/json"
Aug 28 21:18:02 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:02.325736588Z" level=info msg="GET /containers/json"
Aug 28 21:18:06 registry-host01.prod.somewhere.com docker[129644]: time="2015-08-28T21:18:06.199917433Z" level=info msg="GET /version"


# Client
Aug 28 17:20:07 goku. docker[1082]: time="2015-08-28T17:20:07.314987954-04:00" level=info msg="POST /v1.19/images/registry-host01.prod.somewhere.com/test/push?tag="

**Comment by stevvooe** [comment] 2015-08-28 21:30
@dmp42 It looks like s3 is issuing the 400, likely on redirect. Notice the `HEAD` request returns a 307. We'll have to investigate why s3 is rejecting the generated signed url. My guess is that this has something to do with v4 auth.

As an alternative, you can disable redirects.

**Comment by cooktheryan** [comment] 2015-08-31 13:28
I tested this by putting
  redirect:
    disable: true

But still received this 
e3c92c6cff35: Image push failed 
Error pushing to registry: Server error: 400 trying head request for test - sha256:e5b1e91fc7747f5121550b1f4d605788fdaddef9d6cab3230c79362eab057ada

**Comment by romanek-adam** [comment] 2015-09-01 10:08
I can confirm the issue on Docker v1.7.1 and Docker Registry v2.1.1. Apparently using Docker v1.7.0 is a workaround (at least it works for me).

**Comment by stevvooe** [comment] 2015-09-02 20:07
@cooktheryan Interesting. I'm very surprised that had the same exact failure. What is the log line for the head request in that case? Do you still see the `307`?

@romanek-adam That is an interesting data point. There were some fixes for V2/V1 fallback in 1.7.1 @dmcgowan Any ideas?

**Comment by RichardScothern** [comment] 2015-09-16 18:03
@cooktheryan : do you have any update on this from stevvooe's questions?

**Comment by mv012004** [comment] 2015-10-26 14:59
Also is there an issue with the docker client 1.7.1 with storage redirect?
I dont want for my client to connect to S3 directly, and want everything to go through the registry. I believe my understanding of the storage redirect disabled:true will help achieve that however the client still tries to connect to S3. 

Has anyone seen this behavior  ?

**Comment by BrianBland** [comment] 2016-01-26 01:57
@cooktheryan @mv012004 Did you disable storage redirection at the right level in the configuration file? It should look something like this:

```yaml
storage:
  s3:
    accesskey: awsaccesskey
    secretkey: awssecretkey
    region: us-west-1
    bucket: bucketname
    encrypt: true
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /s3/object/name/prefix
  redirect:
    disable: false
```

**Comment by cooktheryan** [comment] 2016-01-26 01:59
I can't provide insight into this as I switched roles. Hopefully @mv012004
will have some info.

**Comment by milosgajdos** [comment] 2023-08-13 14:26
Closing as outdated both from the server and client side. Pleeae feel free to reopen if the issue still persists.

**Closed by milosgajdos** 2023-08-13 14:26 UTC
