### ISSUE TITLE
golang 1.16 fails to builld: problem with modules

### ISSUE THREAD

**Issue by helllamer** [distribution/distribution#3374] opened 2021-03-04 09:19 UTC
During maintaining of [archlinux/docker-registry2-git](https://aur.archlinux.org/packages/docker-registry2-git/) AUR package, problem with building occured after distro.updating from `go-1.15` to `go-1.16`:
```
$ LC_ALL=C makepkg -s
==> Making package: docker-registry2-git r2914.89337b7a-1 (Thu Mar  4 12:15:11 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating docker-registry2-git git repo...
Fetching origin
  -> Found docker-registry.conf
  -> Found docker-registry.service
  -> Found docker-registry.sysusers
==> Validating source files with sha256sums...
    docker-registry2-git ... Skipped
    docker-registry.conf ... Passed
    docker-registry.service ... Passed
    docker-registry.sysusers ... Passed
==> Extracting sources...
  -> Creating working copy of docker-registry2-git git repo...
Cloning into 'docker-registry2-git'...
done.
==> Starting pkgver()...
==> Starting build()...
+ GOPATH=/var/user/projects/pkgbuild/docker-registry-git/src
+ go get -v github.com/distribution/distribution/cmd/registry
go: downloading github.com/distribution/distribution v2.7.1+incompatible
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/Azure/azure-sdk-for-go v0.2.0-beta
go: downloading github.com/Shopify/logrus-bugsnag v0.0.0-20171204204709-577dee27f20d
go: downloading github.com/aws/aws-sdk-go v1.37.23
go: downloading github.com/Azure/azure-sdk-for-go v52.3.0+incompatible
go: downloading github.com/bugsnag/bugsnag-go v1.9.0
go: downloading github.com/docker/libtrust v0.0.0-20160708172513-aabc10ec26b7
go: downloading github.com/garyburd/redigo v1.6.2
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/denverdino/aliyungo v0.0.0-20210222084345-ddfe3452f5e8
go: downloading github.com/docker/go-metrics v0.0.1
go: downloading github.com/bshuster-repo/logrus-logstash-hook v1.0.0
go: downloading github.com/bugsnag/bugsnag-go v2.1.0+incompatible
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/spf13/cobra v1.1.3
go: downloading github.com/ncw/swift v1.0.53
go: downloading github.com/sirupsen/logrus v1.8.0
go: downloading github.com/mitchellh/mapstructure v1.4.1
go: downloading github.com/yvasiyarov/gorelic v0.0.7
go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
go: downloading golang.org/x/oauth2 v0.0.0-20210220000619-9bb904979d93
go: downloading google.golang.org/api v0.40.0
go: downloading google.golang.org/cloud/storage v1.14.0
go: downloading google.golang.org/cloud v0.78.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading rsc.io/letsencrypt v0.0.3
go get: google.golang.org/cloud@none updating to
	google.golang.org/cloud@v0.78.0: parsing go.mod:
	module declares its path as: cloud.google.com/go
	        but was required as: google.golang.org/cloud
==> ERROR: A failure occurred in build().
    Aborting...
```

```
$ go version
go version go1.16 linux/amd64
```

`go-1.15` builds ok.

**Comment by milosgajdos** [comment] 2021-03-18 15:59
Possible duplicate of https://github.com/distribution/distribution/issues/3377

**Comment by mloskot** [comment] 2021-04-22 21:07
> go-1.15 builds ok.

I confirm this. I've successfully built the registry on `golang:1.15.11-windowsservercore` where the `make binaries` leveraging the vendor deps as suggested in https://github.com/distribution/distribution/issues/3377#issuecomment-802043749 is not an option

> Possible duplicate of #3377

I think, it's the other way around

**Comment by milosgajdos** [comment] 2023-08-14 15:33
Given the GO versions referenced in this issue are outdated and no longer supported I believe we should close this issue.

**Closed** 2023-08-17 08:04 UTC
