### ISSUE TITLE
Docker push for OSS storage ( supporting SWIFT) fails with unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by sunil3s3** [distribution/distribution#1881] opened 2016-08-05 07:14 UTC
I have configured registry with backend storage as OSS( object storage) which support SWIFT. But docker push fails with unexpected HTTP status: 500 Internal Server Error
# docker push xxxxxxxx.com:5000/oraclelinux:latest

The push refers to a repository [xxxxxxxxx.com:5000/oraclelinux]
11327e04fac0: Pushing [==================================================>]   289 MB
received unexpected HTTP status: 500 Internal Server Error

I'm using 1.12 docker-engine, tried with 1.10 docker-engine as well
# rpm -qa | grep -i docker-engine

docker-engine-1.12.0-1.el7.x86_64
docker-engine-selinux-1.12.0-1.el7.noarch

**Comment by RichardScothern** [comment] 2016-08-05 17:23
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by sunil3s3** [comment] 2016-08-09 13:12
# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-2755141-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 1.551 GB
 Data Space Total: 107.4 GB
 Data Space Available: 25.09 GB
 Metadata Space Used: 2.777 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-32.2.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 251.6 GiB
Name: den-i026.us.oracle.com
ID: DKRO:COZA:MLEU:PMNM:3RJZ:LYME:XC6R:ER4B:PZ7J:G5PB:2LEG:YSGN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://www-xxxx..com:80/
Https Proxy: http://www-xxxx..com:80/
Registry: https://index.docker.io/v1/
Insecure Registries:
 xxxxxxx..com:5000
 127.0.0.0/8


# docker exec 55aec3b541fb registry -v
registry github.com/docker/distribution v2.2.0

**Comment by sunil3s3** [comment] 2016-08-09 13:13
Command used to start docker registry 
docker run --restart=always --privileged=true -d --name pdit-registry5 -p x.x.x.:5000:5000 -e "REGISTRY_STORAGE=swift" -e "REGISTRY_STORAGE_SWIFT_USERNAME=Storage-xxxxx:xxxxx.Storageadmin" -e "REGISTRY_STORAGE_SWIFT_PASSWORD=xxxxxx" -e "REGISTRY_STORAGE_SWIFT_AUTHURL=https://xxxxxxx.corp.com/auth/v1.0" -e "REGISTRY_STORAGE_SWIFT_CONTAINER=PDIT_REGISTRY" -e  distribution/registry &

**Comment by sunil3s3** [comment] 2016-08-09 13:17
Error logs from docker logs


time="2016-08-06T06:37:59.886228047Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"
time="2016-08-07T06:38:05.119978668Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"
time="2016-08-08T06:38:10.147081926Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"
time="2016-08-09T05:34:51.790459015Z" level=error msg="response completed with error" environment=development err.code="BLOB_UNKNOWN" err.detail=sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89 err.message="blob unknown to registry" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=7460ea26-92c9-49a0-a9e1-37861c16ead0 http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=88.411365ms http.response.status=404 http.response.written=157 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.2.0
time="2016-08-09T05:35:55.129536436Z" level=error msg="error resolving upload: parsing time \"Tue, 09 Aug 2016 05:34:54 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" environment=development go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=ae9416a8-e8fa-4343-95ef-711a2c4e4150 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/a3201700-6c01-4041-aa18-2144f685e631?_state=2A5MA_5VLC3exAE-wEdnuj8zalT65l0dLzs5EMyvO9R7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJhMzIwMTcwMC02YzAxLTQwNDEtYWExOC0yMTQ0ZjY4NWU2MzEiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM0OjUxWiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=a3201700-6c01-4041-aa18-2144f685e631 version=v2.2.0
time="2016-08-09T05:35:55.129675593Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Tue, 09 Aug 2016 05:34:54 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=ae9416a8-e8fa-4343-95ef-711a2c4e4150 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/a3201700-6c01-4041-aa18-2144f685e631?_state=2A5MA_5VLC3exAE-wEdnuj8zalT65l0dLzs5EMyvO9R7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJhMzIwMTcwMC02YzAxLTQwNDEtYWExOC0yMTQ0ZjY4NWU2MzEiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM0OjUxWiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=303.80283ms http.response.status=500 http.response.written=201 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=a3201700-6c01-4041-aa18-2144f685e631 version=v2.2.0
time="2016-08-09T05:36:00.344451358Z" level=error msg="response completed with error" environment=development err.code="BLOB_UNKNOWN" err.detail=sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89 err.message="blob unknown to registry" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=5b8896c8-c980-4e38-996c-f220063e066b http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=75.780972ms http.response.status=404 http.response.written=157 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.2.0
time="2016-08-09T05:37:08.878937978Z" level=error msg="error resolving upload: parsing time \"Tue, 09 Aug 2016 05:36:02 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" environment=development go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=0767b54b-1b83-41b9-97b0-816c8d0a8a32 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/8b65030d-4a68-47f1-87ae-ea41f9699fce?_state=6GE7Pd8XOG1LJQf3TCN7jkh4fYGXdBzdHDX85zGyiMt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiI4YjY1MDMwZC00YTY4LTQ3ZjEtODdhZS1lYTQxZjk2OTlmY2UiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM2OjAwWiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=8b65030d-4a68-47f1-87ae-ea41f9699fce version=v2.2.0
time="2016-08-09T05:37:08.879049087Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Tue, 09 Aug 2016 05:36:02 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=0767b54b-1b83-41b9-97b0-816c8d0a8a32 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/8b65030d-4a68-47f1-87ae-ea41f9699fce?_state=6GE7Pd8XOG1LJQf3TCN7jkh4fYGXdBzdHDX85zGyiMt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiI4YjY1MDMwZC00YTY4LTQ3ZjEtODdhZS1lYTQxZjk2OTlmY2UiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM2OjAwWiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=260.29467ms http.response.status=500 http.response.written=201 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=8b65030d-4a68-47f1-87ae-ea41f9699fce version=v2.2.0
time="2016-08-09T05:37:19.152922494Z" level=error msg="response completed with error" environment=development err.code="BLOB_UNKNOWN" err.detail=sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89 err.message="blob unknown to registry" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=c3e12fd8-9a83-47df-9dcf-2c36a9b1d2e5 http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=90.331198ms http.response.status=404 http.response.written=157 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.2.0
time="2016-08-09T05:38:23.325193199Z" level=error msg="error resolving upload: parsing time \"Tue, 09 Aug 2016 05:37:21 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" environment=development go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=a83c314c-a910-40f7-9a78-bfd564735a12 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/b1cd9e11-3e38-408d-87e7-1c64ccea5736?_state=CW1E1Jzh83NFIlp-W028BzErvOc8KjWgZHwsDujSEIt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJiMWNkOWUxMS0zZTM4LTQwOGQtODdlNy0xYzY0Y2NlYTU3MzYiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM3OjE5WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=b1cd9e11-3e38-408d-87e7-1c64ccea5736 version=v2.2.0
time="2016-08-09T05:38:23.325316359Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Tue, 09 Aug 2016 05:37:21 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=a83c314c-a910-40f7-9a78-bfd564735a12 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/b1cd9e11-3e38-408d-87e7-1c64ccea5736?_state=CW1E1Jzh83NFIlp-W028BzErvOc8KjWgZHwsDujSEIt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJiMWNkOWUxMS0zZTM4LTQwOGQtODdlNy0xYzY0Y2NlYTU3MzYiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM3OjE5WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=261.341145ms http.response.status=500 http.response.written=201 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=b1cd9e11-3e38-408d-87e7-1c64ccea5736 version=v2.2.0
time="2016-08-09T05:38:38.680427688Z" level=error msg="response completed with error" environment=development err.code="BLOB_UNKNOWN" err.detail=sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89 err.message="blob unknown to registry" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=36342210-96a3-46f2-a7cb-5ff9ca8dd803 http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=217.97474ms http.response.status=404 http.response.written=157 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.2.0
time="2016-08-09T05:39:48.045948462Z" level=error msg="error resolving upload: parsing time \"Tue, 09 Aug 2016 05:38:40 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" environment=development go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=cdc3bf9a-73ad-4039-8b16-b791896a3e7e http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/7aa324b5-4794-43c3-84ad-40c6aa8350b9?_state=98sR1CjSC2-zlssZrQXQcd94KwRx5ya34yqZNTnFYGt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiI3YWEzMjRiNS00Nzk0LTQzYzMtODRhZC00MGM2YWE4MzUwYjkiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM4OjM4WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=7aa324b5-4794-43c3-84ad-40c6aa8350b9 version=v2.2.0
time="2016-08-09T05:39:48.046063579Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Tue, 09 Aug 2016 05:38:40 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=cdc3bf9a-73ad-4039-8b16-b791896a3e7e http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/7aa324b5-4794-43c3-84ad-40c6aa8350b9?_state=98sR1CjSC2-zlssZrQXQcd94KwRx5ya34yqZNTnFYGt7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiI3YWEzMjRiNS00Nzk0LTQzYzMtODRhZC00MGM2YWE4MzUwYjkiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjM4OjM4WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=292.725821ms http.response.status=500 http.response.written=201 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=7aa324b5-4794-43c3-84ad-40c6aa8350b9 version=v2.2.0
time="2016-08-09T05:40:08.306559528Z" level=error msg="response completed with error" environment=development err.code="BLOB_UNKNOWN" err.detail=sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89 err.message="blob unknown to registry" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=3ed0a35e-cc36-40bb-ab59-e8f70dbe62fb http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=86.796936ms http.response.status=404 http.response.written=157 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.2.0
time="2016-08-09T05:41:18.118893564Z" level=error msg="error resolving upload: parsing time \"Tue, 09 Aug 2016 05:40:10 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" environment=development go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=b84fb9e6-3455-4c65-b5b3-4b95c0105cc4 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/efdedc15-8633-4996-8d17-27095f41152d?_state=DNLyEbMMsqY-wAwQq4FT0oJXU-o9gyNzcCXmAls022N7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJlZmRlZGMxNS04NjMzLTQ5OTYtOGQxNy0yNzA5NWY0MTE1MmQiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjQwOjA4WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=efdedc15-8633-4996-8d17-27095f41152d version=v2.2.0
time="2016-08-09T05:41:18.119004634Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Tue, 09 Aug 2016 05:40:10 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" go.version=go1.4.3 http.request.host="xxxxxxx.xxxxxxx:5000" http.request.id=b84fb9e6-3455-4c65-b5b3-4b95c0105cc4 http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/oraclelinux/blobs/uploads/efdedc15-8633-4996-8d17-27095f41152d?_state=DNLyEbMMsqY-wAwQq4FT0oJXU-o9gyNzcCXmAls022N7Ik5hbWUiOiJvcmFjbGVsaW51eCIsIlVVSUQiOiJlZmRlZGMxNS04NjMzLTQ5OTYtOGQxNy0yNzA5NWY0MTE1MmQiLCJPZmZzZXQiOjk3ODM3ODUwLCJTdGFydGVkQXQiOiIyMDE2LTA4LTA5VDA1OjQwOjA4WiJ9&digest=sha256%3A10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=314.377142ms http.response.status=500 http.response.written=201 instance.id=ebf30432-0ccf-4691-8901-d0b7636abe91 service=registry vars.name=oraclelinux vars.uuid=efdedc15-8633-4996-8d17-27095f41152d version=v2.2.0
time="2016-08-09T05:50:36.249768971Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"
time="2016-08-09T07:01:47.444524642Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"

**Comment by sunil3s3** [comment] 2016-08-09 13:18
Object storage ( ZFS storage) which supports SWIFT is being used

**Comment by sunil3s3** [comment] 2016-08-09 13:18
no proxy is being used .

Please let  me know if more information is required

**Comment by RichardScothern** [comment] 2016-08-09 16:28
v2.2.0 is a fairly old registry version.  There have been bug fixes related to the swift header in more recent versions.  If possible can you upgrade to 2.5.0?  `library/registry:latest` is the image you want, not `distribution/registry`

**Comment by sunil3s3** [comment] 2016-08-10 03:57
Tried latest registry as well, its the same issue being faced.

# docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
registry                                  latest              c6c14b3960bd        11 days ago         33.28 MB
oraclelinux                               latest              1988eb5b3fc6        2 weeks ago         278.2 MB
golang                                    1.6-alpine          6b317e0ae72c        3 weeks ago         282.9 MB
distribution/registry                     latest              6d263fc92047        8 months ago        666.4 MB


# docker run -i -t registry:latest -v
registry github.com/docker/distribution v2.5.0

**Comment by RichardScothern** [comment] 2016-08-11 00:18
Which backend store implementation and version are you using?  There is something odd about the dates in those headers.

**Comment by sunil3s3** [comment] 2016-08-11 09:50
ZFS storage appliance which supports SWIFT

**Comment by RichardScothern** [comment] 2016-08-11 17:44
Interesting.  The problem here is the upload cannot be resumed because the data in the startedat file can't be parsed.  

There should be a file on storage within the  repository, something like
`oraclelinux/_uploads/679704e6-0b46-4f5c-817e-ab30e51eb499/startedat`

Can you find it and paste the contents?  Also, when testing with 2.5, test with uploading a different repository or the `_uploads` subdirectory.

**Comment by sunil3s3** [comment] 2016-08-12 10:35
[root@testserver- a8571529-7d84-4830-b7d4-dc55ab6ae488]# ls
data  hashstates  startedat
[root@testserver - a8571529-7d84-4830-b7d4-dc55ab6ae488]# cat startedat
2016-07-21T12:28:23Z

**Comment by sunil3s3** [comment] 2016-08-12 11:01
when tried with the registry:latest image, I see below error in docker logs
ime="2016-08-12T10:53:35Z" level=error msg="response completed with error" err.code=unknown err.detail="Get /v2/: unsupported protocol scheme \"\"" err.message="unknown error" go.version=go1.6.3 http.request.host="xxxxx..com:5000" http.request.id=502c00ad-8315-4c01-9053-931329a9bbbe http.request.method=HEAD http.request.remoteaddr=10.88.220.57 http.request.uri="/v2/oraclelinux/blobs/sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.1.12-32.2.3.el7uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.119816866s http.response.status=500 http.response.written=102 instance.id=4dac0028-cdbf-437f-ada5-cdf5356e0499 vars.digest="sha256:10ec637c060cc234336e0b7e33156e045372a32b501ba7d37ae7fea01a502b89" vars.name=oraclelinux version=v2.5.0

**Comment by RichardScothern** [comment] 2016-08-12 16:19
That is a totally unrelated error. Unsupported protocol scheme means that something other than `http` or `https` was used in the URL.

I think you'll need to do some debugging here.
 - Stop using v2.2.0 and use v2.5.0
 - Change the storage driver to filesystem
 - If you get `Get /v2/: unsupported protocol scheme`, then there is a problem with your docker engine communicating with the registry
 - Once you've overcome that, change the storage driver back to what you had before and retest.

**Comment by RichardScothern** [comment] 2016-09-01 20:47
@sunil3s3 any luck here?

**Comment by milosgajdos** [comment] 2023-12-19 15:07
Closing as both `oss` and ``swift` driver support has been deprecated.

**Closed by milosgajdos** 2023-12-19 15:07 UTC
