### ISSUE TITLE
Corrupt registry with Swift Storage 

### ISSUE THREAD

**Issue by Vad1mo** [distribution/distribution#2188] opened 2017-02-09 00:00 UTC
We have a few registries running on swift storage. 

Some of the images can't be pushed because of the error **unknown error completing upload: swift: Timeout expired while waiting for segments of**

```
c11090b4d522: Layer already exists 
0a6d02aaf2e3: Pushing [==================================================>] 74.66 MB
0a6d02aaf2e3: Pushing [===================================>               ] 52.33 MB/74.65 MB
da64abd44f85: Layer already exists 
11de431551d8: Layer already exists 
57dd1622cd6e: Layer already exists 
ac024582817f: Layer already exists 
67852b7d2cf5: Layer already exists 
f1f25d8c6e56: Layer already exists 
33a212e8aa56: Layer already exists 
eaaf72983326: Layer already exists 
a85f35566a26: Layer already exists 
```

The layer **0a6d02aaf2e3** fails to upload with the error message. 

Here is the full log with 
````
registry_1    | time="2017-02-08T22:02:11Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=dockerhub.acme.com http.request.id=8d99fa24-64e6-4f89-ab16-98c9c5bffa03 http.request.method=PATCH http.request.remoteaddr=80.72.104.111 http.request.uri="/v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=Gsxmp39D3eeQZlYd8XBbaLPCMhjJuVAPpnpKIrqyBpV7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE3LTAyLTA4VDIyOjAxOjM4LjM3MDc5Njk1OVoifQ%3D%3D" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" http.response.duration=8.407953144s http.response.status=202 http.response.written=0 instance.id=55615968-323e-432a-a720-bb36c0e127a7 version=v2.6.0 
registry_1    | 172.18.0.3 - - [08/Feb/2017:22:02:03 +0000] "PATCH /v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=Gsxmp39D3eeQZlYd8XBbaLPCMhjJuVAPpnpKIrqyBpV7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE3LTAyLTA4VDIyOjAxOjM4LjM3MDc5Njk1OVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))"
proxy_1       | 80.72.104.111 - - [08/Feb/2017:22:02:12 +0000] "PATCH /v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=Gsxmp39D3eeQZlYd8XBbaLPCMhjJuVAPpnpKIrqyBpV7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE3LTAyLTA4VDIyOjAxOjM4LjM3MDc5Njk1OVoifQ%3D%3D HTTP/1.1" 202 0 "-" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \x5C(darwin\x5C))"
registry_1    | time="2017-02-08T22:02:25Z" level=error msg="unknown error completing upload: swift: Timeout expired while waiting for segments of /docker/registry/v2/blobs/sha256/f2/f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9/data to show up" auth.user.name=dev go.version=go1.7.3 http.request.host=dockerhub.acme.com http.request.id=798cb2f9-343d-4b2e-9eaf-98f949a4b187 http.request.method=PUT http.request.remoteaddr=80.72.104.111 http.request.uri="/v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=8xrLlv2lBSMuE5SJDiRwq9fHyqJHFOqpwPrxV9Rc17R7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0Ijo2Njc3NTU5NiwiU3RhcnRlZEF0IjoiMjAxNy0wMi0wOFQyMjowMTozOFoifQ%3D%3D&digest=sha256%3Af2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" instance.id=55615968-323e-432a-a720-bb36c0e127a7 vars.name="acme/papyrus" vars.uuid=394d7fd6-5205-4fac-a45f-2561a4f31655 version=v2.6.0 
registry_1    | time="2017-02-08T22:02:25Z" level=error msg="error canceling upload after error: already closed" auth.user.name=dev go.version=go1.7.3 http.request.host=dockerhub.acme.com http.request.id=798cb2f9-343d-4b2e-9eaf-98f949a4b187 http.request.method=PUT http.request.remoteaddr=80.72.104.111 http.request.uri="/v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=8xrLlv2lBSMuE5SJDiRwq9fHyqJHFOqpwPrxV9Rc17R7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0Ijo2Njc3NTU5NiwiU3RhcnRlZEF0IjoiMjAxNy0wMi0wOFQyMjowMTozOFoifQ%3D%3D&digest=sha256%3Af2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" instance.id=55615968-323e-432a-a720-bb36c0e127a7 vars.name="acme/papyrus" vars.uuid=394d7fd6-5205-4fac-a45f-2561a4f31655 version=v2.6.0 
registry_1    | time="2017-02-08T22:02:26Z" level=error msg="response completed with error" auth.user.name=dev err.code=unknown err.detail="swift: Timeout expired while waiting for segments of /docker/registry/v2/blobs/sha256/f2/f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9/data to show up" err.message="unknown error" go.version=go1.7.3 http.request.host=dockerhub.acme.com http.request.id=798cb2f9-343d-4b2e-9eaf-98f949a4b187 http.request.method=PUT http.request.remoteaddr=80.72.104.111 http.request.uri="/v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=8xrLlv2lBSMuE5SJDiRwq9fHyqJHFOqpwPrxV9Rc17R7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0Ijo2Njc3NTU5NiwiU3RhcnRlZEF0IjoiMjAxNy0wMi0wOFQyMjowMTozOFoifQ%3D%3D&digest=sha256%3Af2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.641375316s http.response.status=500 http.response.written=104 instance.id=55615968-323e-432a-a720-bb36c0e127a7 vars.name="acme/papyrus" vars.uuid=394d7fd6-5205-4fac-a45f-2561a4f31655 version=v2.6.0 
registry_1    | 172.18.0.3 - - [08/Feb/2017:22:02:12 +0000] "PUT /v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=8xrLlv2lBSMuE5SJDiRwq9fHyqJHFOqpwPrxV9Rc17R7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0Ijo2Njc3NTU5NiwiU3RhcnRlZEF0IjoiMjAxNy0wMi0wOFQyMjowMTozOFoifQ%3D%3D&digest=sha256%3Af2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9 HTTP/1.1" 500 104 "" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))"
proxy_1       | 80.72.104.111 - - [08/Feb/2017:22:02:26 +0000] "PUT /v2/acme/papyrus/blobs/uploads/394d7fd6-5205-4fac-a45f-2561a4f31655?_state=8xrLlv2lBSMuE5SJDiRwq9fHyqJHFOqpwPrxV9Rc17R7Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiMzk0ZDdmZDYtNTIwNS00ZmFjLWE0NWYtMjU2MWE0ZjMxNjU1IiwiT2Zmc2V0Ijo2Njc3NTU5NiwiU3RhcnRlZEF0IjoiMjAxNy0wMi0wOFQyMjowMTozOFoifQ%3D%3D&digest=sha256%3Af2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9 HTTP/1.1" 500 104 "-" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \x5C(darwin\x5C))"
registry_1    | time="2017-02-08T22:02:31Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=dockerhub.acme.com http.request.id=5a42e5ed-99f2-4fee-be4e-57a5f002aafa http.request.method=POST http.request.remoteaddr=80.72.104.111 http.request.uri="/v2/acme/papyrus/blobs/uploads/" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" http.response.duration=457.531335ms http.response.status=202 http.response.written=0 instance.id=55615968-323e-432a-a720-bb36c0e127a7 version=v2.6.0 
proxy_1       | 80.72.104.111 - - [08/Feb/2017:22:02:31 +0000] "POST /v2/acme/papyrus/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \x5C(darwin\x5C))"
registry_1    | 172.18.0.3 - - [08/Feb/2017:22:02:31 +0000] "POST /v2/acme/papyrus/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))"
proxy_1       | 2017/02/08 22:02:32 [warn] 27#27: *18743 a client request body is buffered to a temporary file /usr/local/openresty/nginx/client_body_temp/0000000154, client: 80.72.104.111, server: dockerhub.acme.com, request: "PATCH /v2/acme/papyrus/blobs/uploads/42564a13-49cd-4c9a-ae85-33f753e7de01?_state=d8xl8oIwSAjI-kXDlrSHQYtH7m37gncrcIGuBAPg0E97Ik5hbWUiOiJmaW5vL3BhcHlydXMiLCJVVUlEIjoiNDI1NjRhMTMtNDljZC00YzlhLWFlODUtMzNmNzUzZTdkZTAxIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE3LTAyLTA4VDIyOjAyOjMxLjM1MDI1NjM3OFoifQ%3D%3D HTTP/1.1", host: "dockerhub.acme.com"

`````

Investigating the failed blob 
```
rootÉ2d6ca6783ab2:ü# swift stat --lh images  files/docker/registry/v2/blobs/sha256/f2/f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9/data
       Account: AUTH_b50accfce5044d6e9e47f80d012ca4e7
     Container: images
        Object: files/docker/registry/v2/blobs/sha256/f2/f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9/data
  Content Type: application/octet-stream
Content Length: 0
 Last Modified: Thu, 26 Jan 2017 10:36:46 GMT
          ETag: "d41d8cd98f00b204e9800998ecf8427e"
      Manifest: images/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f66696e6f2f706170797275732f5f75706c6f6164732f33363465623039332d663864642d346136352d613839302d6535633462396164333230632f646174616acec982c140da3457079e3682729fa43f5d2e8d81bd27ac4962d6f39f9f00f9da39a3ee5e6b4b0d3255bfef95601890afd80709
 Accept-Ranges: bytes
   X-Timestamp: 1485427005.63842
    X-Trans-Id: txc80646d37cbf4c31a8dba-00589baabc
```

After that I tried to download the Manifest: `images/segments/2f6/46f63...`

`swift stat --lh images segments/2f6/46f636b6.... Object images/segments/2f6/46f636b657... not found
`

- Should there be always a manifest?
- Can I recreate the manifest or push it? 
- How can I find out where the layer f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9 belongs to, because then I could delete the whole image. 

- How can I possibly fix the registry?

**Comment by sudhanshu-garg** [comment] 2017-04-24 22:54
This issue has been open for 2+ months and there aren't any comments on it.
@Vad1mo Do you still see this issue consistently? Does Docker CLI retry the failed layer uploads and  finally the image get pushed?

**Comment by manvalls** [comment] 2017-04-29 09:44
I'm seeing the exact same issue, a certain layer fails every time I try to push it with the same error.

**Comment by sudhanshu-garg** [comment] 2017-05-01 01:45
Do you have steps to reproduce the issue?

**Comment by manvalls** [comment] 2017-05-01 08:46
I'm sorry, yesterday I developed a quick script to migrate the registry to a new swift container, and that fixed it, so I'm unable to reproduce the issue.

**Comment by Vad1mo** [comment] 2017-05-01 10:59
Also from my side, I changed my setup because of the error.

**Comment by Tronix117** [comment] 2017-08-24 07:57
Why did you close it ? Even if you solved the problem using another mean, the issue is still here.
I am using Swift and exactly same issue with segment keep retrying....

**Comment by Vad1mo** [comment] 2017-08-24 08:03
after some, when we thought that the config change did the trick, we still see this issue popping up once in a while. So opening up the issue again. @Tronix117 what Swift provider are you using? Maybe we can narrow it down to a provider or so, if we can't pinpoint it otherwise.

**Comment by Tronix117** [comment] 2017-08-24 08:09
I am using the Public Cloud Storage of OVH with Swift authentification v2.
If I manually remove all the the layer files on the bucket, the layer finally goes through.

The issue is extremely recurring our side, we are also using Docker Swarm, with an auto configured HAProxy in front with SSL terminaison. However, if I change the storage drive to filesystem, no problems occured.

@Vad1mo Do you remember what config change you made to "kinda" solve the issue ?

**Comment by Vad1mo** [comment] 2017-08-24 09:19
hmm, interesting we too use OVH. Looking on other OVH related issues here I found #1539. (analyzing) and latest updates on #1013

What we changed was the reverse proxy in front of the registry, it cached the requests before now it doesn't. We had the feeling that the error was solved with that. as we saw no such issues for some time. But they still appear to pop up from time to time.

**Comment by manvalls** [comment] 2017-08-25 13:53
I found that running again docker build with `--no-cache` oddly enough fixed the issue in most cases. And yes, Iḿ also using OVH.

**Comment by Vad1mo** [comment] 2017-08-25 14:05
@manvalls it "fixes" the issue because you are creating all the layers again from scratch. This is more of a hack then a solution. The question is why cant that layer be pushed?

**Comment by docwhat** [comment] 2017-08-28 19:40
How can something with a SHA256 checksum identity ever be _broken_?  It could be _missing_, but it should never be _broken_.

**Comment by Vad1mo** [comment] 2017-08-31 23:11
https://github.com/docker/distribution/pull/1229 here is pending pull request the might work

**Comment by xuejipeng** [comment] 2018-12-20 07:20
I have the same problem and i found out that this segments was deleted, It head the 002 file  and deleted the 001 file without finding it， is there any way to avoid this problem now? Or what's the real reason for it? my registry version is 2.6.2
[swift.log](https://github.com/docker/distribution/files/2697770/swift.log)

**Comment by Vad1mo** [comment] 2018-12-20 09:50
The only recommendation I can give you, don't use swift. The implementation is broken. Alt you can try  https://github.com/docker/distribution/pull/2441 this should work

**Comment by xuejipeng** [comment] 2018-12-20 14:20
#1013 say the reason for this problem is eventually consistent and @ncw's advice is "create single objects rather than DLOs " 
I saw a config at [https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/swift.md](url), if i set the chunksize to 1G or more, is it going to solve this problem?

**Comment by zhxqgithub** [comment] 2019-05-09 08:52
I have the same issue with swift storage,however,It can be fixed by two ways:
1. delete all the wrong layers ,we use the failed layers above for example:
```
0a6d02aaf2e3: Pushing [==================================================>] 74.66 MB
0a6d02aaf2e3: Pushing [===================================>               ] 52.33 MB/74.65 MB
```
First ,  get the digest from diffid 0a6d02aaf2e3 in ${docker root dir }/images/xxx/distribution/v2metadata-by-diffid/sha256/0a/0a6d02aaf2e3xxxxxxxxx

Second,use the swift command to delete the corrupt object
```
swift delete ${container_name} path_of_object
swfit delete images files/docker/registry/v2/blobs/sha256/f2/f2327c65e7abe07a0f63af4c87750e1e7d99eac14344588b8df03ff716fd5ea9/data
```
Third, repush the image . if get an http 500 error at last ,you shoud also delete the image id object data
```
   docker inspect image to get imageid at top "Id":"sha256:xxxxxxx"
  swift delete images files/docker/registry/v2/blobs/sha256/xx/xxxxxx.
```
and repush image again

2. Also ,you can modify Stat function in swift.go. like below,
```
if isDLO && info.Bytes == 0 {
			if time.Now().Add(waitingTime).After(endTime) {
				fmt.Printf("Timeout expired while waiting for segments of %s to show up,Just delete it and upload it again\n", path)
				err = d.Delete(ctx, path)
				if err == nil {
					fmt.Printf("delete %s done!!!!\n", path)
					return nil, storagedriver.PathNotFoundError{Path: path}
				}
				fmt.Printf("delete %s error,the err is %s\n", path, err)
				return nil, fmt.Errorf("Timeout expired while waiting for segments of %s to show up", path)
			}
			time.Sleep(waitingTime)
			waitingTime *= 2
			continue
		}
```
The two ways works for me,  Hope it will be helpful to you.

**Comment by shcherbak** [comment] 2021-12-23 13:46
Confusing that  ```segments of /docker/registry/v2/``` has no prefix ```files/docker/registry/v2/``` `files`

**Comment by shcherbak** [comment] 2022-02-16 22:48
the same error on v.2.8.0

**Comment by shcherbak** [comment] 2022-05-12 20:58
We are still suffering of this problem. If you need any details, please refer, i will provide information you need to fix this.
We have intensively used registry setup with swift backend and unable to clean it properly

**Comment by shcherbak** [comment] 2022-06-16 09:47
we are still suffering of this bug

**Comment by shcherbak** [comment] 2022-06-28 23:20
We have large and intensively used registry, for example there is repositories with more then 500 tags. We investigated that garbage collect hangs when need to remove many (apx more then 1000 blobs). When we did garbage collecting with custom script, native garbage collect starts working fine

**Comment by milosgajdos** [comment] 2024-04-21 08:50
Closing as Swift driver has been deprecated in the latest release and is no longer supported.

**Closed by milosgajdos** 2024-04-21 08:50 UTC
