### ISSUE TITLE
Regisrty s3 storage cannot support huawei cloud object storage service

### ISSUE THREAD

**Issue by yuan1238y** [distribution/distribution#3039] opened 2019-10-30 13:27 UTC
I use s3 storage run registry, i can `push` and `pull` image from my registry, but can not list images from my registry.

Command `curl http://192.169.0.99:5000/v2/_catalog` get response:
`curl: (52) Empty reply from server`

Command `kubectl logs registry` get result:
```
time="2019-10-30T13:21:32.194493687Z" level=panic msg="runtime error: invalid memory address or nil pointer dereference" 
2019/10/30 13:21:32 http: panic serving ***:50092: &{0xc00015e050 map[] 2019-10-30 13:21:32.194493687 +0000 UTC m=+1376.280704215 panic runtime error: invalid memory address or nil pointer dereference <nil>}
goroutine 926 [running]:
net/http.(*conn).serve.func1(0xc00014fae0)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xe8e920, 0xc00023a820)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/docker/distribution/vendor/github.com/sirupsen/logrus.Entry.log(0xc00015e050, 0xc0005985a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/distribution/vendor/github.com/sirupsen/logrus/entry.go:124 +0x574
github.com/docker/distribution/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc00023a7d0, 0xc002e7e948, 0x1, 0x1)
	/go/src/github.com/docker/distribution/vendor/github.com/sirupsen/logrus/entry.go:169 +0xb2
github.com/docker/distribution/vendor/github.com/sirupsen/logrus.(*Logger).Panic(0xc00015e050, 0xc002e7e948, 0x1, 0x1)
	/go/src/github.com/docker/distribution/vendor/github.com/sirupsen/logrus/logger.go:236 +0x6d
github.com/docker/distribution/vendor/github.com/sirupsen/logrus.Panic(0xc002e7e948, 0x1, 0x1)
	/go/src/github.com/docker/distribution/vendor/github.com/sirupsen/logrus/exported.go:107 +0x4b
github.com/docker/distribution/registry.panicHandler.func1.1()
	/go/src/github.com/docker/distribution/registry/registry.go:345 +0xf9
panic(0xd81c00, 0x170a620)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc000129480, 0xc0003c4c01, 0xc0004c6200)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00011e560, 0x7f9ae95f08f0, 0xc00025b570, 0xc00015f090, 0xc002e7ef38, 0x0, 0x0, 0x0, 0x1, 0x2)
	/go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0003b0d00, 0xff1ae0, 0xc00025b500, 0xc002e7eff8, 0xc00000ed21, 0x20, 0xea6655, 0x1, 0xc00015f040, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc0003b0d00, 0xff1ae0, 0xc00025b500, 0xc0003ce600, 0x20, 0xc00015f040, 0x2, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc00031da90, 0xff1ae0, 0xc00025b500, 0xc0003ce600, 0x20, 0xc00015f040, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.(*registry).Repositories(0xc0000fe150, 0xff1c60, 0xc0005e4d20, 0xc00007fc00, 0x64, 0x64, 0x0, 0x0, 0x10015c0, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/storage/catalog.go:30 +0x1fb
github.com/docker/distribution/registry/handlers.(*catalogHandler).GetCatalog(0xc00011e260, 0xfef7a0, 0xc0003c4300, 0xc000171c00)
	/go/src/github.com/docker/distribution/registry/handlers/catalog.go:48 +0x12a
github.com/docker/distribution/registry/handlers.(*catalogHandler).GetCatalog-fm(0xfef7a0, 0xc0003c4300, 0xc000171c00)
	/go/src/github.com/docker/distribution/registry/handlers/catalog.go:24 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0004c6160, 0xfef7a0, 0xc0003c4300, 0xc000171c00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/docker/distribution/vendor/github.com/gorilla/handlers.MethodHandler.ServeHTTP(0xc00089bc80, 0xfef7a0, 0xc0003c4300, 0xc000171c00)
	/go/src/github.com/docker/distribution/vendor/github.com/gorilla/handlers/handlers.go:35 +0x342
github.com/docker/distribution/registry/handlers.(*App).dispatcher.func1(0xfef7a0, 0xc0003c4300, 0xc000171600)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:726 +0x51f
net/http.HandlerFunc.ServeHTTP(0xc0003d4340, 0xfef7a0, 0xc0003c4300, 0xc000171600)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/docker/distribution/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000095360, 0xfef7a0, 0xc0003c4300, 0xc000171600)
	/go/src/github.com/docker/distribution/vendor/github.com/gorilla/mux/mux.go:114 +0xe0
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc0002c3a40, 0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:640 +0x297
github.com/docker/distribution/registry.alive.func1(0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/go/src/github.com/docker/distribution/registry/registry.go:365 +0x6a
net/http.HandlerFunc.ServeHTTP(0xc00002fd70, 0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/docker/distribution/health.Handler.func1(0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/go/src/github.com/docker/distribution/health/health.go:271 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc00000a360, 0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/docker/distribution/registry.panicHandler.func1(0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/go/src/github.com/docker/distribution/registry/registry.go:348 +0x81
net/http.HandlerFunc.ServeHTTP(0xc00000a3a0, 0x7f9ae97ba3d0, 0xc00089ae10, 0xc000170e00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/docker/distribution/vendor/github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xfe85c0, 0xc00000c018, 0xfe9d00, 0xc00000a3a0, 0xff0b60, 0xc00049e1c0, 0xc000170e00)
	/go/src/github.com/docker/distribution/vendor/github.com/gorilla/handlers/handlers.go:75 +0x22f
net/http.serverHandler.ServeHTTP(0xc000084680, 0xff0b60, 0xc00049e1c0, 0xc000170e00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00014fae0, 0xff1760, 0xc0003c4200)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

`docker version:`
```
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        aeac9490dc
 Built:             Wed Jul 17 18:15:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       aeac9490dc
  Built:            Wed Jul 17 18:14:16 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

`docker info:`
```
Client:
 Debug Mode: false

Server:
 Containers: 40
  Running: 38
  Paused: 0
  Stopped: 2
 Images: 21
 Server Version: 19.03.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.1.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.7GiB
 Name: hub0001
 ID: TO6A:ZKEO:KOQW:ZLOZ:HFK4:7HNX:NXL3:CSJT:WYIZ:5I3F:XOLV:6Z6S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

`docker exec <registry-container> registry --version:`
`registry github.com/docker/distribution v2.7.1`

`helm config:`
```
image:
  tag: 2.7.1
ingress:
  enabled: true
  hosts:
  - ***
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    nginx.ingress.kubernetes.io/enable-cors: "true"
  tls:
  - secretName: ***
    hosts:
      - ***
storage: s3
secrets:
  s3: 
    accessKey: ***
    secretKey: ***
s3:
  region: cn-east-2
  regionEndpoint: obs.cn-east-2.myhuaweicloud.com
  bucket: ***
  secure: true
  encrypt: false
```

**Comment by jansmets** [comment] 2019-11-25 11:30
probably duplicate of https://github.com/docker/distribution/issues/2695
(which has been fixed, but everyone is waiting for a new release ...)

**Comment by DavidSpek** [comment] 2023-08-16 23:33
Closing this as the fix has now most likely been released.

**Closed by DavidSpek** 2023-08-16 23:33 UTC
