### ISSUE TITLE
MediaType validation too aggressive

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#2259] opened 2017-04-27 23:17 UTC
The mediaType validation for the manifest getter is too aggressive: https://github.com/docker/distribution/blob/master/registry/storage/manifeststore.go#L98.

This prevents the fetching of content by digest which would fail validation on the client. This validation will make it hard to upgrade in the future.

cc @caervs

**Comment by jonjohnsonjr** [comment] 2017-04-28 01:09
Could you expand on this a little bit? Is this related to #2076?

**Comment by stevvooe** [comment] 2017-04-28 20:22
@jonjohnsonjr The registry should be fairly agnostic about the format it is returning. Also, the current code relies on the existence of an embedded `mediaType` field, which is problematic, as the types are supposed to be external.

In general, the current approach will make #2076 harder.

**Comment by milosgajdos** [comment] 2023-05-19 17:20
@stevvooe do you wanna close this issue?

**Comment by DavidSpek** [comment] 2023-08-09 22:50
@milosgajdos Can this be closed given that https://github.com/distribution/distribution/pull/2076 was merged?

**Comment by DavidSpek** [comment] 2023-08-29 10:55
Lets close it. If the issue is still relevant it can be re-opened or a new issue can be created.

**Closed by DavidSpek** 2023-08-29 10:55 UTC
Labels: bug, priority/P2
