### ISSUE TITLE
Private registry push fail with EOF

### ISSUE THREAD

**Issue by dreh23** [distribution/distribution#2071] opened 2016-11-17 09:52 UTC
Problem: Push failes. Registry crashes. I have a self build registry image (based on xenial). Data is stored via s3 backend on premise using minio. This worked flawless before. Any hints?

Logfile of registry:
```
192.168.1.34 - - [17/Nov/2016:09:33:49 +0000] "POST /v2/XXX/baseimage/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.0-47-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \\(linux\\))"
time="2016-11-17T09:34:09Z" level=info msg="response completed" go.version=go1.7.1 http.request.host=cell-registry-01.XXX.inc http.request.id=0081c982-07af-491c-9cd8-db9aafdfd13a http.request.method=PATCH http.request.remoteaddr="192.168.1.34:41460" http.request.uri="/v2/XXX/baseimage/blobs/uploads/081aabe9-18dc-45a9-8797-876e83516b4a?_state=VJNnSNlg-GW-yAxOz1m6nFZLpff2yPXLJz3qYoHRO2B7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6IjA4MWFhYmU5LTE4ZGMtNDVhOS04Nzk3LTg3NmU4MzUxNmI0YSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0xMS0xN1QwOTozMzo0OS4zNzYzNjE1MVoifQ%3D%3D" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.0-47-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \\(linux\\))" http.response.duration=19.630469172s http.response.status=202 http.response.written=0 instance.id=aaf49e0b-d788-49c8-9104-4d30f5f8fe40 version=v2.6.0-rc.1-4-g7694c31 
192.168.1.34 - - [17/Nov/2016:09:33:49 +0000] "PATCH /v2/celluloidvfx/baseimage/blobs/uploads/081aabe9-18dc-45a9-8797-876e83516b4a?_state=VJNnSNlg-GW-yAxOz1m6nFZLpff2yPXLJz3qYoHRO2B7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6IjA4MWFhYmU5LTE4ZGMtNDVhOS04Nzk3LTg3NmU4MzUxNmI0YSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0xMS0xN1QwOTozMzo0OS4zNzYzNjE1MVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.0-47-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \\(linux\\))"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x497a22]

goroutine 93 [running]:
panic(0xaa32c0, 0xc420014080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy.func1(0xc420310fc0, 0x0, 0xc42026fb00, 0xed4160, 0xc420630380, 0xc420345f10, 0x6a, 0xc42032b340, 0x69, 0xc4203d9900, ...)
        /tmp/go1.7.1/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:742 +0x592
created by github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy
        /tmp/go1.7.1/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:748 +0x6aa
time="2016-11-17T09:34:09Z" level=info msg="redis not configured" go.version=go1.7.1 instance.id=12711d19-4fa8-4022-8218-45cf3bccafef version=v2.6.0-rc.1-4-g7694c31 
time="2016-11-17T09:34:09Z" level=info msg="Starting upload purge in 9m0s" go.version=go1.7.1 instance.id=12711d19-4fa8-4022-8218-45cf3bccafef version=v2.6.0-rc.1-4-g7694c31 
time="2016-11-17T09:34:09Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.1 instance.id=12711d19-4fa8-4022-8218-45cf3bccafef version=v2.6.0-rc.1-4-g7694c31 
time="2016-11-17T09:34:09Z" level=info msg="listening on [::]:8080, tls" go.version=go1.7.1 instance.id=12711d19-4fa8-4022-8218-45cf3bccafef version=v2.6.0-rc.1-4-g7694c31 
~
```

Registry build:
```
giturl: github.com/docker/distribution
gitrev: 7694c31658cfc0f9db97cd7ffaef9008b620a4d2
goversion: 1.7.1
```

Workstation docker version:

`Docker version 1.12.3, build 6b644ec
`

Workstation docker info:

```
Containers: 59
 Running: 1
 Paused: 0
 Stopped: 58
Images: 41
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /silo/docker/aufs
 Backing Filesystem: zfs
 Dirs: 234
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65 GiB
Name: cell-ls-24
ID: YV4B:ZM4J:TGKS:D2PK:S2CF:ZU3F:MOL4:DOJJ:7MJ4:UZJN:A6DM:PCXY
Docker Root Dir: /silo/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

Registry config:
```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        accesskey: XYZ
        secretkey: XYZ
        region: us-east-1
        regionendpoint: https://cell-vms-01.XXX.inc:9500
        bucket: repo
        #keyid: mykeyid
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
http:
    secret: MOOO
    addr: :8080
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        certificate: /etc/XXX.inc/ssl/cell-registry-01.XXX.inc.crt
        key: /etc/XXX.inc/ssl/cell-registry-01.XXX.inc.key
        clientcas:
        - /etc/XXX.inc/ssl/ca.pem

```

**Comment by dreh23** [comment] 2016-11-17 10:07
I could narrow it down. Not all push images fail. Could be related to #1967.

**Comment by aaronlehmann** [comment] 2016-11-17 21:38
I suspect that `uploadResp.CopyPartResult` is nil here. Perhaps a check is needed for this. I'm not familiar enough with the S3 SDK to know offhand whether this is expected behavior and what it means.

**Comment by dreh23** [comment] 2016-11-18 08:03
I redid everything to have a clean testbed. There is a pattern: Small layers are pushed. Big layers fail.

```
docker tag e4415b714b62 cell-registry-01.XXX.inc/xxx/ubuntu:xenial
[johannesa ~]
cell-ls-24 docker push cell-registry-01.XXX.inc/xxx/ubuntu:xenial
The push refers to a repository [cell-registry-01.XXX.inc/xxx/ubuntu]
c1bd37d01c89: Pushed 
943edb549a83: Pushed 
bf6751561805: Pushed 
f934e33a54a6: Pushed 
e7ebc6e16708: Pushing [==================================================>] 133.8 MB
received unexpected HTTP status: 500 Internal Server Error
```
corresponding logs:


`time="2016-11-18T07:59:44Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 22UWEG1PAMLJJA7N" err.message="unknown error" go.version=go1.7.1 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=bb4d69fb-5768-4bc4-a848-23dc2709c9c5 http.request.method=PUT http.request.remoteaddr="192.168.1.34:47452" http.request.uri="/v2/xxx/ubuntu/blobs/uploads/9a692767-197d-4dd5-8063-069601a669b2?_state=ILlg2Ttgrh4LCtQ0qWtuJYRXFrxEawnQ1b_WWdioTRp7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvdWJ1bnR1IiwiVVVJRCI6IjlhNjkyNzY3LTE5N2QtNGRkNS04MDYzLTA2OTYwMWE2NjliMiIsIk9mZnNldCI6NTAwNjY5MzQsIlN0YXJ0ZWRBdCI6IjIwMTYtMTEtMThUMDc6NTk6MzBaIn0%3D&digest=sha256%3Aaed15891ba52590c33d862bb6a91ea016b7dc43a9080e48509f75f003d82952c" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.0-47-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=57.634489ms http.response.status=500 http.response.written=117 instance.id=46ccac33-cb67-45c3-8afc-2bc4a301122d vars.name="celluloidvfx/ubuntu" vars.uuid=9a692767-197d-4dd5-8063-069601a669b2 version=v2.6.0-rc.1-4-g7694c31`

**Comment by stevvooe** [comment] 2016-12-15 23:51
@dreh23 I suspect there is a bug in minio's implementation of the s3 protocol. @aaronlehmann's assessment of the panic in the first issue is accurate. I am not sure about this 500 error. Looks like there may have been a change on their end to address the nil part, but now have a missing object.

Would it be possible to reach out to minio for their assistance?

**Comment by matthanley** [comment] 2017-06-13 16:52
Looks like this is related to (and fixed with) https://github.com/minio/minio/issues/3662

**Comment by stevvooe** [comment] 2017-06-13 18:17
We probably need to push a fix upstream to the s3 driver.

**Comment by rgruyters** [comment] 2018-02-21 14:16
Is there an update on this issue? I have this issue as well. What version does work if this is not fixed with latest `registry:2` and `minio:latest`. (for the record also tested with `minio:edge`)

```
$ docker push hub.local/squid:3.6
The push refers to a repository [hub.local/squid]
cca2345b5201: Pushing [==================================================>] 4.096 kB
60e79ae7480e: Pushing [==================================================>] 4.608 kB
34aecab523e0: Pushing [=========================>                         ] 4.598 MB/9.127 MB
cd7100a72410: Pushing [==================================================>] 4.403 MB
error parsing HTTP 403 response body: unexpected end of JSON input: ""
```

**Comment by milosgajdos** [comment] 2024-07-17 20:29
Closing as outdated. We actually use `minio` in our S3 driver integration test suite, so I believe this should work now. Feel free to reopen

**Closed by milosgajdos** 2024-07-17 20:29 UTC
