### ISSUE TITLE
Blobs API sometimes quick， sometimes slow

### ISSUE THREAD

**Issue by HackToday** [distribution/distribution#2456] opened 2017-12-01 09:11 UTC
I hit one strange issue,  before I talked about it in details, let me summary my env:

1. docker registry version  v2.6.1 , and it is running in container
2. docker  registry config

storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: redis

3. the storage /var/lib/registry  is glusterfs mounted in local machine as local filesystem

When access the following API:

`/v2/<name>/blobs/<digest>`

sometimes, it can be quick in 0.165s, however, sometimes, it can spend time about 5s (quite slow), I use curl to test the above API

The strace show that:

```
)            = 2
17:06:52 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:52 poll([{fd=3, events=POLLIN}], 1, 1000^[[A) = 0 (Timeout)
17:06:53 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:53 poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout)
17:06:54 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:54 poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout)
17:06:55 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:55 poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout)
17:06:56 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:56 poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout)
17:06:57 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
17:06:57 poll([{fd=3, events=POLLIN}], 1, 1000) = 1 ([{fd=3, revents=POLLIN}])
17:06:57 poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=3, revents=POLLIN|POLLRDNORM}])
17:06:57 recvfrom(3, "HTTP/1.1 200 OK\r\nAccept-Ranges: "..., 16384, 0, NULL, NULL) = 4096
17:06:57 write(2, "<", 1<)               = 1
17:06:57 write(2, " ", 1 )               = 1
17:06:57 write(2, "HTTP/1.1 200 OK\r\n", 17HTTP/1.1 200 OK
) = 17
17:06:57 write(2, "<", 1<)               = 1
17:06:57 write(2, " ", 1 )               = 1
17:06:57 write(2, "Accept-Ranges: bytes\r\n", 22Accept-Ranges: bytes
) = 22
17:06:57 write(2, "<", 1<)               = 1
17:06:57 write(2, " ", 1 )               = 1
17:06:57 write(2, "Cache-Control: max-age=31536000\r"..., 33Cache-Control: max-age=31536000
```

It appears the code hit issue in distribution is in (registry/storage/blobserver.go)

```
 71     if w.Header().Get("Content-Length") == "" {
 72         // Set the content length if not already set.
 73         w.Header().Set("Content-Length", fmt.Sprint(desc.Size))
 74     }
 75       
 **76     http.ServeContent(w, r, desc.Digest.String(), time.Time{}, br)**
 77     return nil             
 78 } 

```

But I did not know why it is slow here, I checked glusterfs local read blobs data(with while loop to cat the data file), it is quick, and never such slow.  So the issue is not in glusterfs itself, It seems the issue was in registry itself.

@stevvooe   Could you guys help to check what;s the performance issue here ?

**Comment by HackToday** [comment] 2017-12-05 00:38
@stevvooe  @dmcgowan   any ideas for this issue ?

**Comment by stevvooe** [comment] 2018-01-17 00:18
@HackToday Without knowing more about the setup, the problem is likely gluster's response time variability on `Stat` operations. `ServeContent` employs this heavily and this is the area where performance issues can accumulate.

I'd recommend running the registry with debug mode to see the response times for each storage driver operation to verify.

**Comment by dmp42** [comment] 2018-05-26 01:54
@HackToday were you able to learn more about this?

**Comment by milosgajdos** [comment] 2023-08-26 08:33
Closing due to its age and no longer supported registry version. Please test on the latest release and reopen.

**Closed by milosgajdos** 2023-08-26 08:33 UTC
Labels: question
