### ISSUE TITLE
In which branch can I find the Docker Registry 2.7.1 source provided by Docker Hub?

### ISSUE THREAD

**Issue by sunminjeon** [distribution/distribution#3524] opened 2021-11-04 06:44 UTC
If I want to check the source of the docker registry 2.7.1 version provided by docker hub, in which branch can I check it?
(https://hub.docker.com/_/registry?tab=tags)

The contents of the docker registry 2.7.1 image provided by docker hub and source of 'release/2.7' branch seem to be different.

1.docker registry 'release/2.7' branch

> / # registry -v
 registry github.com/docker/distribution v2.7.1-34-g691e62e7.m

2.docker registry 2.7.1 provided by docker hub

> / # registry -v
registry github.com/docker/distribution v2.7.1

Check, Please.

**Comment by brackendawson** [comment] 2021-11-04 10:15
A branch is not what you are looking for, the [`v2.7.1`](https://github.com/distribution/distribution/releases/tag/v2.7.1) tag is.

2.7.1 was released before Docker donated the distribution project to the CNCF, so the repo was called github.com/docker/distribution back then, but the code is the `v2.7.1` tag on the `release/2.7` branch in this repository. The `release/2.7` branch has since had changes merged which may eventually go into a v2.7.2 release.

**Comment by sunminjeon** [comment] 2021-11-05 02:32
@brackendawson  

Thanks for your confirmation.

But in [docker hub](https://hub.docker.com/_/registry?tab=tags), the last update date of version 2.7.1 is 2 months ago.
[v2.7.1](https://github.com/distribution/distribution/releases/tag/v2.7.1) was released 18 Jan 2019.

The last update time is different, is it the same source?

And are these two things the same?

**Comment by brackendawson** [comment] 2021-11-05 10:34
It certainly should be the same source as the `v2.7.1` tag, the repo that builds the image is actually here https://github.com/docker/distribution-library-image and Docker still own that and the library images on hub. It appears to contain a checked in binary.

As Go builds are reproducible and the 2.7.1 tag has a vendor directory you should be able to confirm that the source is unchanged yourself. Perhaps @dmcgowan knows why the image was built again more recently?

**Comment by milosgajdos** [comment] 2021-11-05 10:41
I would also encourage you to avoid `2.7.1.` as much as possible. It's not being actively maintained so to speak. It's received a few security patches, but the general plan is to focus on the `main` branch development, etc.. So, beware of that @sunminjeon

**Comment by bluefriday** [comment] 2021-11-08 02:06
@milosgajdos 
May I know if there are any plans to release version 2.7.2?

**Comment by milosgajdos** [comment] 2021-11-08 08:17
There was, yeah, but it stalled over the summer. We need to revive it. But as I said, when it happens it will only contain security patches, etc.

**Comment by milosgajdos** [comment] 2023-08-14 16:10
Given the latest release is `v2.8.2` I believe we should close this issue.

**Comment by DavidSpek** [comment] 2023-08-16 23:15
Agreed.

**Closed by DavidSpek** 2023-08-16 23:15 UTC
