### ISSUE TITLE
docker push keeps retrying and failing to local registry

### ISSUE THREAD

**Issue by mzhaom** [distribution/distribution#2042] opened 2016-11-07 21:22 UTC
```
$ docker run -d -p 5000:5000 --name registry registry:2
$ docker push --disable-content-trust=false localhost:5000/ubuntu
The push refers to a repository [localhost:5000/ubuntu]
2f1da5476ba7: Pushing [==================================================>] 136.4 MB
could not verify layer data for: sha256:2f1da5476ba736f1c02df28b51515b4a996a55d6d8378a480ef7486a0d568ae2. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue
```

I saw the 500 error in the docker registry log

```
time="2016-11-07T17:33:11Z" level=error msg="response completed with error" err.code=unknown err.detail="unexpected EOF" err.message="unknown error" go.version=go1.6.3 http.request.host="localhost:5000" http.request.id=aba55e29-f48f-4a22-b833-a42c66911f4f http.request.method=PATCH http.request.remoteaddr="192.168.168.1:35133" http.request.uri="/v2/ubuntu/blobs/uploads/062ec770-029f-417e-9f3c-1fb3150bf938?_state=kq_Zaj2MK2tHEQWBRfNagoqe1mLARvBBrajE-qyX2T97Ik5hbWUiOiJ1YnVudHUiLCJVVUlEIjoiMDYyZWM3NzAtMDI5Zi00MTdlLTlmM2MtMWZiMzE1MGJmOTM4IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTExLTA3VDE3OjMyOjQ2LjYzMDA5ODkyM1oifQ%3D%3D" http.request.useragent="docker/1.12.2 go/go1.6.3 git-commit/bb80604 kernel/3.13.0-95-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=24.438541532s http.response.status=500 http.response.written=70 instance.id=da4c4fab-730c-4be4-8c1a-38b9bcdfb6b6 vars.name=ubuntu vars.uuid=062ec770-029f-417e-9f3c-1fb3150bf938 version=v2.5.1 
```

$ docker info
```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-95-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 80
Total Memory: 503.8 GiB
Name: summerpalace
ID: YPT4:YO6X:2QND:TWUU:S7ZN:CB4E:CSLJ:LQTL:WTZ3:DX7G:U6RU:OE2J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 dockmaster.prod.luminatewireless.com:4001
 127.0.0.0/8
```

**Comment by RichardScothern** [comment] 2016-11-07 21:52
@mzhaom can you post the registry logs for the entire push operation up until the error, as well as the deamon logs (in debug mode)

**Comment by mzhaom** [comment] 2016-11-09 23:02
This the registry log:
[registry.txt](https://github.com/docker/distribution/files/582122/registry.txt)

The docker daemon log:
[docker-daemon.txt](https://github.com/docker/distribution/files/582130/docker-daemon.txt)

**Comment by mzhaom** [comment] 2016-11-11 01:33
A little more information. The image was pulled from a v1 registry. I don't know whether that might cause any issue.

**Comment by saravpkkl** [comment] 2016-12-27 10:44
i am getting the exact same error. if someone finds solution please share....need urgently

**Comment by dmcgowan** [comment] 2017-01-03 18:45
@saravpkkl can you open up a new issues and please include your registry configuration. This is a similar issue but doesn't appear to be the exact same issue.

**Comment by sudhanshu-garg** [comment] 2017-04-24 23:32
@mzhaom Are you still hitting this issue and if yes, what are the steps to reproduce it?

**Comment by saravpkkl** [comment] 2017-05-04 06:48
This is already fixed and closed

**Comment by chenww** [comment] 2017-05-08 15:00
@saravpkkl can you point to the commit with the fix?

**Comment by audrummer15** [comment] 2017-07-18 22:16
I'm also hitting this issue. Unless someone can point to the fix, I would still consider this an open issue.

**Comment by reducm** [comment] 2019-01-27 18:07
same issue +1

**Comment by phdowling** [comment] 2019-03-22 09:33
I'm also seeing this. docker service logs also shows no recognizable errors on the side of the registry, but eventually the push fails with a 500 internal server error.

**Comment by mMohamed451** [comment] 2019-08-01 07:57
anyone found a solution for this issue ?

**Comment by LeandroPT** [comment] 2019-08-01 08:08
Hey @mMohamed451 

In my case all i needed to do was to remove limits on any load balancer before the registry.

I don't know your actually setup, but it is something like this: https://github.com/nginxinc/kubernetes-ingress/issues/21

**Comment by mMohamed451** [comment] 2019-08-01 09:06
i have a solution , make sure that you have the correct tag name for the image , i think this will fix this issue

**Comment by mMohamed451** [comment] 2019-08-01 09:07
i think i have a solution , make sure that you have the correct tag name for the image , i think this will fix this issue

**Comment by mugartec** [comment] 2019-08-19 14:06
I had a very similar error (retrying until failure) and it was not related to docker, but to the file system of the machine hosting the registry. In my case the logs were almost identical to yours except that they said

`msg="mkdir: [...] permission denied"`

I solved it by running the `update-permissions` gitlab script.

Now your case seems to be a little different. From your logs:

`msg="unknown error reading request payload: unexpected EOF"`

I'd take a look at the registry's directory (in my case it was `/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/`) and inspect what's going on there. Have a look at the permissions and search for corrupt files. I hope this helps.

**Comment by bachya** [comment] 2020-03-31 17:03
[This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:

```shell
docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
```

**Comment by dvdnhm** [comment] 2020-07-02 22:23
Looks like the issue is about the registry denying the access, in my case I forgot I deleted the registry on the host

**Comment by 1lolbus1** [comment] 2020-07-14 20:00
> [This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:
> 
> ```shell
> docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
> ```

@bachya Thanks so much for this! For some reason I can't seem to find any real docs on `REGISTRY_HTTP_HOST` anywhere. Do you recall where you found the documentation for this?

**Comment by JigarJoshi04** [comment] 2020-07-30 03:13
Make sure you have given right project id when docker build command was run
gcloud builds submit --tag gcr.io/PROJECT-ID/helloworld
here replace project id properly.
In my case this was the issue

**Comment by hbellafkir** [comment] 2020-09-03 22:20
I have the same issue with a custom caffe image

**Comment by HomeLH** [comment] 2020-12-09 02:27
I have the same issue. 
```
controller-0:~$ sudo docker push 192.168.31.49:5000/docker.io/nfvpe/multus:v3.4 
The push refers to repository [192.168.31.49:5000/docker.io/nfvpe/multus] 
b39e09a96a41: Retrying in 14 seconds 
b4b5c7759f04: Retrying in 13 seconds 
877b494a9f30: Retrying in 13 seconds 
```
Please check your docker proxy settings in `/etc/systemd/system/docker.service.d/http-proxy.conf`. If you set the proxy, you need set no proxy entry. 
```
[Service]
Environment="HTTP_PROXY=http://[your proxy]:[port]/" "HTTPS_PROXY=http://[your proxy]:[port]/" "NO_PROXY=localhost,127.0.0.1,[your private docker registry]"
```
Another way, disable the proxy file with `mv http-proxy.conf http-proxy.bak` directly .

Notice，after you changed your proxy file. you have to reload the docker service.
` sudo systemctl restart docker`
`sudo systemctl daemon-reload`

**Comment by WiRight** [comment] 2020-12-23 08:48
> [This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:
> 
> ```shell
> docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
> ```

Thank you very match! This worked for me

**Comment by patrikszepesi** [comment] 2021-05-09 17:00
I had the same issue but all I had to do was enable this : Google Container Registry API in the google cloud console, worked fine after that.

**Comment by clbx** [comment] 2021-08-12 19:57
> i think i have a solution , make sure that you have the correct tag name for the image , i think this will fix this issue

This fixed an issue I was having with pushing to Nexus thank you @mMohamed451

**Comment by alexsapps** [comment] 2021-12-23 21:31
I had to `docker logout` + `docker login` after changing my API key / password.

I did not see anything in the docker daemon logs. I wish it would show the error while it was retrying so we wouldn't have to guess the issue.

**Comment by iranthau** [comment] 2022-02-22 08:17
It was missing IAM permission on the user in my case.

**Comment by mohammad-hakimi** [comment] 2022-05-28 12:53
> [This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:
> 
> ```shell
> docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
> ```

That's it. You saved my life :))). Thanks a lot.

**Comment by annanguyen19** [comment] 2022-06-11 02:44
> It was missing IAM permission on the user in my case.

Hey, what permission are you missing?

**Comment by fanchuanster** [comment] 2022-07-19 15:22
It can be a disk/storage utilization issue.

**Comment by wikicarlos** [comment] 2022-07-28 18:33
It happened to me, the issue was that i had no permits to create a new image, if you wanna overcome without adding permissions, upload using a different label to your image, and you should be fine =)
if nt, just add permissions to your role =)

**Comment by niels-bosman** [comment] 2022-09-06 19:27
This might only be my stupidity (probably), but I missspelled ghcr.io for ghrc.io.

**Comment by Ghostwritten** [comment] 2023-08-02 22:09
> 
thanks, solve my question

```
$ docker run -d --restart=always --name registry  -p 35000:5000 -v /var/lib/registry:/var/lib/registry registry:latest
$ echo "10.60.0.30 registry.demo" >>/etc/hosts
cat <<EOF> /etc/docker/daemon.json
{
  "insecure-registries" : ["registry.demo:35000"]
}
EOF

$ docker push registry.demo:35000/registry:latest 
The push refers to repository [registry.demo:35000/registry]
bd8ea65e605d: Retrying in 20 seconds 
665fce3f5a4e: Retrying in 5 seconds 
f24009e23f0f: Retrying in 20 seconds 
f68373c1ba86: Retrying in 5 seconds 
78a822fe2a2d: Retrying in 20 seconds 

$ cat  /etc/systemd/system/docker.service.d/proxy.conf 
[Service]
Environment="HTTP_PROXY=http://xxxxx:7890"
Environment="HTTPS_PROXY=http://xxxxx:7890"
Environment="NO_PROXY=localhost,127.0.0.1,.example.com,registry.demo:35000,10.60.0.30"


$ systemctl daemon-reload &&systemctl restart docker && systemctl status docker

$ docker push registry.demo:35000/registry:latest 
The push refers to repository [registry.demo:35000/registry]
bd8ea65e605d: Pushed 
665fce3f5a4e: Pushed 
f24009e23f0f: Pushed 
f68373c1ba86: Pushed 
78a822fe2a2d: Pushed 
latest: digest: sha256:0f7e785a49386d7e98c502151f9b01dc5578aa4f13078a346b2c5cf50433f663 size: 1363


```

**Comment by sivn** [comment] 2023-09-26 11:41
> [This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:
> 
> ```shell
> docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
> ```

Thank you very much! That fixed it for me!

**Comment by VNNCC** [comment] 2023-09-26 11:42
> [This](https://stackoverflow.com/a/39568177) gave me the answer that worked for me – in short, ensure that you run your Registry container with the `REGISTRY_HTTP_HOST` env var specified:
> 
> ```shell
> docker run -e REGISTRY_HTTP_HOST=https://my.registry:5000 -d -p 5000:5000 --name registry registry:2
> ```

Thanks, worked for me :).

**Comment by milosgajdos** [comment] 2024-07-06 10:20
Closing as solved. See: https://github.com/distribution/distribution/issues/2042#issuecomment-606753339

**Closed by milosgajdos** 2024-07-06 10:20 UTC

**Comment by marhav20** [comment] 2024-08-09 14:35
Just in case somebody runs a private registry behind a nginx reverse proxy, the client_max_body_size must be increased or you will see docker layer upload retries when a layer is larger than 10M:

```
server {
    listen 443 ssl;
    server_name <domain name of ingress proxy, e.g. xyz.example.com>;

    client_max_body_size 50000M;

    ssl_certificate <path to ssl certificate chain file>;
    ssl_certificate_key <path to ssl key file>;
    ssl_protocols TLSv1.2 TLSv1.3;

    proxy_set_header Proxy "";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Docker registry
    location /v2 {
        proxy_pass http://<IP or domain of registry>:<port if not 80>;
    }
}
```

**Comment by Firzan97** [comment] 2024-10-23 08:23
Make sure there is no extra spaces between each command

**Comment by MonitorIizard** [comment] 2025-03-08 07:30
> Just in case somebody runs a private registry behind a nginx reverse proxy, the client_max_body_size must be increased or you will see docker layer upload retries when a layer is larger than 10M:
> 
> ```
> server {
>     listen 443 ssl;
>     server_name <domain name of ingress proxy, e.g. xyz.example.com>;
> 
>     client_max_body_size 50000M;
> 
>     ssl_certificate <path to ssl certificate chain file>;
>     ssl_certificate_key <path to ssl key file>;
>     ssl_protocols TLSv1.2 TLSv1.3;
> 
>     proxy_set_header Proxy "";
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
> 
>     # Docker registry
>     location /v2 {
>         proxy_pass http://<IP or domain of registry>:<port if not 80>;
>     }
> }
> ```

U save my life

**Comment by Getitdan** [comment] 2026-01-04 23:02
For me the solution was to disable Cloudflare proxy for the registry DNS record!
Cloudflare limits: 100MB for Free/Pro, 200MB for Business, and 500MB for Enterprise.
This was tricky to find out, because in the past I used to upload 700MB easily, so it was unintuitive.

**Comment by DabeDotCom** [comment] 2026-03-19 01:32
Since this was among the top Google hits, I'm gonna mention another possible cause, just for posterity...

My problem ended up being `Apache2` » `mod_security` » **`SecRequestBodyLimit`**

For better or for worse, I simply disabled it for the `repository/v2` hierarchy:
```
<Location "/v2">
    ProxyPass           https://registry.example.com:5000/v2 keepalive=On
    ProxyPassReverse    https://registry.example.com:5000/v2
    <IfModule mod_security2.c>
        SecRuleEngine Off
    </IfModule>
</Location>
```

(FTR: I hate the way `SecAuditLog /var/log/httpd/modsec_audit.log` includes all ~3GB of binary data in each request!  And I've \*never\* been able to get `SecRequestBodyLimitAction ProcessPartial` to Do What I Mean™...  «shrug»)
