### ISSUE TITLE
PATCH calls fails for registry 2.4.0 when using IAM Instance profile

### ISSUE THREAD

**Issue by mihirv0ra** [distribution/distribution#1684] opened 2016-04-28 22:25 UTC
I tried searching for this issue and didnt see anyone report it.

We were using the docker registry 2.3.0 and upgraded to 2.4.0 (we use S3 for storage using IAM Instance Profile).
There were no issues with push/pull/delete calls when using 2.3.0.
When we started testing the registry upgrade to 2.4.0 we see that,
The PULL works fine.
When doing push the PATCH calls to the registry fails, with unauthorized errors, 
We haven't tried the delete image operation yet, and would be trying that tomorrow. 
One behavior that was strange was the PUSH for images having just POST calls work as expected, however when images pushed make PATCH calls, the calls fail. 

The configuration we are using is as follows,

```
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        region: us-east-1
        bucket: myregistrybucket
        encrypt: true
        secure: true
        v4auth: true
        chunksize: 5242880
    redirect:
        disable: true
    delete:
        enabled: true
```

Am I missing something ? Is there a mandate to pass the accesskey and secretkey parameters, 

The documentation did say to leave it blank for using instance profile, so do i have to even mention the parameters with "" strings or it should handle with my existing configuration.

Thanks.

**Comment by RichardScothern** [comment] 2016-05-09 11:02
Does your IAM profile have the necessary permissions?  They changed between 2.3 and 2.4:
https://github.com/docker/distribution/blob/master/docs/storage-drivers/s3.md#s3-permission-scopes

**Comment by timfeirg** [comment] 2016-05-22 07:23
Mine runs into a very similar issue where push works but pull will fail like yours, and the IAM user has been given full permissions, see in https://github.com/docker/docker/issues/22852#issuecomment-220780910 @RichardScothern

**Comment by timfeirg** [comment] 2016-05-22 07:52
did you make any progress with this issue? @mv012004

**Comment by RichardScothern** [comment] 2016-05-23 17:34
@timfeirg : can you post your registry logs?    

What happens when you copy the sample IAM (posted above?)

Also, can you test your setup with the legacy S3 driver? Change the name in the configuration file from `s3` to `s3goamz`.

**Comment by timfeirg** [comment] 2016-05-26 03:30
@RichardScothern  I changed to `s3goamz`, then push/pull both fail:

```shell
$ docker push localhost:22258/testpush
The push refers to a repository [localhost:22258/testpush]
f6ebe8abdaea: Retrying in 11 seconds
acc5ea83ac4e: Retrying in 11 seconds
85ffd1e01e05: Retrying in 11 seconds
e81197a5814f: Retrying in 11 seconds
481104fae705: Retrying in 11 seconds
1df93d8925b8: Waiting
fd6d078b083f: Waiting
89713c868c2d: Waiting
79a2dc487d51: Waiting
5f70bf18a086: Waiting
be4afcadee58: Waiting
2f12183dca17: Waiting
63538fa1c3d0: Waiting
4300ce4f67ba: Waiting
```

```shell
$ curl http://127.0.0.1:22258/v2/ainur/tags/list
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"s3goamz","Enclosed":{"StatusCode":400,"Code":"InvalidRequest","Message":"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.","BucketName":"","RequestId":"8C1E1195680452FB","HostId":"USVvdtHh5nklw34cg+OyS3G98sUuCbVyKoeV0VgAraHWh36TmU4zujMxKfO24cEFCx2Lq3ndOzU="}}}]}
```

**Comment by timfeirg** [comment] 2016-05-26 13:55
are there any working example out there using `s3` as docker registry storage backend?

**Comment by mzupan** [comment] 2016-05-26 17:10
@timfeirg  this is what I'm using

```
storage:
  s3:
    region: us-east-1
    bucket: company-prod-platform-registry
    secure: true
    v4auth: true
    rootdirectory: /images
  delete:
    enabled: false
  cache:
    blobdescriptor: inmemory
  redirect:
    disable: false
```

**Comment by RichardScothern** [comment] 2016-05-26 17:30
@timfeirg it looks like your AWS region requires v4 request signing ( `v4auth : true` in the configuration)

**Comment by timfeirg** [comment] 2016-05-26 17:41
@RichardScothern so now I added the `v4auth : true`, like this:

```yaml
storage:
#  cache:
#    blobdescriptor: redis
#  filesystem:
#    rootdirectory: /mnt/mfs/registry

  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  s3goamz:
    accesskey: xxx
    secretkey: xxxx
    regionendpoint: http://s3.cn-north-1.amazonaws.com.cn
    region: cn-north-1
    bucket: xxx
    v4auth : true
```

now push works but pull says `error pulling image configuration: unauthorized: authentication required`

**Comment by RichardScothern** [comment] 2016-05-26 17:54
What do the registry logs show?

**Comment by timfeirg** [comment] 2016-05-27 06:43
here are the registry logs @RichardScothern :

```
$ sudo registry serve registry.yml
INFO[0000] redis not configured                          environment=nova go.version=go1.6 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
INFO[0000] using inmemory blob descriptor cache          environment=nova go.version=go1.6 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
INFO[0000] listening on [::]:22258                       environment=nova go.version=go1.6 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
INFO[0002] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=a6dc4f35-af17-4b26-87eb-d2aa1440f215 http.request.method=GET http.request.remoteaddr=127.0.0.1:9448 http.request.uri=/v2/ http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/json; charset=utf-8 http.response.duration=4.116417ms http.response.status=200 http.response.written=2 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=6ee17cf7-e386-48d2-a457-544ef4c5d7e3 http.request.method=GET http.request.remoteaddr=127.0.0.1:9449 http.request.uri=/v2/eru/ainur/manifests/e9accee http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/vnd.docker.distribution.manifest.v2+json http.response.duration=191.570429ms http.response.status=200 http.response.written=4250 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/eru/ainur/manifests/e9accee HTTP/1.1" 200 4250 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=36e0b4fb-3561-464f-b0b6-bc4141aff828 http.request.method=GET http.request.remoteaddr=127.0.0.1:9454 http.request.uri=/v2/eru/ainur/blobs/sha256:911d09728ffd9388b33c62f8ea09d751350a882f719794acb3b186dcf5b958df http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=67.772243ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/eru/ainur/blobs/sha256:911d09728ffd9388b33c62f8ea09d751350a882f719794acb3b186dcf5b958df HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=c3b703b1-ef0b-4426-ad61-8df6914a529f http.request.method=GET http.request.remoteaddr=127.0.0.1:9452 http.request.uri=/v2/eru/ainur/blobs/sha256:a30f34bf13d303f2962283023ae22788dacc51863f15d69b653f88a36c3b7d0d http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=82.829661ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/eru/ainur/blobs/sha256:a30f34bf13d303f2962283023ae22788dacc51863f15d69b653f88a36c3b7d0d HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=2b57f422-7b16-4651-beee-e27c330203e0 http.request.method=GET http.request.remoteaddr=127.0.0.1:9453 http.request.uri=/v2/eru/ainur/blobs/sha256:bbe1c4256df30171585344c50fab278157cbf2cb3a2016bb720e99e49a759743 http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=81.144381ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/eru/ainur/blobs/sha256:bbe1c4256df30171585344c50fab278157cbf2cb3a2016bb720e99e49a759743 HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=58c80e2e-c590-4518-a6a1-40fe1476fc99 http.request.method=GET http.request.remoteaddr=127.0.0.1:9455 http.request.uri=/v2/eru/ainur/blobs/sha256:615765bc0d9f82db061f7575d01bd94c99465a6e8dc1a45b793e6fd179e1ddae http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=73.498483ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:00 +0800] "GET /v2/eru/ainur/blobs/sha256:615765bc0d9f82db061f7575d01bd94c99465a6e8dc1a45b793e6fd179e1ddae HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=ce01d52f-03c3-4360-bc88-e3108118c665 http.request.method=GET http.request.remoteaddr=127.0.0.1:9466 http.request.uri=/v2/eru/ainur/blobs/sha256:911d09728ffd9388b33c62f8ea09d751350a882f719794acb3b186dcf5b958df http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=2.090574ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:01 +0800] "GET /v2/eru/ainur/blobs/sha256:911d09728ffd9388b33c62f8ea09d751350a882f719794acb3b186dcf5b958df HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=3504f282-9dd6-4a28-902b-0daec271da2b http.request.method=GET http.request.remoteaddr=127.0.0.1:9470 http.request.uri=/v2/eru/ainur/blobs/sha256:615765bc0d9f82db061f7575d01bd94c99465a6e8dc1a45b793e6fd179e1ddae http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=9.411742ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:01 +0800] "GET /v2/eru/ainur/blobs/sha256:615765bc0d9f82db061f7575d01bd94c99465a6e8dc1a45b793e6fd179e1ddae HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=539158e3-1a7b-4092-84fe-09014cb85014 http.request.method=GET http.request.remoteaddr=127.0.0.1:9468 http.request.uri=/v2/eru/ainur/blobs/sha256:bbe1c4256df30171585344c50fab278157cbf2cb3a2016bb720e99e49a759743 http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=1.814698ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:01 +0800] "GET /v2/eru/ainur/blobs/sha256:bbe1c4256df30171585344c50fab278157cbf2cb3a2016bb720e99e49a759743 HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=4cf10c17-22b1-4626-a251-67b916b64975 http.request.method=GET http.request.remoteaddr=127.0.0.1:9467 http.request.uri=/v2/eru/ainur/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=47.089449ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:01 +0800] "GET /v2/eru/ainur/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
INFO[0003] response completed                            environment=nova go.version=go1.6 http.request.host=127.0.0.1:22258 http.request.id=4e31d0ec-44d0-4880-b625-7515940fb812 http.request.method=GET http.request.remoteaddr=127.0.0.1:9474 http.request.uri=/v2/eru/ainur/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 http.request.useragent=docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \(linux\)) http.response.contenttype=application/octet-stream http.response.duration=6.015185ms http.response.status=307 http.response.written=477 instance.id=0d0ee842-52ee-4e66-8f3e-203bc3d3293a service=registry version=v2.4.1+unknown
127.0.0.1 - - [27/May/2016:01:40:01 +0800] "GET /v2/eru/ainur/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 307 477 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-123.4.4.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
```

**Comment by RichardScothern** [comment] 2016-05-27 17:15
@timfeirg There is nothing indicating an error in those logs.

I think you'll need to do some troubleshooting.  Did this stop working with a specific version of the registry?  Are you able to push/pull with a filesystem backend?  What do the daemon logs (in debug mode) and the registry logs display when the errors occur?

**Comment by timfeirg** [comment] 2016-05-28 07:29
@RichardScothern 
* I'm using `registry github.com/docker/distribution v2.4.1`, I've tried older versions but they all didn't work.
* using the local filesystem backend works fine, but we're trying to migrate to s3.
* daemon logs are provided in https://github.com/docker/docker/issues/22852#issuecomment-220775622
* if I change `s3goamz` back to `s3`, pushing will work, while pull still won't.

in fact the only error logs are inside docker daemon logs, any chance that this was actually a docker issue?

**Comment by mkm85** [comment] 2016-08-12 09:09
setting REGISTRY_STORAGE_REDIRECT_DISABLE=true circumvents the problem so it must be somewhere in the generation of the s3 download redirect url the problem occurs.

**Comment by RichardScothern** [comment] 2016-08-12 16:04
hi @mkm85 that's interesting!

What exactly is the error returned when you curl the redirect URL issued for `cn-north-1`

**Comment by mkm85** [comment] 2016-08-12 17:20
The error returned from s3 is:

 HTTP/1.1 401 Unauthorized
...
<Error><Code>UnauthorizedAccess</Code><Message>You are not authorized to perform this operation</Message><RequestId>9F0259105348B6F1</RequestId><HostId>cXQZ3v89RsNrcxq8Hp/dTiBLB3HFAqX9DZLQjbbpbdLpFlK9enufKiONgIuVReiGZHSiJn5gtwA=</HostId></Error>

One thing that seems odd is that the security token in the redirect url from the registry has 10 %2F in it: X-Amz-Security-Token=FQoDYXdzENn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwE....

Is it s3-aws or s3-goamz which is used when the s3 storage driver is chosen?

**Comment by cetex** [comment] 2016-10-17 16:12
I found that i have the same problem.

I noticed that in China you need a "ICP license" to enable your account for presigned url's (as that's considered publishing information)
https://www.amazonaws.cn/en/about-aws/china/faqs/

Without this license AWS / S3 china by default seems to deny any presigned url requests.

I've checked and it seems i can't disable the http redirect in docker registry at all nowadays..

my config:
`version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    s3:
      accesskey: AKIAxxxxxxxx
      secretkey: /pcaasdlkh+asc8uljkhac
      region: cn-north-1
      bucket: company-docker
    redirect:
      disable: true
http:
    addr: :5000
    secret: oiasclkjaljsc
`

secrets, keys and bucket anonymized..

**Comment by dmcgowan** [comment] 2016-12-20 22:44
@cetex thank you for that information. I wonder if we should include that in our documentation.

> I've checked and it seems i can't disable the http redirect in docker registry at all nowadays..

That shouldn't be correct. Do you have an HTTP capture or docker daemon logs showing this redirect happening?

**Comment by milosgajdos** [comment] 2023-12-18 10:46
Closing as outdated. Please verify if the issue is still present in the latest release or on the `main` branch and reopen if need be.

**Closed by milosgajdos** 2023-12-18 10:46 UTC
