### ISSUE TITLE
Docker Registry V2.8.1 Push fails to GCS "Blob Upload Unknown" "upload resumed at wrong offest: 0 != 772806"

### ISSUE THREAD

**Issue by cgperalt-harness** [distribution/distribution#3609] opened 2022-03-18 03:41 UTC
Hi, 
I'm running into an issue when  pushing docker images with the GCS driver and registry:2.8.1 docker image. 
However, it does work with registry:2.3.1

Below is my conf.yml file 

 ```
   version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      gcs:
        bucket: <gcs-bucket>
        keyfile: /etc/docker/registry/key/gcs-key.json
        rootdirectory: /
    http:
      addr: :5000
      secret: {{.Values.htpasswd}}
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

```

Error:
```
10.128.42.173 - - [18/Mar/2022:03:31:40 +0000] "PUT /v2/plugins/busybox/blobs/uploads/737436ac-2043-4b8c-a85e-5b959ba75859?_state=OJv_dKEM2gRk4zcrWZqPw0gfbDMCeuv55QkxLQWISfx7Ik5hbWUiOiJwbHVnaW5zL2J1c3lib3giLCJVVUlEIjoiNzM3NDM2YWMtMjA0My00YjhjLWE4NWUtNWI5NTliYTc1ODU5IiwiT2Zmc2V0Ijo3NzI4MDYsIlN0YXJ0ZWRBdCI6IjIwMjItMDMtMThUMDM6MzE6MzhaIn0%3D&digest=sha256%3A554879bb300427c7301c1cbdf266a7eba24a85b10d19f270b3d348b9eb9ca7df HTTP/1.1" 404 76 "" "docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.47-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \\(darwin\\))"
time="2022-03-18T03:31:41.684776182Z" level=error msg="response completed with error" err.code="blob upload invalid" err.message="blob upload invalid" go.version=go1.16.15 http.request.host=uat.harness.io http.request.id=95fbcb4d-fc13-4b40-a2a2-577ef0c61282 http.request.method=PUT http.request.remoteaddr=65.115.92.26 http.request.uri="/v2/plugins/busybox/blobs/uploads/737436ac-2043-4b8c-a85e-5b959ba75859?_state=OJv_dKEM2gRk4zcrWZqPw0gfbDMCeuv55QkxLQWISfx7Ik5hbWUiOiJwbHVnaW5zL2J1c3lib3giLCJVVUlEIjoiNzM3NDM2YWMtMjA0My00YjhjLWE4NWUtNWI5NTliYTc1ODU5IiwiT2Zmc2V0Ijo3NzI4MDYsIlN0YXJ0ZWRBdCI6IjIwMjItMDMtMThUMDM6MzE6MzhaIn0%3D&digest=sha256%3A554879bb300427c7301c1cbdf266a7eba24a85b10d19f270b3d348b9eb9ca7df" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.47-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(darwin\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.183947654s http.response.status=404 http.response.written=76 vars.name="plugins/busybox" vars.uuid=737436ac-2043-4b8c-a85e-5b959ba75859
time="2022-03-18T03:31:59.754204989Z" level=info msg="response completed" go.version=go1.16.15 http.request.host=uat.harness.io http.request.id=1f040a05-ba6e-4291-8d16-1003319f6f61 http.request.method=PATCH http.request.remoteaddr=65.115.92.26 http.request.uri="/v2/plugins/busybox/blobs/uploads/b8d0037d-bfb0-47bc-a2b8-1c6fa659cc02?_state=CsczQg8-VqzHFHA4oZMfWrvh-LtCdnVk3jBBAoDYnWd7Ik5hbWUiOiJwbHVnaW5zL2J1c3lib3giLCJVVUlEIjoiYjhkMDAzN2QtYmZiMC00N2JjLWEyYjgtMWM2ZmE2NTljYzAyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTAzLTE4VDAzOjMxOjU3LjEzMzczOTUyOVoifQ%3D%3D" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.47-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(darwin\))" http.response.duration=639.505042ms http.response.status=202 http.response.written=0
```

```
10.128.42.173 - - [18/Mar/2022:03:31:59 +0000] "PATCH /v2/plugins/busybox/blobs/uploads/b8d0037d-bfb0-47bc-a2b8-1c6fa659cc02?_state=CsczQg8-VqzHFHA4oZMfWrvh-LtCdnVk3jBBAoDYnWd7Ik5hbWUiOiJwbHVnaW5zL2J1c3lib3giLCJVVUlEIjoiYjhkMDAzN2QtYmZiMC00N2JjLWEyYjgtMWM2ZmE2NTljYzAyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTAzLTE4VDAzOjMxOjU3LjEzMzczOTUyOVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.47-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \\(darwin\\))"
time="2022-03-18T03:32:00.139898878Z" level=error msg="upload resumed at wrong offest: 0 != 772806" go.version=go1.16.15 http.request.host=uat.harness.io http.request.id=0356d2b1-2a7d-4a4c-9a1c-8fa286181bdc http.request.method=PUT http.request.remoteaddr=65.115.92.26 http.request.uri="/v2/plugins/busybox/blobs/uploads/b8d0037d-bfb0-47bc-a2b8-1c6fa659cc02?_state=BgR0cpSrqinEXe-BwJz1YTFzVbUubjlOMryyXYDMcdx7Ik5hbWUiOiJwbHVnaW5zL2J1c3lib3giLCJVVUlEIjoiYjhkMDAzN2QtYmZiMC00N2JjLWEyYjgtMWM2ZmE2NTljYzAyIiwiT2Zmc2V0Ijo3NzI4MDYsIlN0YXJ0ZWRBdCI6IjIwMjItMDMtMThUMDM6MzE6NTdaIn0%3D&digest=sha256%3A554879bb300427c7301c1cbdf266a7eba24a85b10d19f270b3d348b9eb9ca7df" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.47-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(darwin\))" vars.name="plugins/busybox" vars.uuid=b8d0037d-bfb0-47bc-a2b8-1c6fa659cc02
```

**Comment by cgperalt-harness** [comment] 2022-04-19 02:52
I found the root cause. This has to do with the Role assigned to the Service Account in use.
I assigned the `Storage Admin` role to my service account which according to this link https://cloud.google.com/storage/docs/access-control/iam-roles "Grants full control of buckets and objects"
However that wasn't enough. I found there is a legacy role called `Storage Legacy Bucket Owner` Once I added it everything started working.
is there a reason why the `Storage Admin` role is not working ?

**Comment by cgperalt-harness** [comment] 2022-04-19 02:59
As you can se below the `Storage Admin` role does have `storage.buckets.* ` which should include the same and more permissions as the Legacy one.
```
Storage Legacy Bucket Owner (roles/storage.legacyBucketOwner)
storage.buckets.get 
storage.buckets.update 
storage.buckets.setIamPolicy 
storage.buckets.getIamPolicy 
storage.objects.list 
storage.objects.create 
storage.objects.delete 
storage.multipartUploads.*
```

```
Storage Admin (roles/storage.admin)
firebase.projects.get 
orgpolicy.policy.get1 
resourcemanager.projects.get 
resourcemanager.projects.list 
storage.buckets.* 
storage.objects.* 
storage.multipartUploads.*
```

**Comment by milosgajdos** [comment] 2023-12-20 12:13
Please check if the issue is fixed in the latest release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 

It's extremely unlikely `v2.x` will receive any updates from now on.

**Comment by milosgajdos** [comment] 2024-07-30 09:11
Closing for the lack of noise. Please use the latest v3 release.

**Closed by milosgajdos** 2024-07-30 09:11 UTC
Labels: area/storage/gcs
