### ISSUE TITLE
Push to registry v2 does not detect already pushed layers

### ISSUE THREAD

**Issue by huguesb** [distribution/distribution#1411] opened 2016-02-02 15:38 UTC
Pushing images that only differ by their topmost layer to a v2.2.1 registry result in all layers being uploaded multiple times.

Registry v1 correctly detected that the layers already existed and avoided the upload.

Client is docker 1.9.1.

**Comment by huguesb** [comment] 2016-02-02 16:05
More worrying: when these images are later pulled from the v2 registry, it looks like they don't share any layers, which results in yet more bandwidth wasted and a 900Mb increase in the size of the VM image onto which the containers are pulled (1.8Gb to 2.7Gb).

**Comment by RichardScothern** [comment] 2016-02-02 17:04
hi @huguesb 

The v2 security model necessitated images being re-uploaded.   Registry 2.3 does not require a re-upload if the client has read access to an existing layer in another repository.

Regarding point 2: Docker Engine 1.10 switches to a CAS model internally.

Both of these products are in RC process.   There are more details for both of these changes in the release notes.

**Comment by huguesb** [comment] 2016-02-02 17:47
@RichardScothern Thanks for the reply. I'm not entirely sure what to expect from: "Registry 2.3 does not require a re-upload if the client has read access to an existing layer in another repository."

Our use case is as follows:

1. build a bunch of docker images
2. spin up a local registry and push all images to it
3. spin up a VM and pull all images from the registry
4. power off the VM and export disk image (ova, qcow2, ...) for distribution in cases where reaching out to a docker registry during deployment is not possible (tightly locked-down network)

Although we could conceivably bump docker to 1.10 on the push side we'll be stuck with 1.8 (possibly 1.7 in some cases) on the pull side for a while longer.

Is registry 2.3 going to work for our use case? Can registry 2.2 be coerced to work through config tweaks (security is not an issue for us)?

**Comment by RichardScothern** [comment] 2016-02-02 18:14
If you are using Docker 1.10 and Registry 2.3 in step 2 of your use case, you should not experience duplicate image uploads.

**Comment by stevvooe** [comment] 2016-02-02 20:12
@RichardScothern This is a duplicate of https://github.com/docker/distribution/issues/526. Not sure why that was closed. There are other duplicates of this issue that are identical.

**Comment by stevvooe** [comment] 2016-02-02 20:15
Also a duplicate of docker/docker#14018.

**Comment by huguesb** [comment] 2016-02-19 16:56
@RichardScothern a little update the docker 1.10.1 / distribution 2.3 combo did significantly improve the push side of things.

However:

- it looks like someone pushed an incorrect build of the official registry image to docker hub recently. The 2.3 tag no longer avoids duplicate layer pushes

- the pull side did not improve: the resulting VM image is still massively larger when pulling from v2 registry than from v1

**Comment by RichardScothern** [comment] 2016-02-19 18:06
@huguesb : What makes you think that?  The tag is fixed to a github commit hash and that has not changed.  The image was re-pushed as the underlying image changed (to update glibc)

**Comment by huguesb** [comment] 2016-02-19 18:10
The build logs with the previous image showed a number of messages about layers already belonging to an exiting image on the registry. The build logs with the latest image show every layer being uploaded.

**Comment by huguesb** [comment] 2016-02-19 18:30
@RichardScothern Minimal repro:

```bash
#!/bin/bash
docker build -t foo - <<EOF
FROM alpine:3.3
RUN echo "foo" > /foo
EOF

docker build -t bar - <<EOF
FROM alpine:3.3
RUN echo "bar" > /bar
EOF

docker run -d --name reg --net=host registry:2.3
repo=127.0.0.1:5000

docker tag -f foo $repo/foo
docker tag -f bar $repo/bar
docker push $repo/foo
docker push $repo/bar

docker rmi $repo/foo
docker rmi $repo/bar
docker rmi foo
docker rmi bar
docker rm -fv reg
```

I see the base image being uploaded twice with the latest registry image.

**Comment by RichardScothern** [comment] 2016-02-19 18:41
Thanks for the repro, it's very useful.

When I run it with docker 1.10 I see the base layer (confirmed as equal in both images with `docker history`) mounted on the second push:

```
...
/tmp/scratch $ docker history bar:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
52136ca31609        15 hours ago        /bin/sh -c echo "bar" > /bar                    4 B                 
90239124c352        2 days ago          /bin/sh -c #(nop) ADD file:0f9cfb2e848f093649   4.794 MB            
/tmp/scratch  docker history foo:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6e1b81add7ee        15 hours ago        /bin/sh -c echo "foo" > /foo                    4 B                 
90239124c352        2 days ago          /bin/sh -c #(nop) ADD file:0f9cfb2e848f093649   4.794 MB            
/tmp/scratch $  docker run -d --name reg --net=host registry:2.3
Unable to find image 'registry:2.3' locally
2.3: Pulling from library/registry

7268d8f794c4: Already exists 
a3ed95caeb02: Already exists 
6915c066a24f: Already exists 
7f04289ca403: Already exists 
7539a42f6147: Already exists 
Digest: sha256:fe21f44b49c84f577872f8a79d000deab999b2ac70ff873df5b3a5fe71d68868
Status: Downloaded newer image for registry:2.3
5f340e5be2b6d4788926b3b3618cf85c20a63ee3be092935862fefb891534a44
/tmp/scratch  docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
5f340e5be2b6        registry:2.3              "/bin/registry /etc/d"   15 hours ago        Up 4 seconds                            reg
1ce7164eb196        dockercore/docker:tools   "hack/dind /bin/bash"    8 days ago          Up 32 hours                             dr_test_cont
/tmp/scratch $ repo=127.0.0.1:5000
/tmp/scratch $ docker tag -f foo $repo/foo
Warning: '-f' is deprecated, it will be removed soon. See usage.
/tmp/scratch  docker tag -f bar $repo/bar
Warning: '-f' is deprecated, it will be removed soon. See usage.
/tmp/scratch $  docker push $repo/foo
The push refers to a repository [127.0.0.1:5000/foo]
c4f0cb42b953: Pushed 
18efc99a87df: Pushed 
latest: digest: sha256:f211955549261c48acdd927e6afffd9365445e59b81296602bcf3eb8599428d3 size: 713
/tmp/scratch $ docker push $repo/bar
The push refers to a repository [127.0.0.1:5000/bar]
c8ae3f5c6f35: Pushed 
18efc99a87df: Mounted from foo 
latest: digest: sha256:0fd4cef7709124900549f6344ebbe78a006e1547a2abaedbccf25130955dca10 size: 713
/tmp/scratch $ 


```

**Comment by huguesb** [comment] 2016-02-19 18:46
Hmm, my daemon is 1.10.1 and my client is 1.9.1, could that be an issue?

**Comment by huguesb** [comment] 2016-02-19 18:48
Here's the output I get:

```
./repro.sh
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 14f89d0e6257
Step 2 : RUN echo "foo" > /foo
 ---> Running in c108725ae7e4
 ---> 1233abc9324e
Removing intermediate container c108725ae7e4
Successfully built 1233abc9324e
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 14f89d0e6257
Step 2 : RUN echo "bar" > /bar
 ---> Running in 000f97415f0d
 ---> 6ff8816e4327
Removing intermediate container 000f97415f0d
Successfully built 6ff8816e4327
49c56a146580b119091649275c563624bdd68d811f6cfb6d1954702b2a66c91b
The push refers to a repository [127.0.0.1:5000/foo]
7a73c4c34f43: Pushed
6102f0d2ad33: Pushed
latest: digest: sha256:98b97847c978be10ca912a0f333fac87d958e8681358892a518bacdae67b2642 size: 713
The push refers to a repository [127.0.0.1:5000/bar]
9c280f1ae1da: Pushed
6102f0d2ad33: Pushed
latest: digest: sha256:366490243ed5615a52d2a09fdab1c59691799f4b6fbab7a03f6006a3c0e44dea size: 713
```

**Comment by huguesb** [comment] 2016-02-19 18:57
Also potentially relevant, we don't seem to have the same registry image:

```
registry                                2.3                 sha256:c3c09        2 days ago          165.7 MB
```

**Comment by huguesb** [comment] 2016-02-19 18:59
Nevermind, I removed my local `registry:2.3` image and pulled the latest, which matches the sha in your logs above, and the issue persists.

**Comment by blackadmin** [comment] 2016-03-06 00:25
Same here, I pushed my image and then pulled the same image and then when I pushed the same image it started uploading, instead of saying Already exists, please fix this issue.

Docker version 1.10.2, build c3959b1

**Comment by kopax** [comment] 2016-05-28 05:18
same issue

**Comment by RichardScothern** [comment] 2016-05-31 18:10
For those of you who see this please run the above repo script and paste the results.  Also include your docker and registry versions.

**Comment by shyr** [comment] 2016-06-01 07:15
hi guys. I ran repro scripts several times and figured out that the exist layer mounted well at first run of the script, but after that it re-pushed. 

First run of repro script :
```
$ ./repro.sh 
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 13e1761bf172
Step 2 : RUN echo "foo" > /foo
 ---> Running in 7209338b6bc0
 ---> 4fb8b1328c61
^[bRemoving intermediate container 7209338b6bc0
Successfully built 4fb8b1328c61
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 13e1761bf172
Step 2 : RUN echo "bar" > /bar
 ---> Running in 5f3d6eb36814
 ---> 0515e4368382
Removing intermediate container 5f3d6eb36814
Successfully built 0515e4368382
693339da70c26846d2cf60175ef0083205376935effc4f129ae139b302e1b808
Warning: '-f' is deprecated, it will be removed soon. See usage.
Warning: '-f' is deprecated, it will be removed soon. See usage.
The push refers to a repository [127.0.0.1:5000/foo]
5a6e12b3a158: Pushed 
8f01a53880b9: Pushed 
latest: digest: sha256:5078773e83537f85b38fd967fa70beaed8e1c124fa6beae4a7462926bb250c65 size: 713
The push refers to a repository [127.0.0.1:5000/bar]
57d1d4e452e2: Pushed 
8f01a53880b9: Mounted from foo 
latest: digest: sha256:38953c0205fed076d67663b6b9690fba9a61bf8556bbe7a8ba36d5d016904934 size: 713
Untagged: 127.0.0.1:5000/foo:latest
Untagged: 127.0.0.1:5000/bar:latest
Untagged: foo:latest
Deleted: sha256:4fb8b1328c6148c3db15c65265828aabf94058d613faff07676b18e092545118
Deleted: sha256:afa5300d8029c4045c8444fbd29e723ad0f08694459d92f69b7d487afea00697
Untagged: bar:latest
Deleted: sha256:0515e43683825bb8141cff775f0e9a925bae0382191a32b4352359952154b7e1
Deleted: sha256:924901c92248cd79f285c46407aaf28c3416d7b334a87a208dc6de820f684572
reg
```

But since then, it keeps re-push :
```
$ ./repro.sh 
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 13e1761bf172
Step 2 : RUN echo "foo" > /foo
 ---> Running in 1e94a928ef01
 ---> 161268bc89fe
Removing intermediate container 1e94a928ef01
Successfully built 161268bc89fe
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:3.3
 ---> 13e1761bf172
Step 2 : RUN echo "bar" > /bar
 ---> Running in 9b8f732d3aec
 ---> b28847cd446b
Removing intermediate container 9b8f732d3aec
Successfully built b28847cd446b
ab71870b86146a389827b25c74a5050446943659fe80b74f3fac3350a85cee4f
Warning: '-f' is deprecated, it will be removed soon. See usage.
Warning: '-f' is deprecated, it will be removed soon. See usage.
The push refers to a repository [127.0.0.1:5000/foo]
17edc7f8cdce: Pushed 
8f01a53880b9: Pushed 
latest: digest: sha256:8432c81ca583bc13fcb3e5e4f2683765b200c29244934e054f084c623b0423c2 size: 713
The push refers to a repository [127.0.0.1:5000/bar]
f1f3a63f7e34: Pushed 
8f01a53880b9: Pushed 
latest: digest: sha256:b1f63c7133791ac0fedc8bc591323e41e6ae2ba959d7427118346aff7951f4f0 size: 712
Untagged: 127.0.0.1:5000/foo:latest
Untagged: 127.0.0.1:5000/bar:latest
Untagged: foo:latest
Deleted: sha256:161268bc89fe7273a6fd2ba8a33900c6519d310c1f41d081b102e137ed7205c0
Deleted: sha256:ef1cae8f74630756a1684380499c0561e4adcc4d2a2b1db5ee2823d62ea9115e
Untagged: bar:latest
Deleted: sha256:b28847cd446babb890f7bbd8ec7a099da0e1565401abfbbcb1fcf4a14b0983dc
Deleted: sha256:f053c867f5e76ea8b5955c0a1af074015d00d8496ed30d88e4eef36373f8c7d4
reg
```

I didn't change anything in the repro script. And my docker version is
```
$ docker --version
Docker version 1.10.0, build 590d5108
```

**Comment by shyr** [comment] 2016-06-01 07:30
I faced same issue with @blackadmin 
I'm not sure it's relevant with `cross-repository blob mount`. I re-pushed very same repository consecutively, but docker re-pushed exist layer randomly.

You can find the layer `9b54b37c4b2f` existed, but it was re-pushed again.
```
...
9b54b37c4b2f: Layer already exists
b3687b0f9f71: Layer already exists
a21babc8f3fa: Layer already exists
d7ec9dc6a652: Layer already exists
e6af6652191f: Layer already exists
9a6b1be058f3: Layer already exists
3501aee2afbe: Layer already exists
2f8a0c55e2e1: Layer already exists
e1df6df9d2bb: Layer already exists
efb0355fd067: Layer already exists
99016a5b7f58: Layer already exists
0c6c3ef2d6e1: Layer already exists
6b3267f47fde: Layer already exists
e3abc875f790: Layer already exists
6259f9fc3207: Layer already exists
b7d446781409: Layer already exists
df26f0ecf8f5: Layer already exists
5f70bf18a086: Layer already exists
17a992d2fac2: Pushed
2.0.1: digest: sha256:c53d366b2fabe60d622f8d5f55cae2acbb28a6d68058387ccdee1b3c7a74c1c3 size: 7599
[root@kolla-dist kolla]# docker push registry.navercorp.com/kolla-dev/centos-source-nova-compute-ironic
The push refers to a repository [registry.navercorp.com/kolla-dev/centos-source-nova-compute-ironic]
034314b8936c: Layer already exists
05c507c74528: Layer already exists
145db4b86ab7: Layer already exists
2e5fb19c603b: Layer already exists
77b3ac555c0e: Layer already exists
4eb7c8dac292: Layer already exists
90dda7e0beab: Layer already exists
0fa258523dbe: Layer already exists
6abe16bb8600: Layer already exists
2d78557b726d: Layer already exists
85bba687e00d: Layer already exists
451a5f59c683: Layer already exists
c65e0d49b93d: Pushed
c6076ddd7662: Pushed
9b54b37c4b2f: Pushed
b3687b0f9f71: Pushed
a21babc8f3fa: Pushed
d7ec9dc6a652: Pushed
e6af6652191f: Pushed
9a6b1be058f3: Pushed
3501aee2afbe: Pushed
2f8a0c55e2e1: Pushed
e1df6df9d2bb: Pushed
efb0355fd067: Pushed
...
```

**Comment by junoyoon** [comment] 2016-06-01 07:39
https://github.com/docker/distribution/issues/1411#issuecomment-222914944

In addition to this. We found out that this only happens when the docker registry auth is applied.

**Comment by aaronlehmann** [comment] 2016-06-01 17:14
It may be helpful to see a registry log that corresponds to a push with redundant uploads. Docker will generally check if the registry already has layers using a `HEAD` request. It would be interesting to see whether this `HEAD` request is being made, and whether the registry returns an error.

**Comment by stevvooe** [comment] 2016-06-01 23:34
> Docker will generally check if the registry already has layers using a HEAD request. It would be interesting to see whether this HEAD request is being made, and whether the registry returns an error.

Are these layers actually being pushed or is the CLI justing saying they are? It is possible this is a CLI bug...

**Comment by polaru** [comment] 2016-09-21 09:39
I haven't run the repo.sh test, but I reproduced it while investigating the same issue (pushing layers that shouldn't have), before searching online for a solution, and I believe the problem is with docker daemon. In my setup I build the same image twice:
{code}
sudo docker build -t docker-registry-push3.example.com/myrepo/testregistry2any:`date +'%Y%m%d-%H%M%S'` .
{code}
after that I change a LABEL at the top of the Dockerfile to trigger rebuilding only some of the layers and tag with a different image name
{code}
sudo docker build -t docker-registry-push1.example.com/myrepo/testregistry2any:`date +'%Y%m%d-%H%M%S'` .
{code}
Both addresses (docker-registry-push[13].example.com) point to the same local registry.
The first push works properly (not pushing the layers at the top, before the changed LABEL), the second one pushes everything. 
The first push starts with 3 HEAD requests (which get HTTP 200 from registry) and following 4 POST requests (which get HTTP 202).
The second push starts with 5 POST requests (which get HTTP 202).
This makes me think that docker daemon already assumes some knowledge about the layers. How can I find out more about this?

docker registry 2.3.1 and daemon 1.10.3

**Comment by milosgajdos** [comment] 2024-04-21 08:55
Closing as wildly outdated. please check with the latest `v3` release and reopen if need be.

**Closed by milosgajdos** 2024-04-21 08:55 UTC
