### ISSUE TITLE
push image to docker hub,but got "unauthorized"error 

### ISSUE THREAD

**Issue by adezdl** [distribution/distribution#1679] opened 2016-04-28 01:16 UTC
i have logged in successfully,but got this error.
someone said "Adding the X-Forwarded-Proto in the proxy configuration fixes it",but i am prohibited
from modifying my company's proxy server. Any other way? 

Environment: Ubuntu 14.04 LTS + Docker 1.10.3

root@ubuntu:~# 
root@ubuntu:~# docker login
Username: zdldocker
Password: 
Email: 
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
root@ubuntu:~# 
root@ubuntu:~# docker push zdlrepository/tomcattwo:latest
The push refers to a repository [docker.io/zdlrepository/tomcattwo]
f4ba23d94afc: Preparing 
f4ade33f15c9: Preparing 
501416a091a6: Preparing 
35ee642fd1c2: Preparing 
16879aa5082c: Preparing 
5f70bf18a086: Waiting 
f75f146a5022: Waiting 
711b0bd2cb6a: Waiting 
595d1d53a534: Waiting 
unauthorized: authentication required

**Comment by noxiouz** [comment] 2016-04-28 13:15
I have the same issue with beta  Docker for Mac and private Registry v.2.3.1
```
213.180:~$ docker push registry.yandex.net/echo
The push refers to a repository [registry.yandex.net/echo]
c5b0034201f2: Layer already exists
da61c8f6fafa: Layer already exists
8bfac3bbfefc: Layer already exists
631b7aecffd0: Layer already exists
6208212fc500: Layer already exists
08456b53c47e: Layer already exists
264f7eca249d: Layer already exists
5f70bf18a086: Layer already exists
ceddf6185bdf: Layer already exists
d5c8f5da98d4: Layer already exists
a523be55ce6e: Layer already exists
unauthorized: authentication required
```

`tcpdump` shows me that the last redirect is done without Authorization header 

```
POST /v2/echo/blobs/uploads/ HTTP/1.1
Host: registry.yandex.net
X-Real-IP: 213.180.219.220
Content-Length: 0
User-Agent: docker/1.11.0 go/go1.5.4 git-commit/a5315b8 kernel/4.4.6 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \(darwin\))
Authorization: Basic <token>
Content-Type:
Accept-Encoding: gzip

HTTP/1.1 202 Accepted
Content-Length: 0
Docker-Distribution-Api-Version: registry/2.0
Docker-Upload-Uuid: f74400cf-741b-49be-8115-6038f8c7b1e8
Location: http://registry.yandex.net/v2/echo/blobs/uploads/f74400cf-741b-49be-8115-6038f8c7b1e8?_state=y8fcAuy-67ztJW51VD15obV3bvdVzl68qP5xMW4WQ-F7Ik5hbWUiOiJlY2hvIiwiVVVJRCI6ImY3NDQwMGNmLTc0MWItNDliZS04MTE1LTYwMzhmOGM3YjFlOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0yOFQxMjo1MDoxOS4xNDY1MzE5NzVaIn0%3D
Range: 0-0
Date: Thu, 28 Apr 2016 12:50:19 GMT
Content-Type: text/plain; charset=utf-8


PATCH /v2/echo/blobs/uploads/f74400cf-741b-49be-8115-6038f8c7b1e8?_state=y8fcAuy-67ztJW51VD15obV3bvdVzl68qP5xMW4WQ-F7Ik5hbWUiOiJlY2hvIiwiVVVJRCI6ImY3NDQwMGNmLTc0MWItNDliZS04MTE1LTYwMzhmOGM3YjFlOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0yOFQxMjo1MDoxOS4xNDY1MzE5NzVaIn0%3D HTTP/1.1
Host: registry.yandex.net
X-Real-IP: 213.180.219.220
Content-Length: 4772
User-Agent: docker/1.11.0 go/go1.5.4 git-commit/a5315b8 kernel/4.4.6 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \(darwin\))
Accept-Encoding: gzip

{<some big secret JSON here :) >}

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic
Date: Thu, 28 Apr 2016 12:50:19 GMT
Content-Length: 188

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"echo","Action":"pull"},{"Type":"repository","Name":"echo","Action":"push"}]}]}
```

**Comment by dmcgowan** [comment] 2016-04-28 18:52
@noxiouz It would be helpful seeing the request that comes directly out of the engine to know if the authorization header was no added, or if it was stripped by the proxy.

@adezdl likewise more information about the request that came out of the engine. If you cannot get that debug logs from the engine will be helpful. Does it also seem as though some requests succeed and some fail (for example just `PATCH` requests fail). I am assuming authorization is not always being stripped since the login succeeded fine.

**Comment by noxiouz** [comment] 2016-04-28 19:36
@dmcgowan Do you want tcpdump between Docker and nginx? It requires to switch off https

**Comment by dmcgowan** [comment] 2016-04-28 21:01
@noxiouz That is what I want. There are plenty of tools which will do https mitm if you are able to update your certificate list for it.

**Comment by noxiouz** [comment] 2016-04-28 21:46
That's what I can provide now. I add insecure-registry to use http.
```
PATCH /v2/echo/blobs/uploads/2bcf7d5e-5456-473a-893a-741cad3a6f3b?_state=huFzHJcUG9ptT1Q3xY-TQImh6SfrwrmJnKUWZJ7gHKR7Ik5hbWUiOiJlY2hvIiwiVVVJRCI6IjJiY2Y3ZDVlLTU0NTYtNDczYS04OTNhLTc0MWNhZDNhNmYzYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0yOFQyMTo0MjowMy45NjYxOTc1MDVaIn0%3D HTTP/1.1
Host: registry.yandex.net
User-Agent: docker/1.11.0 go/go1.5.4 git-commit/a5315b8 kernel/4.4.6-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \(darwin\))
Transfer-Encoding: chunked
Accept-Encoding: gzip
Connection: close

HTTP/1.1 401 Unauthorized
Server: nginx/1.8.1
Date: Thu, 28 Apr 2016 21:42:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 188
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"echo","Action":"pull"},{"Type":"repository","Name":"echo","Action":"push"}]}]}
```

**Comment by dmcgowan** [comment] 2016-04-28 22:07
@noxiouz thanks. I don't think the server side packets will be helpful since it appears the `Authorization` header is missing leaving the engine. Engine debug logs may be useful in this case. Does the previous HTTP still have the `Authorization` and `Location` header?

**Comment by noxiouz** [comment] 2016-04-28 22:31
I tried 1.11 on linux on the same host where registry is and eliminate nginx, and it works. I need some time to investigate reproducing conditions.

**Comment by milosgajdos** [comment] 2023-12-22 10:15
Closing as wildly outdated. Feel free to reopen.

**Closed by milosgajdos** 2023-12-22 10:15 UTC
