### ISSUE TITLE
Docker [2.1.0.0 BUG]: Duplicate mount points

### ISSUE THREAD

**Issue by p-gonzo** [distribution/distribution#2971] opened 2019-08-01 17:40 UTC
## Example Repo:
https://github.com/p-gonzo/docker-duplicate-mount-points-bug

## Background:

- We are developing a white-labeled application that uses Docker Compose to switch between static assets.
- We have a separate .yml file per-application to do the asset linking

## Usage (On Docker 2.0.0.3 on OSX):

- Running `docker-compose -f docker-compose-one.yml up` in the root of this directory
     - Outputs `Hello Assets One!` at `http://localhost:3000`

- Running `docker-compose -f docker-compose-two.yml up` in the root of this directory
     - Outputs `Hello Assets Two!` at `http://localhost:3000`

## Bug in latest version of Docker (After upgrading to 2.1.0.0):
- Running `docker-compose -f docker-compose-one.yml up` in the root of this directory produces the error:
    ```bash
    ERROR: Duplicate mount points: [/usr/src/app/web/static, /Users/phil/Desktop/docker-duplicate-mount-points-bug/web/assets_two:/usr/src/app/web/static:rw]
    ```
- Running `docker-compose -f docker-compose-one.yml up` in the root of this directory produces the error:
    ```bash
        ERROR: Duplicate mount points: [/usr/src/app/web/static, /Users/phil/Desktop/docker-duplicate-mount-points-bug/web/assets_two:/usr/src/app/web/static:rw]
    ```

## Notable Upgrades between 2.0.0.3 and 2.1.0.0:
- Docker 19.03.1
- Docker Compose 1.24.1
- Kubernetes 1.14.3
- Compose on Kubernetes 0.4.23
- Docker Machine 0.16.1
- linuxkit v0.7
- Linux Kernel 4.9.184
- Kitematic 0.17.6
- Qemu 4.0.0 for cross compiling for ARM
- Alpine 3.10
- Docker Credential Helpers 0.6.3

**Comment by jwnardini** [comment] 2019-08-07 19:11
This was an issue for me when I updated Docker to 2.1.0 without updating Lando. My lando version was v3.0.0-beta.47, but the latest version was Lando v3.0.0-rc.19. I was getting the `Duplicate mount points` errors as a result on all lando commands. 

Updating lando to v3.0.0-rc.19 solved the issue for me, no more errors.

Easy lando update method: Download directly from github
https://github.com/lando/lando/releases/tag/v3.0.0-rc.19

For me (on Mac) I simply installed the .dmg file and ran it. Makes updating lando a breeze!

**Comment by p-gonzo** [comment] 2019-08-08 15:41
Thanks @jwnardini for your post!

Unfortunately we are not using Lando to manage docker, so I believe the two issues are unrelated.

**Comment by HeathNaylor** [comment] 2019-09-27 00:37
@p-gonzo, I decided to take a look at this, can you explain what your intention is with this line? https://github.com/p-gonzo/docker-duplicate-mount-points-bug/blob/master/docker-compose-one.yml#L8

It is in both Dockerfiles and has some unsavory side effects in 2.0.0.3 that I believe 2.1.0.0 is resolving via an error message. Essentially what is happening is that the _last_ duplicate mounted volume is _overwriting_ the one before it.

I have confirmed the behavior you are seeing, but I think it is by design and is there to be more explicit about the overwriting behavior you were seeing on the previous version.

You can take a look at my changes to demonstrate this in my fork of your repo.
https://github.com/HeathNaylor/docker-duplicate-mount-points-bug/commit/b5b86a34c2a92f50d48079e3f2f10cb10fce30b7

**Comment by p-gonzo** [comment] 2019-09-27 15:08
Hi @HeathNaylor - thanks for your comments.  

I don't believe what you are describing would resolve the issue I'm experiencing.  Here's the breakdown of each line and it's purpose:

`- ./:/usr/src/app`
    - Mount the current directory in /usr/src/app in Docker
`- /usr/src/app/web/static`
    - However, ignore the static folder (located on my machine at ./web/static)
`- ./web/assets_one:/usr/src/app/web/static`
    - Now mount `./web/assets_one` to the previously ignored location
`- /usr/src/app/web/nodeApp/node_modules`
    - Ignore the folder located on my machine at `./web/NodeApp/node_modules`

**Comment by milosgajdos** [comment] 2023-08-13 21:02
Closing, this is the wrong repository to report this in. Please ask in https://github.com/moby/moby

**Closed by milosgajdos** 2023-08-13 21:02 UTC
