### ISSUE TITLE
High memory usage with s3 driver

### ISSUE THREAD

**Issue by klausenbusk** [distribution/distribution#1533] opened 2016-03-15 22:02 UTC
The s3 driver seems to have a rather high memory usage when pushing and a few minutes after.

Tested with: `docker pull golang:1.6 && docker tag .. && docker push`
With the default chunk size of 10MB peak memory is around 148MB, with a chunk size of 5MB peak memory is around 98MB.

Registry was started like:

```
docker run -t -i 
    -e REGISTRY_STORAGE=s3
    -e REGISTRY_STORAGE_S3_REGION=eu-central-1
    -e REGISTRY_STORAGE_S3_BUCKET=foo
    -e REGISTRY_STORAGE_S3_ACCESSKEY="foo"
    -e REGISTRY_STORAGE_S3_SECRETKEY="barr"
    -e REGISTRY_STORAGE_S3_V4AUTH=true
    -e REGISTRY_STORAGE_S3_CHUNKSIZE=5242880
    -e REGISTRY_LOG_LEVEL=debug
    -e GOGC=5
    --rm
    -p 5000:5000
    --name registry
    distribution/registry:master
```

pprof:

```
http://sprunge.us/fIZM (before)
http://sprunge.us/aNDg (under)
http://sprunge.us/giQI (under)
http://sprunge.us/GVII (under)
http://sprunge.us/XHdK (after with debug=2)
http://sprunge.us/cULA (after with debug=2)
http://sprunge.us/NHMh (after with debug=2, memory dropped to 21MB)
```

docker version/info and registry version

```
[kristian@arch-hp-laptop ~]$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
[kristian@arch-hp-laptop ~]$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 126
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:3-6949349-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.265 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.1 GB
 Metadata Space Used: 9.867 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.119 (2016-03-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.32 GiB
Name: arch-hp-laptop
ID: MDNG:D2CL:76WB:JMFF:OESH:A7HR:LFWB:ISOI:R7XY:QDI6:3IHV:KHOS
Username: klausenbusk
Registry: https://index.docker.io/v1/
root@b237c8b87c8b:/go/src/github.com/docker/distribution# registry --version
registry github.com/docker/distribution 2c635d1
```

**Comment by stevvooe** [comment] 2016-03-15 22:17
Confirmed we may be leaking or generating undue garbage in the s3-aws driver. A fix will require further investigation.

**Comment by RichardScothern** [comment] 2016-03-17 20:58
thanks for the report @klausenbusk 

I did a cursory investigation and fished the stats out of the table and the end of the prof files.

As far as I can tell, the maximum heap size is ~63mb.   Between the third 'under' sample and the first `before` sample, 900mb are allocated and freed.  It might be instructive to take more samples to find out what is going on.  The system is using ~90mb of memory (and not releasing it), but there is no further breakdown in the files.  As an aside, I can get `Sys` to jump from 7mb to 110mb by `make`ing a 100mb []byte, so that may account for some allocations by the S3 driver.

I'm unable to get a meaningful stacktrace from the provided profiles.  @klausenbusk : could you take another sample in your setup as follows:
`go tool pprof -alloc_space bin/registry http://<reg-host>:<debug-port>/debug/pprof/heap`
enter `top10` and paste the results?
This gives a pretty telling indication of memory usage per function.

data
------
 
**HeapAlloc** bytes allocated and not yet freed

Stage | bytes
----- | -----
before.heap | 1935312
under-1.heap | 13138392
under-2.heap | 31052784
under-3.heap | 61827472
after-1.heap | 2570416
after-2.heap | 2451016
after-3.heap | 2559496

**HeapInuse**  bytes in non-idle span

Stage | bytes
----- | -----
before.heap | 2785280
under-1.heap | 14524416
under-2.heap | 32432128
under-3.heap | 63143936
after-1.heap | 3596288
after-2.heap | 3547136
after-3.heap | 3604480

**Sys** bytes obtained from system

Stage | bytes
----- | -----
before.heap | 7145720
under-1.heap | 27711736
under-2.heap | 53491960
under-3.heap | 91646200
after-1.heap |  91646200
after-2.heap | 91646200
after-3.heap | 91646200

**TotalAlloc** bytes allocated (even if freed)

Stage | bytes
----- | -----
before.heap | 13661792
under-1.heap | 90777808
under-2.heap | 181991440
under-3.heap | 314751600
after-1.heap | 1417051384
after-2.heap | 1422790608
after-3.heap | 1426362008

**Comment by klausenbusk** [comment] 2016-03-17 21:24
Before I started push
```
(pprof) top10
2562.32kB of 2562.32kB total (  100%)
Showing top 10 nodes out of 34 (cum >= 512.05kB)
      flat  flat%   sum%        cum   cum%
  513.25kB 20.03% 20.03%   513.25kB 20.03%  regexp/syntax.(*compiler).rune
  512.81kB 20.01% 40.04%   512.81kB 20.01%  github.com/bradfitz/http2.init.2
  512.19kB 19.99% 60.03%   512.19kB 19.99%  runtime.malg
  512.05kB 19.98% 80.02%   512.05kB 19.98%  regexp/syntax.(*Regexp).Simplify
  512.02kB 19.98%   100%   512.02kB 19.98%  regexp.mergeRuneSets.func2
         0     0%   100%   512.81kB 20.01%  github.com/bradfitz/http2.init
         0     0%   100%   512.05kB 19.98%  github.com/docker/distribution/registry.NewRegistry
         0     0%   100%   512.05kB 19.98%  github.com/docker/distribution/registry.glob.func2
         0     0%   100%   512.05kB 19.98%  github.com/docker/distribution/registry/api/v2.RouterWithPrefix
         0     0%   100%   512.05kB 19.98%  github.com/docker/distribution/registry/handlers.NewApp
```
After push finished:
```
(pprof) top10
1360.93MB of 1429.10MB total (95.23%)
Dropped 293 nodes (cum <= 7.15MB)
Showing top 10 nodes out of 48 (cum >= 17.02MB)
      flat  flat%   sum%        cum   cum%
 1309.22MB 91.61% 91.61%  1313.22MB 91.89%  github.com/docker/distribution/registry/storage/driver/s3-aws.(*writer).Write
   43.11MB  3.02% 94.63%    45.62MB  3.19%  github.com/docker/distribution/registry/storage/driver/s3-aws.(*writer).flushPart
    7.59MB  0.53% 95.16%     7.59MB  0.53%  regexp.onePassCopy
    0.52MB 0.036% 95.20%  1315.24MB 92.03%  io.copyBuffer
    0.50MB 0.035% 95.23%    26.62MB  1.86%  regexp.compile
         0     0% 95.23%       10MB   0.7%  crypto/tls.(*Conn).Handshake
         0     0% 95.23%       10MB   0.7%  crypto/tls.(*Conn).clientHandshake
         0     0% 95.23%       10MB   0.7%  crypto/tls.(*clientHandshakeState).doFullHandshake
         0     0% 95.23%    17.02MB  1.19%  github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run
         0     0% 95.23%    17.02MB  1.19%  github.com/aws/aws-sdk-go/aws/request.(*Request).Send
```

**Comment by klausenbusk** [comment] 2016-03-17 21:25
Htop shows registry is using 134M RES

**Comment by stevvooe** [comment] 2016-03-17 23:19
@RichardScothern Looks like we could do with some buffer pooling in s3.Write.

**Comment by RichardScothern** [comment] 2016-03-17 23:34
Absolutely :100:

**Comment by klausenbusk** [comment] 2016-07-30 17:37
Any update on this?

**Comment by stevvooe** [comment] 2016-08-01 21:04
@klausenbusk Someone has to take the time to fix it or we just wait until the garbage collector gets better.

From the analysis, it is clear that the [`io.copyBuffer`](https://golang.org/src/io/io.go?s=12575:12653#L377) and [`github.com/docker/distribution/registry/storage/driver/s3-aws.(*writer).Write)`](https://github.com/docker/distribution/blob/master/registry/storage/driver/s3-aws/s3.go#L862) are just pressuring the garbage collector. I'm not seeing any evidence of a true leak, where repeated pulls have an effect, other than the 90MB left over after the first pull. The pre-request 10MB isn't necessarily representative, as not all resources may have been allocated at that time (I could be wrong here, as I don't think this is part of the analysis).

In general, it might be good to test the current code base under this kind of load then try it with a buffer pool implementation. It may be also worthwhile to track down the caller of `io.copyBuffer` (likely through `io.Copy` or elsewhere), since we are seeing large allocation happen there. If we can move both of these to buffer pool, the max RSS should decrease, since less garbage will be generated.

**Comment by alexkappa** [comment] 2016-10-10 10:05
@stevvooe is there a workaround for the time being on this issue? The [docker hub](https://hub.docker.com/r/library/registry/tags/) doesn't list any of the older builds unfortunately, so I don't know if we can roll back. 

We're stuck in a phase where the registry keeps restarting every hour or so (depending on activity) and it severely impacts our workflow.

Appreciate the help.

**Comment by RichardScothern** [comment] 2016-10-10 17:45
@alexkappa we do not see evidence of a memory leak here so restarting your registry every hour should not be happening.  The issue here is peak memory usage being higher than it could be.

Are you seeing a prolonged buildup of memory that is never released?  If so I think that may be a different issue. 

Can you provide more information on your setup?  Also, old builds are still available - just use the version you want.

**Comment by alexkappa** [comment] 2016-10-11 10:16
Hi @RichardScothern, indeed while idle it consumes around 25% of its allocated memory, which is not bad. But during pushes it spikes quite heavily causing it to exceed the memory limit so it gets killed.

![Here's an extract from our monitoring](https://dl.dropboxusercontent.com/u/48176547/Screen%20Shot%202016-10-11%20at%2012.11.20.png)

The memory limit is 128Mi. What should be the recommended memory allocation baring this issue in mind?

Thanks,
Alex

**Comment by stevvooe** [comment] 2016-10-12 21:16
@alexkappa You could try decreasing the buffer size used by s3 but this will affect performance.

Have you confirmed the restart of the registry every hour is due to memory usage?

**Comment by alexkappa** [comment] 2016-10-13 07:24
@stevvooe yes I see that clearly from k8s events.

I can try decreasing the buffer size as you said, would that be the `s3.chunksize` configuration? I'm better of with less performance if it gains stability.

**Comment by stevvooe** [comment] 2016-10-14 01:44
`s3.chunksize` is the correct value.

**Comment by krishnasrinivas** [comment] 2017-09-11 06:42
https://github.com/krishnasrinivas/distribution/commit/26aa7e82868ecd991bb4dfb6846900771b6da942 should help with memory usage.

**Comment by Mobe91** [comment] 2018-06-07 06:01
I think I am facing the same issue when running docker registry v2.6.2 with s3 backend as Swarm service on AWS EC2. My swarm service yml contains the following resources restrictions:
```yml
resources:
   reservations:
      memory: 512m
    limits:
      memory: 1g
```
The registry consistently gets killed when I try to push an image containing multiple large layers that are up to 100GB in size.
My `s3.chunksize` is set to 51214400.

**Comment by milosgajdos** [comment] 2023-12-20 11:41
With the new release out https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 I'm inclined to closing this issue. I'd strongly recommend taking it for a spin as it contains a lot of performance optimisations for all supported storage drivers.

**Comment by milosgajdos** [comment] 2024-04-21 08:36
Closing as per my last comment.

**Closed by milosgajdos** 2024-04-21 08:36 UTC
Labels: bug
