### ISSUE TITLE
S3 driver: panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by jkroepke** [distribution/distribution#4411] opened 2024-07-19 12:50 UTC
### Description

While contributing (https://github.com/project-zot/zot/pull/2532) to https://github.com/project-zot/zot and upgrading to https://github.com/distribution/distribution/releases/tag/v3.0.0-beta.1 the CI reports some panics with the S3 driver.

```
# panic: runtime error: invalid memory address or nil pointer dereference
# [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55e3c9ed15a9]
#
# goroutine 89 [running]:
# github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).List(0xc002ae1200, {0x55e3cefaaa98, 0xc001bb45a0}, {0xc002ae65e0, 0x4})
# 	github.com/distribution/distribution/v3@v3.0.0-beta.1/registry/storage/driver/s3-aws/s3.go:837 +0x349
# github.com/distribution/distribution/v3/registry/storage/driver/base.(*Base).List(0xc002dffd90, {0x55e3cefaa9b8, 0x55e3d19830e0}, {0xc002ae65e0, 0x4})
# 	github.com/distribution/distribution/v3@v3.0.0-beta.1/registry/storage/driver/base/base.go:234 +0x5f1
# zotregistry.dev/zot/pkg/storage/s3.(*Driver).List(0xc000eee460?, {0xc002ae65e0?, 0xc0028aec90?})
# 	zotregistry.dev/zot/pkg/storage/s3/driver.go:83 +0x34
# zotregistry.dev/zot/pkg/storage/imagestore.(*ImageStore).GetNextRepository(0xc000eee460, {0x0, 0x0})
# 	zotregistry.dev/zot/pkg/storage/imagestore/imagestore.go:319 +0xeb
# zotregistry.dev/zot/pkg/storage/gc.(*GCTaskGenerator).Next(0xc00286ec60)
# 	zotregistry.dev/zot/pkg/storage/gc/gc.go:[783](https://github.com/project-zot/zot/actions/runs/10004288859/job/27652690776?pr=2532#step:9:784) +0x1ff
# zotregistry.dev/zot/pkg/scheduler.(*generator).generate(0xc0027c6fc0, 0xc00288a8c0)
# 	zotregistry.dev/zot/pkg/scheduler/scheduler.go:462 +0x82
# zotregistry.dev/zot/pkg/scheduler.(*Scheduler).generateTasks(0xc00288a8c0)
# 	zotregistry.dev/zot/pkg/scheduler/scheduler.go:355 +0xdd
# zotregistry.dev/zot/pkg/scheduler.(*Scheduler).getTask(0xc00288a8c0)
# 	zotregistry.dev/zot/pkg/scheduler/scheduler.go:360 +0x1c
# zotregistry.dev/zot/pkg/scheduler.(*Scheduler).RunScheduler.func1()
# 	zotregistry.dev/zot/pkg/scheduler/scheduler.go:280 +0xcc
# created by zotregistry.dev/zot/pkg/scheduler.(*Scheduler).RunScheduler in goroutine 1
# 	zotregistry.dev/zot/pkg/scheduler/scheduler.go:258 +0x18e
```

ref: zotregistry.dev/zot/pkg/storage/s3/driver.go:83

https://github.com/jkroepke/zot/blob/cb04d24813bfbecea4e01bd6561bd27e2c610012/pkg/storage/s3/driver.go#L83

### Reproduce

No idea, but here are CI logs:

The CI

* https://github.com/project-zot/zot/actions/runs/10004288859/job/27652690776?pr=2532#step:9:777
* https://github.com/project-zot/zot/actions/runs/10004288862/job/27652691691?pr=2532#step:7:1047

### registry version

3.0.0-beta.1

**Comment by milosgajdos** [comment] 2024-07-19 12:56
Would you like to contribute to this project as well? Some debugging and a PR would be wonderful.

**Comment by milosgajdos** [comment] 2024-07-19 13:05
Looks like that's a duplicate of https://github.com/distribution/distribution/issues/2479 

It would be good to know why `resp` is actually nil there; I suspect this is some silliness from some S3 API "compatible" APIs. Closing as dupe.

**Comment by jkroepke** [comment] 2024-07-19 13:18
https://github.com/distribution/distribution/pull/4412

**Comment by milosgajdos** [comment] 2024-07-19 13:48
> @milosgajdos resp is not nil. I can't bet nil in line 837. because resp is accessed in line 832 and 828.

yes, sorry, I mistyped...fingers move faster than brain. You're right it's the istruncated part; we  actually fixed it elsewhere in the codebase for different operation.

I'll reopen this

**Closed** 2024-07-19 15:02 UTC
