### ISSUE TITLE
The registry insists my COMODO issued TLS Cert is signed by an unknown authority

### ISSUE THREAD

**Issue by six0h** [distribution/distribution#1184] opened 2015-11-12 22:17 UTC
My Docker host is: Docker version 1.9.0, build 76d6bc9
The Daemon I'm using is an equally new docker-machine on OSX.
I have tested this from Ubuntu 14.04 as well as OSX, and while the error message is slightly better on Ubuntu, its complaining about the same thing.

I am trying to run a Docker registry within my network in my data-center. I have run the container with docker-compose as follows:

```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/star.hotheadgames.com.crt
    REGISTRY_HTTP_TLS_KEY: /certs/star.hotheadgames.com.key
    REGISTRY_HTTP_TLS_CAS: /certs/star.hotheadgames.com.ca.crt
  volumes:
    - /data/registry/images:/var/lib/registry
    - /data/certs:/certs
```

The registry comes online, seems to accept my certificates just fine, but rejects all pushes into the registry due to 'bad certificate', as you can see below:
Docker Daemon Side:

```
The push refers to a repository [registry.hotheadgames.com:5000/chatops/errbot] (len: 1)
unable to ping registry endpoint https://registry.hotheadgames.com:5000/v0/
v2 ping attempt failed with error: Get https://registry.hotheadgames.com:5000/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://registry.hotheadgames.com:5000/v1/_ping: x509: certificate signed by unknown authority
```

Docker Host Side:

```
registry_1 | 2015/11/12 21:34:16 http: TLS handshake error from 172.24.160.62:63967: remote error: bad certificate
```

When i force the client to use --insecure-registry, i can push into it just fine, but I don't want to configure every client to do this, and my certificate IS valid, it's currently present on many of our subdomains, and millions of people around the world are connecting to our clients just fine.

Please assist.

**Comment by stevvooe** [comment] 2015-11-12 22:35
@six0h The registry, even when personified, is not the party doing the insisting. This is actually the docker daemon, from what I can tell.

I am thinking this is probably due to this https://github.com/docker/docker/issues/12756. Docker does not use the host's default certificate chain. You must add the authority to /etc/docker/certs.d/<registry host>/ca.crt.

**Comment by dmp42** [comment] 2015-12-22 20:19
@six0h can you `curl -iv https://registry.hotheadgames.com:5000` and tell us what happens?

**Comment by dmp42** [comment] 2015-12-22 20:20
Rephrasing: can you ssh into the host where your docker daemon runs (likely, inside your virtual machine), and run curl there?

**Comment by KaleoCheng** [comment] 2016-05-16 09:11
I have also been hitting this issue. 

curl output:

```shell
kaleocheng@Mac$ curl -iv https://hub.zbjwork.com:5000
* Rebuilt URL to: https://hub.zbjwork.com:5000/
*   Trying 172.26.4.3...
* Connected to hub.zbjwork.com (172.26.4.3) port 5000 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: hub.zbjwork.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET / HTTP/1.1
> Host: hub.zbjwork.com:5000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: no-cache
Cache-Control: no-cache
< Date: Mon, 16 May 2016 08:56:53 GMT
Date: Mon, 16 May 2016 08:56:53 GMT
< Content-Length: 0
Content-Length: 0
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8

< 
* Connection #0 to host hub.zbjwork.com left intact
```

**Comment by KaleoCheng** [comment] 2016-05-16 09:59
I have also hitting this issue. I merged  the `.ca-bundle`  and the `.crt` , and now it  works well.
```shell
cat hub.mydomain.com.ca-bundle >> hub.mydomain.crt
```

**Comment by tino** [comment] 2018-02-19 16:35
I can confirm that adding the full chain to the cert made it work for me as well.

Quite a PITA to find out though.

**Comment by milosgajdos** [comment] 2024-07-06 10:04
Closing as outdated and largely solved.

**Closed by milosgajdos** 2024-07-06 10:04 UTC
Labels: question
