### ISSUE TITLE
Random "image config verification failed for digest sha256:<sha256>" errors when pulling images

### ISSUE THREAD

**Issue by Soulou** [distribution/distribution#1539] opened 2016-03-17 14:10 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 165
 Running: 147
 Paused: 0
 Stopped: 18
Images: 293
Server Version: 1.10.3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.42 GiB
Name: <edited>
ID: AZNH:RYE6:EPU2:OM3H:RQGL:E6GL:3PCA:BJJP:JVQO:ILYS:G7B4:TWOZ
Username: <edited>
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VPS

*\* Registry setup **

We're running our own **distribution registry, version 2.3** backed by a Swift storage backend and with a nginx reverse-proxy on two instances of the registry. (with redis cache)

**Steps to reproduce the issue:**
1. docker run <image> <cmd>
2. docker commit <id> / docker tag
3. docker push image:tag

Note: The layers pushed are not very large, maximum 300-400MB

On another host
1. docker pull image:tag

**Describe the results you received:**

```
└> sudo docker pull repo:e88527622a7d52a
[sudo] password for leo: 
 e88527622a7d52a: Pulling from repo

a3ed95caeb02: Already exists 
4546a4a8a29d: Already exists 
a898f8c7f6ba: Already exists 
706514fbad74: Already exists 
979168d7ceb7: Already exists 
6a953df111c8: Already exists 
39cb19057166: Already exists 
0d268101d605: Already exists 
517ff1a63fec: Already exists 
cc017fff06a9: Pulling fs layer 
image config verification failed for digest sha256:9315cd9d987b2ec50be5529c18efaa64ebae17f72ae4b292525ca7ee2ab98318
```

**Describe the results you expected:**

No error

*\* Notes **

It happens one image among hundreds, more or less, it happens almost everyday in our production infrastructure but I can't reproduce it willingly.

What can be the cause of that ?

**Comment by Soulou** [comment] 2016-03-17 14:10
Also posted here: https://github.com/docker/docker/issues/21290

**Comment by aaronlehmann** [comment] 2016-03-17 17:34
This looks like a Docker Engine issue, so I'm closing this one in favor of docker/docker#21290.

**Comment by aaronlehmann** [comment] 2016-03-23 16:49
Based on the discussion in docker/docker#21290, this now looks like a bug in either the registry, the Swift storage driver, or Swift itself. I'm reopening this issue to move the discussion back here. Please see docker/docker#21290 for context.

**Comment by Soulou** [comment] 2016-03-24 11:52
> Can you download one of the affected blobs and see if its sha256 hash matches the blob name?

It doesn't.

Docker logs:

```
time="2016-03-24T12:31:05.775091184+01:00" level=error msg="image config verification failed for digest sha256:fdd958b1ea9e36aaa37949d168490771006947d48915946933b7b489fb98cb36"
```

Blob:

```
└> swift download <container> files/docker/registry/v2/blobs/sha256/fd/fdd958b1ea9e36aaa37949d168490771006947d48915946933b7b489fb98cb36/data
ha256sum files/docker/registry/v2/blobs/sha256/fd/fdd958b1ea9e36aaa37949d168490771006947d48915946933b7b489fb98cb36/data
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  files/docker/registry/v2/blobs/sha256/fd/fdd958b1ea9e36aaa37949d168490771006947d48915946933b7b489fb98cb36/data
```

The SHA256 doesn't match, the config blob is really empty (SHA e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

So the metadata issue doesn't seem to be the problem, there are really empty blobs.

**Comment by Soulou** [comment] 2016-03-25 16:27
```
I, [2016-03-25T16:34:41.963104 #15628]  INFO -- : registry.example.com/app-sample:43269c1553cf363 0bc7258e-b686-4a06-9e01-24d496d3749d manifest object: 9085 bytes
I, [2016-03-25T16:35:30.833290 #16458]  INFO -- : registry.example.com/app-sample:51e0f8314925f25 7a92796f-abc9-4661-baae-91f4d5ec8a1a manifest object: 9087 bytes
I, [2016-03-25T16:36:16.571841 #17557]  INFO -- : registry.example.com/app-sample:a0209542a580a87 9757b58e-dd5d-4eb4-98ea-6aceb6c965b4 manifest object: 9087 bytes
I, [2016-03-25T16:36:56.634303 #18257]  INFO -- : registry.example.com/app-sample:743f5758c6b48f1 48cb04c1-eb0f-4ffc-859a-72a71c2ec6fc manifest object: 9087 bytes
Currently trying to reproduce the error artificialy (without success so far)

```
I, [2016-03-25T16:37:40.312100 #18965]  INFO -- : registry.example.com/app-sample:12e2207862cf3d1 1ca7a3c7-4139-4c57-be61-2277fbd03764 manifest object: 9087 bytes
I, [2016-03-25T16:38:30.692195 #19634]  INFO -- : registry.example.com/app-sample:79b56df0652651e 41fbb71a-edb3-4111-ae28-6c3d3b06a49d manifest object: 9087 bytes
I, [2016-03-25T16:39:15.756868 #20416]  INFO -- : registry.example.com/app-sample:f4a0caf80c04845 4966ee23-1665-46e5-a0a3-920fdb03715a manifest object: 9087 bytes
I, [2016-03-25T16:39:57.614513 #21139]  INFO -- : registry.example.com/app-sample:c27b85a154ba11f 0a88a999-14c2-4163-b06a-a4dcff63f98a manifest object: 9087 bytes
I, [2016-03-25T16:40:50.540985 #22990]  INFO -- : registry.example.com/app-sample:ee9282033ec20fa 26ceec71-c1e6-4e69-a544-0497f4e9091a manifest object: 9087 bytes
I, [2016-03-25T16:41:37.752867 #25931]  INFO -- : registry.example.com/app-sample:852a721bb65dd61 81c17cea-08b2-4796-a7d5-4b71f4229e68 manifest object: 9087 bytes
I, [2016-03-25T16:42:27.928190 #27053]  INFO -- : registry.example.com/app-sample:b0a485253d6712c 30d081a9-72b1-40f9-a3f9-a8f95ce77623 manifest object: 9087 bytes
I, [2016-03-25T16:43:27.897366 #28052]  INFO -- : registry.example.com/app-sample:0b77f55200f9c4c c9a59045-3246-486f-a57e-1ad244a1e005 manifest object: 9087 bytes
I, [2016-03-25T16:44:20.018073 #28756]  INFO -- : registry.example.com/app-sample:0f6e5327051eaae 724ac52b-eb39-40f7-bb48-914939a99aae manifest object: 9087 bytes
I, [2016-03-25T16:45:05.921464 #29487]  INFO -- : registry.example.com/app-sample:cefe78a512d3ac8 dfa0545c-8806-4425-b984-c761ded3c6db manifest object: 9087 bytes
I, [2016-03-25T16:46:02.214105 #30649]  INFO -- : registry.example.com/app-sample:da36f124ae970fb a672fbb2-6e37-451e-a8e5-7f733496e6e5 manifest object: 9087 bytes
I, [2016-03-25T16:46:45.238516 #32001]  INFO -- : registry.example.com/app-sample:7813c1101b2c94a a497bdf8-712d-4839-80a3-2a14af4355e1 manifest object: 9087 bytes
I, [2016-03-25T16:47:36.926443 #818]  INFO -- : registry.example.com/app-sample:fa6065d04c2e621 308b7f98-2978-4548-b2e7-aa3c27df2ae4 manifest object: 9087 bytes
I, [2016-03-25T16:48:26.723030 #1874]  INFO -- : registry.example.com/app-sample:33183f8b7c17d9c 97ace633-3a48-47f3-a37f-345296d05ad2 manifest object: 9087 bytes
I, [2016-03-25T16:49:11.991669 #3203]  INFO -- : registry.example.com/app-sample:08f89ab8f15b352 423bf409-a6ae-4983-87be-802a00d48421 manifest object: 9087 bytes
I, [2016-03-25T16:50:12.961042 #4642]  INFO -- : registry.example.com/app-sample:61ae11c1d42e6c6 203c1ef8-177c-435d-83e3-c755c417b15e manifest object: 9087 bytes
I, [2016-03-25T16:51:11.638025 #6360]  INFO -- : registry.example.com/app-sample:92f9645ea76aac8 538c3d17-07ef-4518-8de5-29d362bf078b manifest object: 9087 bytes
I, [2016-03-25T16:52:15.848094 #7636]  INFO -- : registry.example.com/app-sample:7da0dc37672c919 a9de0361-93a5-401b-823f-dc33114690ec manifest object: 9087 bytes
I, [2016-03-25T16:53:12.845157 #8726]  INFO -- : registry.example.com/app-sample:faa1e7e9075784a 35597bb6-2fe9-482d-83ec-66f850e1e5a6 manifest object: 9087 bytes
I, [2016-03-25T16:54:03.897285 #10153]  INFO -- : registry.example.com/app-sample:7820237150fb3fb efb0c305-4c72-41c0-b314-af2ec138bd9e manifest object: 9085 bytes
I, [2016-03-25T16:54:54.378961 #11597]  INFO -- : registry.example.com/app-sample:79d4da2dd06601a 62dca744-ef19-4f2d-a514-26f27d888d75 manifest object: 9085 bytes
I, [2016-03-25T16:56:04.038693 #13330]  INFO -- : registry.example.com/app-sample:8111485c6f125d5 8b1707e7-f074-467e-9eac-5f2d60a552d5 manifest object: 9087 bytes
I, [2016-03-25T16:57:06.483685 #14623]  INFO -- : registry.example.com/app-sample:8bdcf5822bf4b56 a5f63989-41fd-45e5-9efc-80f4abb98c8d manifest object: 9087 bytes
I, [2016-03-25T16:57:58.994706 #16414]  INFO -- : registry.example.com/app-sample:63a91d31ef18374 fc1ce5fe-043d-462e-906c-b178bf0c55b6 manifest object: 9087 bytes
I, [2016-03-25T16:58:52.748914 #17857]  INFO -- : registry.example.com/app-sample:0a46eb5b6ad0b36 587c943e-146b-4cd6-a4e8-83c1caf721d3 manifest object: 9087 bytes
I, [2016-03-25T16:59:44.315230 #19229]  INFO -- : registry.example.com/app-sample:11b75e217258499 7a87cd81-f682-4dda-8c49-3b891c3ead19 manifest object: 9087 bytes
I, [2016-03-25T17:01:03.930279 #20502]  INFO -- : registry.example.com/app-sample:da729e4ab2b84f2 f6ae88a6-c734-4453-8414-20d234d01075 manifest object: 9087 bytes
I, [2016-03-25T17:02:30.812569 #22469]  INFO -- : registry.example.com/app-sample:d1290376a2c5c60 27b95674-683c-469b-9e36-26894576ef2e manifest object: 9085 bytes
I, [2016-03-25T17:03:36.500479 #24620]  INFO -- : registry.example.com/app-sample:175b0482010d244 f53fe665-1763-408d-8cc7-86bfac7bbbb0 manifest object: 9087 bytes
I, [2016-03-25T17:04:34.848840 #27058]  INFO -- : registry.example.com/app-sample:c6d2a80a8581e28 217d9761-fd5b-4e66-a68c-b9e9b3e2b269 manifest object: 9087 bytes
I, [2016-03-25T17:05:46.382930 #29822]  INFO -- : registry.example.com/app-sample:4560d0853ad25c2 1fa39f1c-55d2-447f-8c17-790f8a9f280c manifest object: 9087 bytes
I, [2016-03-25T17:06:38.595217 #31361]  INFO -- : registry.example.com/app-sample:ffe8eed9c40ca6b d8eeddea-392c-483a-ae57-48ea78629db6 manifest object: 9087 bytes
I, [2016-03-25T17:07:47.223908 #32377]  INFO -- : registry.example.com/app-sample:de7ff90aa4ec7fe fe900d00-9d36-4026-a60c-540a0ce1e4e8 manifest object: 9087 bytes
I, [2016-03-25T17:08:49.363178 #1294]  INFO -- : registry.example.com/app-sample:cdb59c488ee0f3f d858aa6f-c1df-45f0-95ec-005f34e9a0e5 manifest object: 9085 bytes
I, [2016-03-25T17:09:56.191141 #2821]  INFO -- : registry.example.com/app-sample:0c4e48e15f17406 acab80d3-fa11-4001-b493-cd3520b89686 manifest object: 9087 bytes
I, [2016-03-25T17:11:00.310841 #4660]  INFO -- : registry.example.com/app-sample:94bdf72ac7a563a 27bd418b-bc34-481a-ab8c-e96e8d8c9bea manifest object: 9087 bytes
I, [2016-03-25T17:12:12.775569 #5963]  INFO -- : registry.example.com/app-sample:b35a9f0b5b8af7a b809f89b-b265-4b3b-aa20-d152eec2973a manifest object: 9087 bytes
I, [2016-03-25T17:13:19.847099 #7458]  INFO -- : registry.example.com/app-sample:54b0e68a1d6f7b5 38e68fee-8ca1-4014-ac29-01ca2927671c manifest object: 9087 bytes
I, [2016-03-25T17:14:13.666142 #8393]  INFO -- : registry.example.com/app-sample:0f22b1494b0efc4 d6ec7c44-12d0-4ce5-a992-77a4221c1a59 manifest object: 9087 bytes
I, [2016-03-25T17:15:04.010544 #9782]  INFO -- : registry.example.com/app-sample:4e944ccdc0faaf1 969f74fa-5d1a-4526-a34f-862cab46931d manifest object: 9087 bytes
I, [2016-03-25T17:16:25.990134 #11619]  INFO -- : registry.example.com/app-sample:37e1dedc9df4dd5 acff0250-0c98-4417-bde2-e94253cee748 manifest object: 9087 bytes
I, [2016-03-25T17:17:27.733048 #13136]  INFO -- : registry.example.com/app-sample:58cd6bcc8d53d71 513170cf-bcab-409b-bb8f-c460ace28b53 manifest object: 9085 bytes
I, [2016-03-25T17:18:24.751417 #14933]  INFO -- : registry.example.com/app-sample:8d6b0e211a31211 df465029-1fdc-49a1-8fac-2910005a7c41 manifest object: 9085 bytes
I, [2016-03-25T17:19:27.549727 #16566]  INFO -- : registry.example.com/app-sample:c17adf416cdda43 679c86d4-a353-4bab-893f-31d3ff80232b manifest object: 9087 bytes
I, [2016-03-25T17:20:30.066522 #17615]  INFO -- : registry.example.com/app-sample:10727e205c4ce44 74609e81-0668-4092-b1c5-6da2db124c78 manifest object: 9087 bytes
I, [2016-03-25T17:21:56.986155 #19711]  INFO -- : registry.example.com/app-sample:6987e09bf976503 e49affec-4de6-4bd5-966b-fe320e368f4c manifest object: 9087 bytes
I, [2016-03-25T17:23:15.645050 #22731]  INFO -- : registry.example.com/app-sample:bc39b8b38821372 afaffa9f-8c88-4d95-b868-fa8ab20fcf9f manifest object: 9087 bytes
```

**Comment by Soulou** [comment] 2016-03-25 17:22
More details about my investigation:

```
I, [2016-03-25T18:12:39.787219 #32710]  INFO -- : registry.example.com/app-sample:8c26dd2cb39fa8b 9ac1c509-2845-4112-922f-f96f4ece835a manifest object: 0 bytes
W, [2016-03-25T18:12:40.431968 #32710]  WARN -- : registry.example.com/app-sample:8c26dd2cb39fa8b 9ac1c509-2845-4112-922f-f96f4ece835a fail to push registry.example.com/app-sample:8c26dd2cb39fa8b (Empty uploaded manifest for registry.example.com/app-sample:8c26dd2cb39fa8b), retry in 3 seconds, 2 retry left
I, [2016-03-25T18:14:45.038832 #32710]  INFO -- : registry.example.com/app-sample:8c26dd2cb39fa8b 9ac1c509-2845-4112-922f-f96f4ece835a manifest object: 8829 bytes
```

I did succeed to reproduce the empty manifest effect, I detected it and delete the empty blob with a direct swift request and retry to push the image, with success.

The issue now is to know if that's swift fault or the registry's fault.

**Comment by Soulou** [comment] 2016-03-25 18:24
Distribution error logs:

Event if the push succeeds (or sometime docker retries it), I can see quite a lot of 'blob unknown' errors in the log of 'distribution'. I assume all that can be related.

```
time="2016-03-25T14:41:19.494006035Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:cfc302d6d711c20ea457edceaf9ba97f32784b4b4a5608262e808a5a5dfb3c4c err.message="blob unknown to registry" go.version=go1.5.3 
time="2016-03-25T14:44:24.435148639Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:aa04d2b7d47076f063b37849531408f2d1b30507ee1d9cf5c8b184a616139316 err.message="blob unknown to registry" go.version=go1.5.3 
time="2016-03-25T14:51:26.068232903Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:2ad365d1949f30c4564f2a7f7f7e7c4ffa136e4b4a20b39e077f8f2e9faf4f41 err.message="blob unknown to registry" go.version=go1.5.3 
time="2016-03-25T14:52:02.383534638Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:a53321f49e96122edd98a63b986c3368522fb7b9cd203d7a80d0762002e5b29e err.message="blob unknown to registry" go.version=go1.5.3 
time="2016-03-25T15:21:10.684037265Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:1e44dcba8bf99440a83b9b12ef824465d5644f3ffa93f59830bf5f2cf84ad40d err.message="blob unknown to registry" go.version=go1.5.3 
time="2016-03-25T15:41:16.387498673Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:927e1893f66da889d0f4582383e2a68461642e94f28e1519b48d8e4a9111cf6d err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T15:43:34.525928264Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:b704bf27036c6ca4798b49fda4dbc143b9ccedae6e3fa45dacb210cf1a77975f err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T15:50:33.561326254Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:2390d7d9517f064232fecb3910c724be8ad61e73c8fd7eb80e4f8f76f433c3ee err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:06:15.041207424Z" level=error msg="canonical digest does match provided digest" auth.user.name=0 canonical=sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 go.version=go1.5.3
time="2016-03-25T16:06:17.54232579Z" level=error msg="response completed with error" auth.user.name=0 err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:0c408c7fd7b37cd3c50198d4959aae1252c64b1fc44dfa2e934d8b0371b445cd, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3
time="2016-03-25T16:07:04.976135228Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:c5544c4d5f8955380c26fbc27b9e60e90d7d27a6cc1e07d7fb273a826fa82a14 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:10:21.014242278Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:fd7e9cade7241d069da1dc558f8ae05d5a6572459c0254d78871c73812898d3c err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:22:24.391260369Z" level=error msg="canonical digest does match provided digest" auth.user.name=0 canonical=sha256:fd6bfb9dcbabe67e7f5b6e196e3c5c103127872cea4a864447eb766edc9c419a go.version=go1.5.3
time="2016-03-25T16:22:26.600081066Z" level=error msg="response completed with error" auth.user.name=0 err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:0093a3d4761964ab89f0dfd79d59c45a310071aae8725c076c78733042f14c63, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3
time="2016-03-25T16:31:14.800027877Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:63930504b3a889d71d38830c1b3acfb58ed8b62b695c3268dd74f23c09189a89 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:43:57.647953247Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:e540934271b8465a8663a16ab4b7b333eda9bef33286fda0545d3f5dba1a0713 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:53:23.342084554Z" level=error msg="canonical digest does match provided digest" auth.user.name=0 canonical=sha256:ea914d1b0b7ed2b8b135e228483898963beb79e31c42e7106a974fcffce92917 go.version=go1.5.3
time="2016-03-25T16:53:56.950974199Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:ee3334ffe20e2eca9a38de9a7ee2fde979856e13b78662d6295ebf9708551a73 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T16:53:57.392023122Z" level=error msg="response completed with error" auth.user.name=0 err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:32b9ba382b8661a25687ae0bc4757abaabe47daadcc1098b1a288a96ccdc3d28, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3
time="2016-03-25T16:56:52.68266739Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:dc8df92333541ad4c0f700671b3d2f0a2ff7fa7b4a44df4abd14f88d5beeed34 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:08:51.960915383Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:5c3d4544e7d48ee9a996f76ac5a8cbcba78b11258c61570e4b6bab60c1d0b8f2 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:12:42.596144519Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:a379494c9531a2c06951f0a2767c794c0aede86a39616d2ad580734270815874 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:13:44.140399718Z" level=error msg="canonical digest does match provided digest" auth.user.name=0 canonical=sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 go.version=go1.5.3
time="2016-03-25T17:14:08.308216751Z" level=error msg="response completed with error" auth.user.name=0 err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:a379494c9531a2c06951f0a2767c794c0aede86a39616d2ad580734270815874, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3
time="2016-03-25T17:21:45.822660708Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:34437fb50911b643d3db747fe2621469a41433b24b917dec1c33c63353b43af1 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:30:39.3425842Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:4302884202f8d38ff5b3319272a4cd78118f629a84c008c192f5cb8eba502f43 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:43:31.417123582Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:7fa5fe9214cb1fc6683a0bdf396fef7ccd93ceaef86ab64b99e135e55cb8e017 err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:47:18.123396179Z" level=error msg="canonical digest does match provided digest" auth.user.name=0 canonical=sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 go.version=go1.5.3
time="2016-03-25T17:47:52.95931358Z" level=error msg="response completed with error" auth.user.name=0 err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:8971ff8c2880e3b0606b9795366279d05ab52787f377f0d78cfc1c14a6992d50, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3
time="2016-03-25T17:53:01.329074103Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:375cc4515b6b0a35824f7f3740494fba7481f6816b28ff4f78d5b768498c9e3b err.message="blob unknown to registry" go.version=go1.5.3
time="2016-03-25T17:54:51.716994618Z" level=error msg="response completed with error" auth.user.name=0 err.code=unknown err.detail="swift: HTTP Error: 503: 503 Internal Server Error" err.message="unknown error" go.version=go1.5.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json"
time="2016-03-25T18:02:13.274681367Z" level=error msg="response completed with error" auth.user.name=0 err.code="blob unknown" err.detail=sha256:df595fdc07ae8605e4b1500f55760e3f13cddfd727052e10eaebedae29277e6b err.message="blob unknown to registry" go.version=go1.5.3
```

**Comment by janeczku** [comment] 2016-03-25 18:30
I am facing the same issue with swift backend on OVH. I get intermittent `image config verification failed for digest` errors on pull and `digest invalid: provided digest did not match uploaded content` on push.
Also, once an image upload is corrupted it is very difficult to restore the image as consecutive pushes will not rewrite the corrupt layer.

Related issue with the swift backend: https://github.com/docker/distribution/issues/1013

**Comment by Soulou** [comment] 2016-03-31 15:24
Something new, sometimes the manifest is ok, but it's the binary blob of the layer which is broken:

```
    {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 300126448,
         "digest": "sha256:57d3648144f06c3db4eb98cba46ea03bbfae897b544e6655319dc8fa46d23a90"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 93529577,
         "digest": "sha256:1cfcaf2a11aa3e743d7fd7ba47e403a64634dfc4042e0c37ba045580155aa630"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:7d1323de0a1ceb3f5fb9a532e3b17f213163ad30b04aaa2bf6350a769ad15b3f"
      }
```

I've been able to see it quickly as there is no 'size' available.

After deleting the blob `7d132...`, redoing a `docker push`, it's working, here is the diff of manifest:

```
       {
          "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
+         "size": 94627608,
          "digest": "sha256:7d1323de0a1ceb3f5fb9a532e3b17f213163ad30b04aaa2bf6350a769ad15b3f"
       }
```

The size has been added :-)

I assume in the first case the size was 0 and wasn't serialized by Go because it's a 0 value and there is an omitempty on the field, after a second upload attempt, the size has been filled, and everything is ok.

**Comment by Soulou** [comment] 2016-04-08 18:15
I've been speaking with OVH support so far, here is there answer, I don't know what does it worth.. I've been explaining them that some file have wrong metadata (0 byte but file is present), I'm not sure it affects this bug as here files are really empty.

```
Hi Mr Unbekandt,

You're right, you doesn't have the file, actually it's another problem.

To resume the situation we doesn't have support of Large files in our Public Cloud.

For this reason you can't upload a file larger than 5Go.

Your file is a manifest and its contain only informaitons of different segment of your object.

The original file do 55Mo, you don't have to split it for Large Object support.
```

**Comment by depay** [comment] 2016-08-02 09:49
i'm using a registry-proxy before central registry. Reproduce something alike:
1. pull a image
2. delete one of blob in proxy's storage
3. rmi, then pull that image again, daemon log like "filesystem layer verification failed for digest sha256:xxxxxxxxxxxx"

**Comment by RichardScothern** [comment] 2016-08-02 16:27
@depay : I do not think you are seeing the same issue.  If you are directly removing content from the storage then the registry descriptor caches will not be invalidated.  The cached content will be removed by the scheduler.

**Comment by depay** [comment] 2016-08-03 06:39
@RichardScothern i am also curious about that, but the deletion by proxy's scheduler really made the same error log..then i remove the in-memory cache config of proxy, it works normally. I'm using v2.2.1 and wondering there may be something wrong with the proxy's expire scheduler or in-memory cache.

**Comment by RichardScothern** [comment] 2016-08-03 17:06
@depay there was a bug (my fault 😿 ), which was fixed in 2.3 (I think).  We are now on version 2.5, so if you are able to upgrade that would be spiffing.

**Comment by depay** [comment] 2016-08-04 01:23
ooooops, my version is tooooo old...but i'm afraid of the compatibility between v2.3 & v2.2 with kinds of client version(1.7/1.9/1.12) about the manifest Schema 2, due to the v2.3 compatibility [document](https://github.com/docker/distribution/blob/master/docs/compatibility.md#registry-v23).

**Comment by mastertinner** [comment] 2017-01-16 14:00
I think I'm having a very similar problem with an S3 backend. I'm using registry `2.6.0-rc.2` and docker `1.12.6`. The problem is similar in that I can push images but when pulling them, I get the following output:

```bash
registry docker pull registry.scapp.io/elastic
Using default tag: latest
latest: Pulling from elastic
75a822cd7888: Verifying Checksum
57de64c72267: Download complete
cd1fc1696ecd: Download complete
34836fffacad: Download complete
4f4f57ee64ee: Download complete
975b9daf71f5: Verifying Checksum
6c6cde91351a: Download complete
cda5a5d3e7b3: Download complete
097a2fd195eb: Download complete
9c2393d697fe: Download complete
77a9b03f44da: Download complete
7b23fbfd6595: Download complete
3c8bd3acdba9: Download complete
df9745689e27: Download complete
filesystem layer verification failed for digest sha256:975b9daf71f592b2408562d1dd1cc8593b6a97a1399c2b9b4a2e453090cf8884
```

where the two layers that didn't complete are around 100 MB and the ones that downloaded successfully are smaller.

**Comment by aaronlehmann** [comment] 2017-01-17 18:50
@mastertinner: This seems a bit different from the issue discussed earlier in this thread. Could you please open a separate issue? It may be helpful to include logs from the registry when you push and pull the affected image.

**Comment by mastertinner** [comment] 2017-01-21 14:13
Thanks, @aaronlehmann. I created a separate issue for my S3 related problem: https://github.com/docker/distribution/issues/2168

**Comment by drnybble** [comment] 2017-08-02 14:27
Any updates on this issue? We are seeing random filesystem layer verification failed for digest sha256 errors for our private registry using SoftLayer ObjectStore (Swift driver).

**Comment by stefli** [comment] 2018-04-26 05:57
Try below steps:

1. Build with some options, in order to remove the cache and checksum
```
docker build --rm=true --no-cache --disable-content-trust=true -t image-name .
docker tag image-name 192.168.0.2:5000/image-name
docker push --disable-content-trust=true 192.168.0.2:5000/image-name
```

2. Try to docker pull in any server, it should be work now without any exception tips.

3. Use normal operation to build the image.
```
docker build -t image-name .
docker tag image-name 192.168.0.2:5000/image-name
docker push 192.168.0.2:5000/image-name
```

4. Try to docker pull in any server, it works.

**Comment by milosgajdos** [comment] 2024-07-17 19:50
Closing as wildly outdated.

**Closed by milosgajdos** 2024-07-17 19:50 UTC
