### ISSUE TITLE
Can not access Docker registry from a different machine.

### ISSUE THREAD

**Issue by hantsy** [distribution/distribution#2515] opened 2018-02-06 03:46 UTC
Currently I am using the latest Docker Toolbox 18.01 under Windows 10.

I created a  Docker Registry  in one machine, and tried to  run other dockers for my projects in another machine.  In this Docker registry machine,  docker pull and push commands worked well.

 In the machine for my project, I added localhost:5000 or 127.0.0.1:5000 into the machine specific `config.json`.

```
            "InsecureRegistry": [
                "localhost:5000",
                "127.0.0.1:5000"
            ],
```

Docker push  did not work at all.

```
$ docker push localhost:5000/auth-service:latest
The push refers to repository [localhost:5000/auth-service]
Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: getsockopt: connection refused

```

BTW, I am sure I have set the port 5000 mapped to localhost in the docker registry machine, and I can access http://localhost:5000/v2/_catalog in my browser.

**Comment by thaJeztah** [comment] 2018-02-06 09:27
Localhost from inside a VM will refer to localhost inside that machine, so if the registry is running inside another VM, that’s expected

**Comment by hantsy** [comment] 2018-02-07 08:52
@thaJeztah  But I used docker registry machine ip to connect, it still does not work.

**Comment by thaJeztah** [comment] 2018-02-07 09:43
Looks like this is an issue in your setup; I'm not able to reproduce:

Create two machines:

```
docker-machine create --driver=virtualbox one
docker-machine create --driver=virtualbox two
```

```
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
one        -        virtualbox   Running   tcp://192.168.99.100:2376           v18.01.0-ce   
two        *        virtualbox   Running   tcp://192.168.99.101:2376           v18.01.0-ce   
```

Connect to machine "one", and start a registry;

```bash
eval $(docker-machine env one) 
docker run -d -p 5000:5000 registry:2
```

Connect to machine "two", and push/pull from the registry on host "one"

```bash
eval $(docker-machine env two)

docker pull busybox
docker tag busybox 192.168.99.100:5000/busybox
docker push 192.168.99.100:5000/busybox
```

That works, but the registry is not configured as "insecure", push fails, but you can see that it's trying to push

```
The push refers to repository [192.168.99.100:5000/busybox]
Get https://192.168.99.100:5000/v2/: http: server gave HTTP response to HTTPS client
```

**Comment by hantsy** [comment] 2018-02-08 04:06
Got the same error even I added  192.168.99.100:5000 to the project machine config(`InsecureRegistry` of docker machine *config.json*, I have restarted it after changed the config.json).

```
"InsecureRegistry": [
        "192.168.99.100:5000"
],
```

**Comment by stevvooe** [comment] 2018-03-15 01:32
@hantsy How would be able to access a registry on another machine if you are pushing and pulling from localhost?

**Comment by hantsy** [comment] 2018-03-15 01:48
@stevvooe  What I need is put the docker registry and app containers into different virtualbox machines.

**Comment by milosgajdos** [comment] 2024-05-27 21:23
@hantsy is this still an issues for you? If not, mind closing it.

**Comment by thaJeztah** [comment] 2024-05-28 08:44
Let's close this one; it's 6 Years old now.

**Closed by thaJeztah** 2024-05-28 08:44 UTC
Labels: question
