### ISSUE TITLE
Auto renew certs

### ISSUE THREAD

**Issue by 5andr0** [distribution/distribution#4504] opened 2024-11-11 15:15 UTC
### Description

So to my understanding `ListenAndServe` is only called at startup and then queries certs from letsencrypt or HTTP.TLS.Certificate.
So if these certs have to be renewed, the user has to restart the whole registry?

It would be nice to have a cert expiration check and autorenew letsencrypt or for certs added by HTTP.TLS.Certificate offer a command to reload certs instead of restarting everything.

Looks like for now i still have to use a reverse proxy who manages the certs.
I hope cert renew makes it into the v3 release

**Comment by ialidzhikov** [comment] 2024-11-12 07:23
Duplicate of https://github.com/distribution/distribution/issues/3712

**Closed** 2024-11-12 08:11 UTC
