### ISSUE TITLE
Unknown error with 2.5.1/2.6.0-rc1/2.6.0-rc2 and Amazon S3 

### ISSUE THREAD

**Issue by javisabalete** [distribution/distribution#2119] opened 2017-01-03 08:00 UTC
Testing with Amazon S3

**Run command**
```
docker run -d -p 5000:5000 --restart=always --name registry2 -v /root/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/MYCERT.crt -e REGISTRY_HTTP_TLS_KEY=/certs/MYCERT.key -e REGISTRY_STORAGE_DELETE_ENABLED=True -e REGISTRY_STORAGE=s3 -e REGISTRY_STORAGE_S3_BUCKET=MYBUCKET -e REGISTRY_STORAGE_S3_ACCESSKEY=MYACCESSKEY -e REGISTRY_STORAGE_S3_REGION=eu-west-1 -e REGISTRY_STORAGE_S3_SECRETKEY=MYSECRETKEY registry:2.6.0-rc.2
```

**Log Error**
```
[03/Jan/2017:07:44:38 +0000] "GET /v2/_catalog HTTP/2.0" 500 133 "" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
time="2017-01-03T07:44:38Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: invalid path: /docker/registry/v2/repositories/" err.message="unknown error" go.version=go1.7.3 http.request.host="MYREGISTRYURL:5000" http.request.id=3853a3ed-c3fe-4861-bf50-173a538cdd32 http.request.method=GET http.request.remoteaddr="MYIP:60599" http.request.uri="/v2/_catalog" http.request.useragent="Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=11.306346ms http.response.status=500 http.response.written=133 instance.id=4b00186d-80ec-42ed-99fc-fe46e67c1e71 version=v2.6.0-rc.2 
```

**Browser Error**
https://MYREGISTRYURL:5000/v2/_catalog
```
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"Path":"/docker/registry/v2/repositories/","DriverName":"s3aws"}}]}
```

Amazon policies aren't the problem, tested with S3FullAccess polocy

**Comment by JaviSabalete** [comment] 2017-01-03 08:17
With <= 2.5.0 not working neither but no errors

**Log Error**
```
[03/Jan/2017:08:09:09 +0000] "GET /v2/_catalog HTTP/1.1" 200 20 "" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
time="2017-01-03T08:13:28Z" level=info msg="response completed" go.version=go1.6.3 http.request.host="MYREGISTRYURL:5000" http.request.id=1e234ebd-74cb-4828-bc65-922eb0148659 http.request.method=GET http.request.remoteaddr="MYIP:33167" http.request.uri="/v2/_catalog" http.request.useragent="Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=19.635087ms http.response.status=200 http.response.written=20 instance.id=eca3e7ae-f179-4f12-a392-c50ef2e8513d version=v2.5.0
```

**Browser Error**
https://MYREGISTRYURL:5000/v2/_catalog
```
{"repositories":[]}
```

**Comment by dmcgowan** [comment] 2017-01-03 19:03
@JaviSabalete thanks for report and testing the release candidate. While I look into this do you mind putting the registry in debug mode and including the debug logs.

**Comment by dmcgowan** [comment] 2017-01-03 20:07
@JaviSabalete unable to reproduce. Please add `-e REGISTRY_LOGLEVEL=debug` to the command and send the result. The trace should have more information as to where the invalid path error occurred.

**Comment by JaviSabalete** [comment] 2017-01-05 12:04
Sure


[debugregistry.txt](https://github.com/docker/distribution/files/687194/debugregistry.txt)

**Comment by dmcgowan** [comment] 2017-01-05 19:01
@JaviSabalete thanks!

It is this call to `Stat` which is erroring out
```
time="2017-01-05T11:55:24Z" level=debug msg="s3aws.Stat(\"/docker/registry/v2/repositories/\")" go.version=go1.7.3 http.request.host="MYREGISTRYURL:5000" http.request.id=229b2b83-64eb-4155-83be-334a8a2ff8b1 http.request.method=GET http.request.remoteaddr="MYIP:38167" http.request.uri="/v2/_catalog" http.request.useragent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" instance.id=1f56b642-adf5-4b1b-af24-c4e9a5a10a0c trace.duration=9.975µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=4f010eb8-8a17-43be-b118-03355eb23c17 trace.line=137 version=v2.6.0-rc.2 
```

because `/docker/registry/v2/repositories/` does not match the expected regexp `^(/[A-Za-z0-9._-]+)+$`

I am looking through the code to understand exactly what is going on. The previous call to list should return all the descendants of `/docker/registry/v2/repositories` and not sure yet why `/docker/registry/v2/repositories/` is in that list. If you have the `aws` cli tool, would you mind looking at the out output of `$ aws s3 ls s3://yourbucket/docker/registry/v2/repositories/`

**Comment by dmcgowan** [comment] 2017-01-05 19:13
Ok, I will able to reproduce this issue by doing

```
$ aws s3 cp somefile "s3://mybucket/docker/registry/v2/repositories//"
```

This "empty" directory name causes results to be returned from `List` which fail on `Stat`. Catalog should probably be updated to ignore these errors rather than error out. An error will also occur if you create a file under that directory which does not match the regexp, `s3://mybucket/docker/registry/v2/repositories/with space` also failed.

If this is the case with your bucket, I would suggest removing the unsupported files. If these files were created by the registry, then I will investigate further to figure out how it was created.

**Comment by JaviSabalete** [comment] 2017-01-05 21:32
No empty directory on this folder

```
~$ aws s3 ls s3://MYBUCKET/docker/registry/v2/repositories/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
2016-05-23 19:48:05          0
```

I uploaded a file into empty directory

```
~$ aws s3 cp testfile "s3://MYBUCKET/docker/registry/v2/repositories//"
upload: ./testfile to s3://MYBUCKET/docker/registry/v2/repositories//testfile
```

I see it

```
~$ aws s3 ls s3://MYBUCKET/docker/registry/v2/repositories/
                           PRE /
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
                           PRE xxxxxxxx/
2016-05-23 19:48:05          0 
```

Same error

```{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"Path":"/docker/registry/v2/repositories/","DriverName":"s3aws"}}]}```


Probably s3 lib was wrong? It's strange because push and pull works perfectly

**Comment by dmcgowan** [comment] 2017-01-05 22:33
> No empty directory on this folder

Did you see anything under the directory that wasn't part of a repository name or wouldn't match the regexp I sent? 

> Probably s3 lib was wrong? It's strange because push and pull works perfectly

The s3 library can be defensive here, but it is isn't expecting other files to exist in that directory which were not created through the driver. It is still unclear to me what in that directory may be causing it. I understand the failure after running that command, but once you remove that file I wouldn't expect the failure to continue. Still looking for evidence that the s3 library may have created this content or incorrectly parsed validly content. Wouldn't expect push/pull to be effected unless a directory was name was corrupted.

**Comment by JaviSabalete** [comment] 2017-01-05 23:51
Ok! Let's see 3 tests

listfiles contains ``aws s3 ls --recursive s3://MYBUCKET/docker/registry/v2/repositories/ >> listfiles``and removed useless columns

```
docker/registry/v2/repositories/
docker/registry/v2/repositories/apache2/_layers/sha256/00112a0f9c340f79d1e8ad4bf6d5a8225a33907e4c5b3b8cd4f46325463140a9/
docker/registry/v2/repositories/apache2/_layers/sha256/00112a0f9c340f79d1e8ad4bf6d5a8225a33907e4c5b3b8cd4f46325463140a9/link
docker/registry/v2/repositories/apache2/_layers/sha256/001cbd34d4e955588193efeba3d6379adc5dc55ecc749029acc323b93f6fed86/link
docker/registry/v2/repositories/apache2/_layers/sha256/00387f8a983383d2d5bb16fde691d594edbe39ab37e12358ce0080457d60590d/link
docker/registry/v2/repositories/apache2/_layers/sha256/003db986052637376c53bd7959e878614ace4253d44a2c9535b02887947f833a/
docker/registry/v2/repositories/apache2/_layers/sha256/003db986052637376c53bd7959e878614ace4253d44a2c9535b02887947f833a/link
docker/registry/v2/repositories/apache2/_layers/sha256/00513833e07c3c094f790748f591278913ed66ffe113c2939e1fd4da7367b8cd/link
docker/registry/v2/repositories/apache2/_layers/sha256/006eac82ef5e756c31d418d2ad58d780dfee6744e6c69d13066b28735b08983f/
docker/registry/v2/repositories/apache2/_layers/sha256/006eac82ef5e756c31d418d2ad58d780dfee6744e6c69d13066b28735b08983f/link
docker/registry/v2/repositories/apache2/_layers/sha256/0087c14d8e6b28f9b4e37c8b81013de9e8022f38ecc9a5a36774c559893e5eeb/link
docker/registry/v2/repositories/apache2/_layers/sha256/008b3ab9eeed94ed127eca831c09672b896a02aa5f90b13ffe26c90c2b8edf74/
docker/registry/v2/repositories/apache2/_layers/sha256/008b3ab9eeed94ed127eca831c09672b896a02aa5f90b13ffe26c90c2b8edf74/link
docker/registry/v2/repositories/apache2/_layers/sha256/00e959a4963648cd18f5d8be9040b3552b626193815320a5c1b530eaa7ba120d/link
docker/registry/v2/repositories/apache2/_layers/sha256/00ff1640c2dfb0e9a7a0ce59b5f4ce68f862ba9c8f191ce33436a8d0f35d8b3f/
docker/registry/v2/repositories/apache2/_layers/sha256/00ff1640c2dfb0e9a7a0ce59b5f4ce68f862ba9c8f191ce33436a8d0f35d8b3f/link
```

**File lengh**
```
~$ cat listfiles | wc -l
8687
```

**Test 1**
With ```^[A-Za-z0-9._-]+$```no one pass regex because regex don't have /
```
~$ cat listfiles | egrep -v "^[A-Za-z0-9._-]+$" | wc -l
8687
```

**Test 2**
With ```^[A-Za-z0-9._-/]+$``` all pass
```
~$ cat listfiles | egrep -v "^[A-Za-z0-9._-/]+$" | wc -l
0
```

**Test 3**
Looking for double /
```
~$ cat listfiles2 | grep "//" | wc -l
0
```


This bucket is exclusive for docker registry and configured with registry completely empty. No one has permissions on it so all objects were created by registry

**Comment by stevvooe** [comment] 2017-01-09 21:30
@JaviSabalete `_` is not a valid character for a repository name. Could you remove that from the test regexp and run those examples again?

**Comment by JaviSabalete** [comment] 2017-01-10 09:25
Same results @stevvooe , in fact, these are my container names

~$ aws s3 ls s3://MYBUCKET/docker/registry/v2/repositories/ 
                           PRE apache2/
                           PRE data/
                           PRE debian/
                           PRE git/
                           PRE mysql/
                           PRE openvpn/
                           PRE phpmyadmin/
                           PRE postfix/
                           PRE ubuntu/
2016-05-23 19:48:05          0

All names passes regex

How you knows, on every repository have 3 folders with _ but this isn't the problem isn't?

```
_manifests
_layers
_uploads
```

**Comment by stevvooe** [comment] 2017-01-10 18:19
@JaviSabalete The `_` prefixed files are "system" directories, so this looks okay.

@dmcgowan I think your reproduction shows that we need a fix in the driver. Can we add a test case that hits one of these bad paths?

**Comment by JaviSabalete** [comment] 2017-01-12 07:12
Sounds great, I'll test again when you make some changes

**Comment by afrazkhan** [comment] 2017-01-12 09:32
In case it helps, I did end up getting at least the `_catalog` endpoint to work (didn't test the others) when I set the root directory to "registry". i.e. Setting `REGISTRY_STORAGE_S3_ROOTDIRECTORY="/registry"`

**Comment by bhuisgen** [comment] 2017-07-04 13:25
Still the same problem with latest master branch. Thanks to @afrazkhan for the config fix.

**Comment by tnextday** [comment] 2018-08-24 05:41
I also encountered this error, I entered s3 and found that someone created the `docker/registry/v2/repositories/` object.
like this：
```xml
<ListBucketResult
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>docker-registry</Name>
    <Prefix>docker/registry/v2/repositories/</Prefix>
    <Marker/>
    <MaxKeys>1000</MaxKeys>
    <Delimiter>/</Delimiter>
    <IsTruncated>false</IsTruncated>
    <Contents>
        <Key>docker/registry/v2/repositories/</Key>
        <LastModified>2018-08-02T10:44:23.336Z</LastModified>
        <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
        <Size>0</Size>
        <StorageClass>STANDARD</StorageClass>
        <Owner>
            <ID>registry</ID>
            <DisplayName>registry</DisplayName>
        </Owner>
    </Contents>
    <CommonPrefixes>
        <Prefix>docker/registry/v2/repositories/ceph/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>docker/registry/v2/repositories/debian/</Prefix>
    </CommonPrefixes>
</ListBucketResult>
```
But the s3aws driver won't delete the `/` at the end of the Content key.

https://github.com/docker/distribution/blob/90070b336766a20c1973c89aed1005dce9320484/registry/storage/driver/s3-aws/s3.go#L662

The solution is to delete the `docker/registry/v2/repositories/` object

**Comment by UlTriX** [comment] 2018-12-20 15:53
@tnextday I have the same problem. Can you tell me how can I delete the docker/registry/v2/repositories/ object ?

**Comment by offero** [comment] 2020-01-21 21:35
docker/registry/v2/repositories/ contains all of the repo data, why would we delete that?

**Comment by milosgajdos** [comment] 2023-08-13 15:00
@javisabalete can you verify if this still happens on the latest `2.8.x` release?

**Comment by milosgajdos** [comment] 2023-12-19 15:07
Closing for the lack of noise. If you manage to reproduce it in `2.8.x` feel free to reopen.

**Closed by milosgajdos** 2023-12-19 15:07 UTC
Labels: bug
